### ISSUE TITLE
How to stop recognizing immediately on Android sdk

### ISSUE THREAD

**Issue by livesun** [Azure-Samples/cognitive-services-speech-sdk#253] opened 2019-05-31 06:18 UTC
Before returning the result, I want to end the current conversation immediately and start a new conversation at the same time, but I call the stopContinuousRecognitionAsync.get() method, which is not an immediate interrupt, It will wait for a maximum of 10 seconds. End the current conversation completely.
What method should I call or how can I stop the current conversation immediately without obstructing my new conversation?

**Comment by spacetimeglitch** [comment] 2019-05-31 20:32
Thanks for the feedback.

```stopContinuousRecognitionAsync()``` signals the SpeechRecognizer object to "start" the stopping process. The ```future<void>``` that is returned from```stopContinuousRecognitionAsync()``` will not complete until the request has been satisfied, i.e., actually stopped. Thus, the call to ```stopContinuousRecognitionAsync().get()``` will wait for the stopping to actually complete, and thus be stopped. ```stopContinuousRecognitinAsync()``` is a non-destructive operation, meaning, if there is audio that's currently being evaluated by the service, it will be completed prior to "stopping". The 10 seconds that you're observing is the maximum timeout that we allow the stop request to take (which we plan on removing to allow longer sentences to still be recognized).

We intend to in the future have a method (or an override of the current method) that will allow you to specify that you'd like to actually abandon the current audio evaluation. 

May I ask, what's the user scenario you're trying to enable with the "immediately abandon the current recognition"?

**Comment by livesun** [comment] 2019-06-01 02:12
Thank you for your answer.
My scenario is that the user initiates a recorded dialog to identify it. Some users may immediately close the dialog to undo the voice. In this case, I must let him wait for a maximum of 10 seconds to completely stop the conversation. Close the dialog, this will make the user wait for a long time, but if I don't call stopContinuousRecognitionAsync(), the recording will still work in the background, but if the stopContinuousRecognitionAsync() and the dialog are closed asynchronously, I can't guarantee that the next recording will be able to Correct identification.

My current practice is to interrupt the recognition scene by controlling the closing and pausing of the recording by customizing the PullAudioInputStreamCallback. It will call canceled to end the conversation. The next time the user starts the conversation, I will re-recognize the new TranslationRecognizer(). I didn't call stopContinuousRecognitionAsync() for the whole process, so I would like to ask, what kind of problem will this solution cause? (There is still a problem, in Samsung S8 and Google Pixel2 mobile phone Android9.0 it always gives an error, the error message is: WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR code ConnectionFailure)

Very embarrassed, my English is not very good, it may not be clear

Thanks again.

**Comment by wolfma61** [comment] 2019-06-01 08:09
not sure, but closing your recognizer on button press and then creating a new recognizer for the new audio might work.

Wolfgang

**Comment by livesun** [comment] 2019-06-01 08:38
Thank you for your answer
I tried it, but it doesn't work correctly. The instance of TranslationRecognizer created multiple times can't be closed properly, keeps the link in the background.
 it may be my code problem.

I also want to ask this " WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR code ConnectionFailure" error, what is the cause?

**Comment by wolfma61** [comment] 2019-07-01 13:18
making 'stopReco' async is on the wishlist of changes (additional/new API). The work isn't scheduled currently, I don't think it will make it into the next release. Object tear-down with active listeners, containing objects that can go out of scope etc. is 'interesting', especially with all the small differences in platform and language behavior/timing.  

you should be able to create a NEW recognizer at any time, that will also pick up the microphone, without impacting ongoing recognizer sessions. 

I don't really understand how your code is currently handling this, but the more 'simple' you design it, the better. The WS_ERROR_UNDERLYING_IO_ERROR could have many reason and looks like some websocket connection is in a broken state. If you can reproduce it and can create a log-file for this scenario, that might help us in analyzing the issue

thx
Wolfgang

**Closed** 2019-09-19 15:19 UTC

**Comment by SOliasS** [comment] 2019-10-07 08:48
is stopContinuousRecognitionAsync immediately included in the new release?
