### ISSUE TITLE
Japanese pronunciation assessment show empty strings for phonemes and syllables

### ISSUE THREAD

**Issue by AlienKevin** [Azure-Samples/cognitive-services-speech-sdk#2237] opened 2024-01-24 15:20 UTC
# Issue
Japanese pronunciation assessment show empty strings for phonemes and syllables.

## In speech studio

<img width="524" alt="Screenshot 2024-01-24 at 10 08 01 AM" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/22850071/574fe76c-2e6b-46c2-bb03-b5a7828c39ea">

## Manual request through the JS SDK
<img width="684" alt="Screenshot 2024-01-24 at 10 04 07 AM" src="https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/22850071/efb771f4-b8b3-4bce-be54-c43ae0e13771">

Standard request from official doc:
```js
function pronunciationAssessmentWithMicrophone(reference) {
    return new Promise((resolve, reject) => {
        let speechConfig = SpeechSDK.SpeechConfig.fromSubscription("xxx", "eastasia");
        speechConfig.outputFormat = SpeechSDK.OutputFormat.Detailed;
        let audioConfig = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();

        const pronunciationAssessmentConfig = new SpeechSDK.PronunciationAssessmentConfig(
            reference,
            SpeechSDK.PronunciationAssessmentGradingSystem.HundredMark,
            SpeechSDK.PronunciationAssessmentGranularity.Phoneme,
            true
        );
        pronunciationAssessmentConfig.enableProsodyAssessment = true;

        let language = "ja-JP";
        speechConfig.speechRecognitionLanguage = language;

        let recognizer = new SpeechSDK.SpeechRecognizer(speechConfig, audioConfig);
        pronunciationAssessmentConfig.applyTo(recognizer);

        recognizer.recognizeOnceAsync(result => {
            console.log(`Recognized text: ${result.text}`);
            console.log(result);

            let pronunciationResult = SpeechSDK.PronunciationAssessmentResult.fromResult(result);
            console.log(pronunciationResult);
            console.log("Pronunciation assessment scores:");
            console.log(`  Accuracy score: ${pronunciationResult.accuracyScore}`);
            console.log(`  Pronunciation score: ${pronunciationResult.pronunciationScore}`);
            console.log(`  Completeness score: ${pronunciationResult.completenessScore}`);
            console.log(`  Fluency score: ${pronunciationResult.fluencyScore}`);

            recognizer.close();
            resolve(pronunciationResult.accuracyScore);
        }, error => {
            console.error(error);
            recognizer.close();
            reject(error);
        });
    });
}
```

- If relevant, a WAV file of your input audio.
https://on.soundcloud.com/KBLJx

**Expected behavior**

* Phoneme should show IPA or romaji.
* Syllable should show hiragana or romaji.

**Version of the Cognitive Services Speech SDK**

1.34.0

**Platform, Operating System, and Programming Language**

 - Programming language: JavaScript

**Comment by yulin-li** [comment] 2024-01-26 06:57
@wangkenpu could you help to take a look?

**Comment by wangkenpu** [comment] 2024-03-12 05:49
It's by design. 
FYI. https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-pronunciation-assessment?pivots=programming-language-csharp#phoneme-alphabet-format

**Comment by yulin-li** [comment] 2024-03-12 06:11
closed as won't fix

**Closed by yulin-li** 2024-03-12 06:11 UTC
Labels: in-review, pending close, pronunciation assessment
