### ISSUE TITLE
Speech-to-Text Container not working with python Speech SDK

### ISSUE THREAD

**Issue by kcvikander** [Azure-Samples/cognitive-services-speech-sdk#310] opened 2019-07-10 13:31 UTC
**Describe the bug**
When running the Cognitive Services public preview container for running speech-to-text on premises, the python SDK is unable to recognize speech.  The container runs fine and the Speech SDK appears to connect but provides no result and no additional logging in the container.  When using the same code against the public cloud, the speech SDK behaves as expected.

**To Reproduce**
1. Start speech container (Script pasted below)
2. Invoke speech sdk via python (script is copied from speech_recognize_continuous_from_file method in python examples)

**Expected behavior**
The SDK returns incremental callbacks as speech is being recognized. 

**Version of the Cognitive Services Speech SDK**
1.6.0

**Platform, Operating System, and Programming Language**
 - OS: Mac OS High Sierra 10.13.6
 - Hardware - 2.7 GHz Intel Core i7
 - Programming language: Python

**Additional context**
- script used to start speech container: 
```
docker run --rm -it -p 5000:5000  --memory 4g --cpus 4  \
containerpreview.azurecr.io/microsoft/cognitive-services-speech-to-text \
EULA=accept \
Billing=https://westus.api.cognitive.microsoft.com/sts/v1.0 \
ApiKey=**myapikey** \
Logging:Console:LogLevel:Default=Debug
```
- script used to invoke the speech sdk
```
def speech_recognize_continuous_from_file():
    """performs continuous speech recognition with input from an audio file"""
    # <SpeechContinuousRecognitionWithFile>
    initial_silence_timeout_ms = 15 * 1e3
    template = "ws://localhost:5000/speech/recognition/dictation/cognitiveservices/v1?initialSilenceTimeoutMs={:d}"
    speech_config = speechsdk.SpeechConfig(subscription=speech_key,
                                           endpoint=template.format(int(initial_silence_timeout_ms)))

    audio_config = speechsdk.audio.AudioConfig(filename='mytestfile.wav')

    speech_recognizer = speechsdk.SpeechRecognizer(
        speech_config=speech_config, audio_config=audio_config)

    done = False

    def stop_cb(evt):
        """callback that stops continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        speech_recognizer.stop_continuous_recognition()
        nonlocal done
        done = True

    # Connect callbacks to the events fired by the speech recognizer
    speech_recognizer.recognizing.connect(
        lambda evt: print('RECOGNIZING: {}'.format(evt)))
    speech_recognizer.recognized.connect(
        lambda evt: print('RECOGNIZED: {}'.format(evt)))
    speech_recognizer.session_started.connect(
        lambda evt: print('SESSION STARTED: {}'.format(evt)))
    speech_recognizer.session_stopped.connect(
        lambda evt: print('SESSION STOPPED {}'.format(evt)))
    speech_recognizer.canceled.connect(
        lambda evt: print('CANCELED {}'.format(evt)))
    # stop continuous recognition on either session stopped or canceled events
    speech_recognizer.session_stopped.connect(stop_cb)
    speech_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    speech_recognizer.start_continuous_recognition()
    while not done:
        time.sleep(.5)
    # </SpeechContinuousRecognitionWithFile>
```

- I made the requisite changes to the SpeechConfig object - passing in the endpoint of the local image and removing the region parameter.  In my testing, I tried updating the local websocket URL to use SSL, which did in fact throw some errors in the speech container.
 - Using the python example for speech_recognize_continuous_from_file specifically, when running the sample it provides the following output: ```SESSION STARTED: SessionEventArgs(session_id=b78b00274ac149a0b43ffa647ed5ddc6)``` and nothing more.  Furthermore, the container itself doesn't log any more information when this script is invoked. 
- No activity is shown in my azure portal indicating any processing has been done

**Comment by Soty89** [comment] 2019-09-03 07:59
I have exactly the same problem. Have you found a solution yet?

**Comment by yshahin** [comment] 2019-09-03 16:47
Can you try this https://hub.docker.com/r/antsu/on-prem-client to hit the container.
Use this command on your mac
```docker run --rm -it antsu/on-prem-client ./speech-to-text-client -r local --mac --expect "What's the weather like" ./audio/whatstheweatherlike.wav```
If this works then the issue is with the speech SDK on OSX

**Comment by Soty89** [comment] 2019-09-09 08:08
> Can you try this https://hub.docker.com/r/antsu/on-prem-client to hit the container.
> Use this command on your mac
> `docker run --rm -it antsu/on-prem-client ./speech-to-text-client -r local --mac --expect "What's the weather like" ./audio/whatstheweatherlike.wav`
> If this works then the issue is with the speech SDK on OSX

That works

**Comment by yshahin** [comment] 2019-09-09 17:04
Then it is not a container issue, its a problem with the SDK running on OSX

**Comment by skehoe3** [comment] 2019-09-11 12:16
I have this problem as well. I have tried updating the SDK, but no luck.  Any other ideas?

**Comment by skehoe3** [comment] 2019-09-11 12:55
Using the swagger tool, I figured out that several parts of the docker image are working incorrectly.  See below screenshots.  What endpoint are you using?  We are currently using: ws://localhost:5000/speech/recognition/dictation/cognitiveservices/v1

The errors occur in UniversalV1 for dictation, interactive, and conversation.

![Screenshot 2019-09-11 at 14 51 56](https://user-images.githubusercontent.com/12484960/64698841-e815a080-d4a3-11e9-8426-d21249e26dad.png)

**Comment by rhurey** [comment] 2019-09-18 20:10
Sorry it's taken us a while to get to the bottom of this.

There are two problems here:
1) The Speech SDK has a transport library dependency that doesn't support non-SSL connections on MacOS / iOS. It fails the connection.

We're contacting the library maintainers to understand the story behind that and see if there are plans or a different branch we can pull support from.

2) When #1 happened, the Speech SDK didn't properly handle the error and get the correct status back out. We'll fix this in a future release.

**Comment by rhurey** [comment] 2019-10-08 21:20
To follow up, a fix for both issues will be in our next SDK release.

**Closed** 2019-10-08 21:20 UTC

**Comment by paras55** [comment] 2020-09-26 19:55
>     1. The Speech SDK has a transport library dependency that doesn't support non-SSL connections

The SDK also doesn't support http connection . I have been running a flask server and getting  a http link and trying to hit api . But it doesn't respond ,
Is there a fix ?
