### ISSUE TITLE
Keep getting UnsatisfiedLinkError and not sure why

### ISSUE THREAD

**Issue by Flippeh** [Azure-Samples/cognitive-services-speech-sdk#469] opened 2019-12-23 08:43 UTC
![image](https://user-images.githubusercontent.com/35188639/71346633-ef7e2880-252d-11ea-8928-a9a61e2baa63.png)

This is a screencap of my Eclipse window. I'm pretty sure I have set everything up correctly.

Any tips for a noob?

**Comment by lisaweixu** [comment] 2019-12-23 18:43
Hello Flippeh,

I followed the [java quickstart](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-microphone?tabs=dotnet%2Cx-android%2Clinux%2Cjava-runtime&pivots=programming-language-java) and I could not reproduce the UnSatisfiedLinkeError that you saw. 

The Speech SDK implicitly loads at least two native dlls, Microsoft.CognitiveServices.Speech.core.dll and Microsoft.CognitiveServices.Speech.java.bindings.dll. My guess is that the UnsatisfiedLinkError is due to JVM can't find them, for some reason. More details, https://examples.javacodegeeks.com/java-basics/exceptions/java-lang-unsatisfiedlinkerror-how-to-handle-unsatisfied-link-error/

Here is my pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.microsoft.cognitiveservices.speech.samples</groupId>
  <artifactId>2020Xmas</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <repositories>
  <repository>
    <id>maven-cognitiveservices-speech</id>
    <name>Microsoft Cognitive Services Speech Maven Repository</name>
    <url>https://csspeechstorage.blob.core.windows.net/maven/</url>
  </repository>
</repositories>
<dependencies>
  <dependency>
    <groupId>com.microsoft.cognitiveservices.speech</groupId>
    <artifactId>client-sdk</artifactId>
    <version>1.8.0</version>
  </dependency>
</dependencies>
</project>

BTW, I could have my speech from a microphone correctly recognized.

**Comment by Flippeh** [comment] 2019-12-23 20:00
> Microsoft.CognitiveServices.Speech.java.bindings.dll

I checked my pom.xml and it is the same as yours and yet I'm still getting this error.

Could it be an issue with the key I'm using? I'm not super sure how this works.

**Comment by lisaweixu** [comment] 2019-12-23 21:33
No, It should not be your key since JVM can't find the native dll. The java code is just a wrapper. Verifying key is happening in the native code.

One workaround that I can think of is that you can put C:\Users\Kiffer\.m2\repository\com\microsoft\cognitiveservices\speech\client-sdk\1.8.0\client-sdk-1.8.0\ASSETS\windows64 
into your PATH.

**Comment by pankopon** [comment] 2020-02-20 19:33
Closing the issue because no update since December, please re-open if still valid.

**Closed by pankopon** 2020-02-20 19:33 UTC
Labels: question
