### ISSUE TITLE
Retrieving the Detailed Connection Error details from Speech SDK

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#604] opened 2020-04-24 19:26 UTC
Hello,

I am trying to connect to an endpoint which has a Speech Container hosted.

However, I am getting connection errors and generic error message. 
"Connection failed (no connection to the remote host). Internal error: 1. Error details: 2460. Please check network connection, firewall setting, and the region name used to create speech". I need the exact reason. Possible issues could be TLS handshake issue, DNS resolution issues etc.

 How do i get the detailed exception log of connection failure from the Speech SDK. I need the exact reason for the Connection failure as the container is behind a proxy with TLS to debug the issue.

How can i get the detailed connection error message from the SDK.

Regards,

**Comment by rhurey** [comment] 2020-04-24 19:54
There are instructions here on how to enable logging from the Speech SDK: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

In the log file, I'd start with looking for lines containing SPX_TRACE_ERROR. There may be some spurious errors, but there should be enough to point you in the right direction. If you post a log, someone will be happy to take a look at it to help out.

**Comment by viju2008** [comment] 2020-04-28 19:06
I am getting tls verify fail error. I have two options as it development.. How do i bypass tls verification .

I am trying in android

Second how do i provide the CA certificate required  so that if such issue occurs with self hosted containers then providing the CA cert dynamically to the SpeechConfig would be needed

**Comment by viju2008** [comment] 2020-04-28 19:07
[logfile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/4547990/logfile.txt)

**Comment by rhurey** [comment] 2020-04-28 20:34
Was the certificate issued by a CA that isn't part of the standard root certificates in the Android store?

For test devices the solution would be to install the CA from your issuer as a trusted root. For production it would be to get a certificate issued by a universally trusted CA.

**Comment by viju2008** [comment] 2020-04-29 03:41
The certificate is verifiable through browser on the same mobile so this means the certiticate is trusted in Android store else the browser also would not have verified it.

**Comment by viju2008** [comment] 2020-04-30 18:52
Also a peculiar situation that i noticed .. If i am calling my websocket proxy from a Java program JRE 1.8 on my desktop i am not getting TLS verification issues.

I am only getting it on android phone . Hence it seems the android phone is missing some certificates. However in production its not possible to add any certificate to the keystore of the client, hence some other way of passing CA certificate to SDK needs to be available.

**Comment by pankopon** [comment] 2020-06-13 00:29
Duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/614.

**Closed by pankopon** 2020-06-13 00:29 UTC
