### ISSUE TITLE
MSB3027 Could not copy Microsoft.CognitiveServices.Speech.extension.lu.dll

### ISSUE THREAD

**Issue by fatihyildizhan** [Azure-Samples/cognitive-services-speech-sdk#2257] opened 2024-02-05 09:59 UTC
**Describe the bug**
We are using CognitiveServices.Speech v1.35.0 on C# Web API project and using GitHub Actions on Ubuntu 20.04 with Dockerfile.

When we upgrade it from v1.33.0 to v1.34.1 or v1.35.0 we get build error on GitHub Actions.

**To Reproduce**
1- We are using Nuget to install the sdk
2- Dockerfile
```
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
RUN apt-get update && apt-get install -y apt-utils libgdiplus libc6-dev libssl-dev libasound2 build-essential wget
RUN wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb
RUN dpkg -i libssl1.1_1.1.1f-1ubuntu2.20_amd64.deb
RUN wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.20_amd64.deb
RUN dpkg -i libssl-dev_1.1.1f-1ubuntu2.20_amd64.deb
USER app
WORKDIR /app
EXPOSE 5000
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ConsoleApp1/ConsoleApp1.csproj", "ConsoleApp1/"]
RUN dotnet restore "./ConsoleApp1/./ConsoleApp1.csproj"
COPY . .
WORKDIR "/src/ConsoleApp1"
RUN dotnet build "./ConsoleApp1.csproj" -c $BUILD_CONFIGURATION -o /app/build
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ConsoleApp1.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ConsoleApp1.dll"] 
```

**Version of the Cognitive Services Speech SDK**

v1.35.0

**Platform, Operating System, and Programming Language**

 - OS: Ubuntu 20.04
 - Hardware: x64
 - Programming language: C# - .NET 7 / .NET 8

**Additional context**

/usr/share/dotnet/sdk/7.0.405/Microsoft.Common.CurrentVersion.targets(4879,5): error MSB3027: Could not copy "/root/.nuget/packages/microsoft.cognitiveservices.speech/1.35.0/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.lu.dll" to "/app/build/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.lu.dll". Exceeded retry count of 10. Failed. 

/usr/share/dotnet/sdk/7.0.405/Microsoft.Common.CurrentVersion.targets(4879,5): error MSB3021: Unable to copy file "/root/.nuget/packages/microsoft.cognitiveservices.speech/1.35.0/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.lu.dll" to "/app/build/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.lu.dll". Could not find a part of the path '/app/build/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.lu.dll'.

**Comment by BrianMouncer** [comment] 2024-02-05 19:21
I do not see the same errors using our public SPX docker image (and our SPX command line tool is also a C# console application).
Can you try the following docker calls, update the path to your mapped in data folder, and try running your application on this prebuilt container? e.g. I'd like to narrow the failure down to something in the docker container, or in the CS Project file...

    docker pull msftspeech/spx:latest
    docker run -it --rm --entrypoint /bin/bash -v c:\docker\data:/data msftspeech/spx:latest
    az login
    spx init
    spx synthesize --text "Hello, would you like a glass of water?" --voice "en-AU-NatashaNeural" --audio output test.wav
    spx recognize --file test.wav
    
It is also strange that your C# project is attempting to load the windows arm64 dll, rather than the linux x64 .so file.
It almost looks like you are building for the wrong target, or maybe deploying the wrong binaries?
But maybe that is just because it is a cross platform .net core app?

**Comment by dargilco** [comment] 2024-02-21 17:47
Closing since there was no response in two weeks. @fatihyildizhan please reactivate if you need more assistance. Thanks.

**Comment by fatihyildizhan** [comment] 2024-04-27 10:41
Hi @dargilco 

The issue still persists. Is it possible to re-open it? So, maybe someone mention to this issue. Thanks.

Our current version is v1.33.0 is working on Ubuntu with Docker image on .NET 7. There are several releases after this version like 34, 35, 36 and now the latest version is 1.37.0. I don't know what changed after v1.33.0.

```
69.97 /usr/share/dotnet/sdk/7.0.408/Microsoft.Common.CurrentVersion.targets(4879,5): error MSB3027: Could not copy "/root/.nuget/packages/microsoft.cognitiveservices.speech/1.37.0/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.kws.dll" to "/app/build/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.kws.dll". Exceeded retry count of 10. Failed.  [/src/MyProject.API/MyProject.API.csproj]

69.97 /usr/share/dotnet/sdk/7.0.408/Microsoft.Common.CurrentVersion.targets(4879,5): error MSB3021: Unable to copy file "/root/.nuget/packages/microsoft.cognitiveservices.speech/1.37.0/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.kws.dll" to "/app/build/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.kws.dll". Could not find a part of the path '/app/build/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.kws.dll'. [/src/MyProject.API/MyProject.API.csproj]
```

**Comment by jhakulin** [comment] 2024-05-24 18:33
@fatihyildizhan Have you tested with .NET8? .NET7 is end of support (https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)

**Comment by jhakulin** [comment] 2024-05-24 20:11
@fatihyildizhan 
when the nuget is installed, do you see there is e.g. following file under
"/root/.nuget/packages/microsoft.cognitiveservices.speech/1.37.0/runtimes/win-arm64/native/Microsoft.CognitiveServices.Speech.extension.kws.dll" ?

I would like to understand does the copy fail because file is not there or some other reason.

Probably file is there but for some reason copying fails to /app/build/runtimes/win-arm64/native in the Docker container.

**Comment by fatihyildizhan** [comment] 2024-05-24 20:52
On my local Windows 11 machine this folder name is uppercased. "win-arm64" => "win-ARM64".

Ubuntu is looking for `1.37.0/runtimes/win-arm64/native/Microsoft` Could be case-sensitive?

Win
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/602600/a3c3951f-038f-4c00-9905-562079d6357b)

net8.0\runtimes\win-ARM64\native
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/602600/319a9d20-32b4-422a-80be-12dd69d542d9)

Full
![image](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/602600/2ef1ae2c-7ab3-4a02-8ded-2be425186594)

**Comment by jhakulin** [comment] 2024-05-24 22:38
@fatihyildizhan What do you see in the Docker container side? Does the nuget get restored and is there a permissions to copy the file? With 1.33.0 Speech SDK version, do you use the exactly the same Docker configuration?

**Comment by fatihyildizhan** [comment] 2024-05-31 11:14
@jhakulin 
- There is no permission error with the same Docker configuration. We've tried with user and root permission, nothing changed.
- We are using exactly the same Docker and GitHub actions configurations for v1.33, 34 ... 1.37
- There is only a single file named Microsoft.CognitiveServices.Speech.csharp.dll in the Docker container

**Comment by pankopon** [comment] 2024-06-19 20:56
@fatihyildizhan Please try the attached test project that uses .NET 8.0 and the current latest Speech SDK 1.38.0 release (which does not require OpenSSL 1.x anymore).
[dockertest.zip](https://github.com/user-attachments/files/15905802/dockertest.zip)
Edit `helloworld\Program.cs` and replace the subscription key and service region placeholders with valid values.
Dockerfile is like your original except for added `ca-certificates` and no `libssl1.1` installation.

Example build and run on Ubuntu 18.04 host using `docker.io` (Docker community edition):
```
$ docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~18.04.3

$ docker build -t test:1 .
Sending build context to Docker daemon  73.22kB
Step 1/20 : FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
 ---> 7c519794d26d
...
Step 20/20 : ENTRYPOINT ["dotnet", "ConsoleApp1.dll"]
 ---> Running in 9a91a27f76b1
Removing intermediate container 9a91a27f76b1
 ---> 18baabe5f537
Successfully built 18baabe5f537
Successfully tagged test:1

$ docker run test:1
RECOGNIZED: Text=What's the weather like?
```
Can you run the same successfully or are there errors?

**Comment by pankopon** [comment] 2024-08-15 20:43
Closed as not reproduced and no further updates.

**Closed by pankopon** 2024-08-15 20:43 UTC
Labels: in-review, pending close
