### ISSUE TITLE
speech sdk .so library files issue with linking in rhel7.9 / centos 7.9

### ISSUE THREAD

**Issue by debdeep82** [Azure-Samples/cognitive-services-speech-sdk#1016] opened 2021-03-30 09:45 UTC
Hi Team,

We are try a java sdk based bot application using directline speech in linux (rhel 7.9). Tried following link 
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7.

We are using sdk .jar client-sdk-1.14.0.jar
Does microsoft maintain a repository for the libraries for differenet rhel7 linux version with cleint sdk versions ?

But the application hits an issue with runtime linking of the speech sdk so files. Could you please help to resolve the error ?

 Received BindRequest with no SA_MESSAGEINTEGRITY. Sending 401.
Mar 30 UTC 2021 08:47:43 AM.426295| 14975 |  OrigTrunkLeg$3                | 0| Id ERROR | S:3 Unexpected userLevel exception (task: OTL.connectionStateChange) exception occured:
                                  |       |                               | java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.dialog.BotFrameworkConfig.fromSubscription(Lcom/microsoft/cognitiveservices/speech/util/IntRef;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
                                  |       |                               |     at com.microsoft.cognitiveservices.speech.dialog.BotFrameworkConfig.fromSubscription(Native Method)
                                  |       |                               |     at com.microsoft.cognitiveservices.speech.dialog.BotFrameworkConfig.fromSubscription(BotFrameworkConfig.java:32)
                                  |       |                               |     at hpe.opencall.media.exampoclets.bot.BotService.connect(BotService.java:242)
                                  |       |                               |     at hpe.opencall.media.exampoclets.bot.BotService$2.trunkLegStateChange(BotService.java:198)
                                  |       |                               |     at hp.opencall.media.service.OrigTrunkLeg$3.runTask(OrigTrunkLeg.java:483)
                                  |       |                               |     at hp.opencall.media.platform.FWTask.startTask(FWTask.java:221)
                                  |       |                               |     at hp.opencall.media.platform.FWThread.run(FWThread.java:356)

**Comment by debdeep82** [comment] 2021-03-31 10:51
Update regarding this issue we reported.
@BrianMouncer @rhurey thank you evry much for prompt feedback for issue 1017.
export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt helped to make the cpp linux based example working with connectivity correctly established.

Please help us with one more quesry we have raised (#1016) when we are trying to deploy the java aplication in rhel 7.9. Today we user the .so files from SpeechSDK-Linux-1.16.0.tar.gz (retrieved from wget -O SpeechSDK-Linux.tar.gz https://aka.ms/csspeech/linuxbinary ) and deployed .so files

-rwxrwxrwx. 1 root root 6443784 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.core.so
-rwxrwxrwx. 1 root root 84960 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.extension.codec.so
-rwxrwxrwx. 1 root root 130360 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.extension.audio.sys.so
-rwxrwxrwx. 1 root root 468248 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.extension.kws.so
[root@hybay5vm1 so]#

And jar fieles we used in our application classpath are

-rwxrwxrwx. 1 root root 106901 Mar 29 14:52 bot-schema-4.6.0-preview3.jar
-rwxrwxrwx. 1 root root 503880 Mar 29 14:53 commons-lang3-3.9.jar
-rwxrwxrwx. 1 root root 66519 Mar 29 14:53 jackson-annotations-2.9.0.jar
-rwxrwxrwx. 1 root root 348635 Mar 29 14:53 jackson-core-2.10.0.jar
-rwxrwxrwx. 1 root root 1400944 Mar 29 14:54 jackson-databind-2.10.0.jar
-rwxrwxrwx. 1 root root 70820 Mar 29 14:54 jackson-datatype-joda-2.9.8.jar
-rwxrwxrwx. 1 root root 100674 Mar 29 14:54 jackson-datatype-jsr310-2.9.9.jar
-rwxrwxrwx. 1 root root 589289 Mar 29 14:54 joda-time-2.7.jar
-rwxrwxrwx. 1 root root 10547027 Mar 31 08:58 client-sdk-1.16.0.jar

But when the application is invoked we are hitting following exception :

Mar 31 UTC 2021 09:53:21 AM.937347| 7201 | OrigTrunkLeg$3 | 0| Id ERROR | S:3 Unexpected userLevel exception (task: OTL.connectionStateChange) exception occured:
| | | java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
| | | at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
| | | at com.microsoft.cognitiveservices.speech.SpeechConfig.(SpeechConfig.java:74)
| | | at hpe.opencall.media.exampoclets.bot.BotService.connect(BotService.java:243)
| | | at hpe.opencall.media.exampoclets.bot.BotService$2.trunkLegStateChange(BotService.java:199)
| | | at hp.opencall.media.service.OrigTrunkLeg$3.runTask(OrigTrunkLeg.java:483)
| | | at hp.opencall.media.platform.FWTask.startTask(FWTask.java:221)
| | | at hp.opencall.media.platform.FWThread.run(FWThread.java:356)

Could you please suggest us what we may be doing wrong and do you have any README with using java clent-sdk in linux to make such a application working where java will be doing jni calls towards spech sdk .so libraries.

**Comment by rhurey** [comment] 2021-03-31 14:45
The client sdk jar file contains all the binaries needed, you shouldn't need to download them separately from the tar file.

The correct binaries are unpacked and loaded at runtime. The should be unpacked into <temp dir>/speech-sdk-native-<something>

Is this environment variable set?
```
# Add updated C/C++ runtimes to the library path
# (this is required for any development/testing with Speech SDK)
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
```
From: [How to configure REHL/Centos](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7)

**Comment by glecaros** [comment] 2021-04-27 00:17
Can you try just adding 
```java
try {
  System.loadLibrary("Microsoft.CognitiveServices.Speech.java.bindings");
} catch (Exception e) {
}
```

**Comment by pankopon** [comment] 2021-05-12 00:12
Closed since a workaround has been provided. We have an internal work item to improve the case and will update this issue when the release schedule of a possible fix is confirmed.

**Comment by lqkun** [comment] 2021-08-09 04:46
你好 我在lunix上使用语音sdk也遇见了同样的问题 请问是如何解决的？ 谢谢

java.lang.UnsatisfiedLinkError: 'void com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(java.lang.String)'
	at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method) ~[client-sdk-1.18.0.jar!/:?]
	at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:77) ~[client-sdk-1.18.0.jar!/:?]

**Comment by githluo** [comment] 2021-08-14 09:25
你好，在CentOS Linux release 7.8.2003 (Core)遇到了同样的问题，client-sdk.1.18.0

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1053)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
        at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:77)
        at com.central.xbaas.utils.Test.test(Test.java:14)
        at com.central.xbaas.controller.MicrosoftController.a(MicrosoftController.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        ... 55 common frames omitted

**Comment by yulin-li** [comment] 2021-08-14 15:23
Hi @lqkun and @githluo. could you try to follow [Configure RHEL/CentOS 7 for Speech SDK](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7) to install a newer C++ runtime and set the environment variables?

**Comment by lqkun** [comment] 2021-08-16 01:44
> Hi @lqkun and @githluo. could you try to follow [Configure RHEL/CentOS 7 for Speech SDK](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7) to install a newer C++ runtime and set the environment variables?

现在初始化可以了 但是会报连不到主机异常，是什么原因引起的呢？

CANCELED: Reason=Error:Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2543. SessionId: 0bdecca7b50f4b3683579aa78db2118d

**Comment by githluo** [comment] 2021-08-16 08:35
你好！GCC 版本已升级到8.1.0，并支撑CXXABI_1.3.9和GLIBCXX_3.4.21，sdk合成无异常，但合成后的问题大小为0，请帮忙看下！谢谢！
![image](https://user-images.githubusercontent.com/54386017/129535125-1ab3f4f6-57cb-4421-b746-a5acb12432f0.png)
![image](https://user-images.githubusercontent.com/54386017/129535357-38b3f0de-ecbf-4cc4-9356-614a575a37a0.png)

**Comment by yulin-li** [comment] 2021-08-16 08:40
@lqkun and @githluo , firstly, it will nice if you use English to discuss issues here. You will get better and quicker support as most of  colleagues here are not speaking Chinese.

Secondly, was the `SSL_CERT_FILE` environment environment variable correctly set? If the issue still happen after setting certs, could you [enable SDK logging](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging) and paste the log here?

**Comment by githluo** [comment] 2021-08-16 09:34
The setting of SSL_CERT_FILE environment variable has been checked. After synthesis, the file size is still 0KB. Please help to check, thank you!

[mtts.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6991234/mtts.log)

**Comment by pankopon** [comment] 2021-08-17 22:06
I tested the current [voice assistant quickstart](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/jre/virtual-assistant) that uses BotFrameworkConfig with Speech SDK 1.18.0 and the following setup, with no errors.

CentOS 7, with all the latest updates and configured like in https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7.
- After configuration, do ensure that these environment variables are set at all times:
  ```
  export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
  export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
  ```

Download `eclipse-SDK-4.8-linux-gtk-x86_64.tar.gz` from https://archive.eclipse.org/eclipse/downloads/drops4/R-4.8-201806110500/, unpack and launch:

```
tar zxvf <path-to-package>/eclipse-SDK-4.8-linux-gtk-x86_64.tar.gz
cd eclipse
./eclipse &
```

In Eclipse,

1. Go to menu Help, Install New Software
2. For "Work with", input http://download.eclipse.org/technology/m2e/releases/ and press Enter
3. Unselect "Show only the latest versions of available software"
4. From the list, select Maven Integration for Eclipse, *m2e - Maven Integration for Eclipse (includes Incubating components) 1.10.0.20181127-2120*
5. Wait until "Installing Software" is finished, trust the Eclipse.org Foundation certificate, restart Eclipse as prompted
6. Go to menu File, Import, select import wizard Maven - Existing Maven Projects
7. Browse to the SDK samples folder `quickstart\java\jre\virtual-assistant` where pom.xml is located
8. Wait until "Importing Maven projects" is finished
9. Edit Main.java to use a valid dialog subscription key and region
10. Run the app.

**Comment by pankopon** [comment] 2021-08-17 22:09
Closing this since the linking issue is not reproducible with the described setup. @lqkun and @githluo please create a new issue on problems with other areas like connection.

**Closed by pankopon** 2021-08-17 22:09 UTC
Labels: bug, accepted

**Comment by lqkun** [comment] 2021-08-18 04:21
> 我测试了当前使用 BotFrameworkConfig 和 Speech SDK 1.18.0 和以下设置的[语音助手快速入门](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/java/jre/virtual-assistant)，没有错误。
> 
> CentOS 7，具有所有最新的更新和配置，如https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7。
> 
> * 配置后，请确保始终设置这些环境变量：
>   ```
>   export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt
>   export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
>   ```
> 
> `eclipse-SDK-4.8-linux-gtk-x86_64.tar.gz`从https://archive.eclipse.org/eclipse/downloads/drops4/R-4.8-201806110500/下载，解压并启动：
> 
> ```
> tar zxvf <path-to-package>/eclipse-SDK-4.8-linux-gtk-x86_64.tar.gz
> cd eclipse
> ./eclipse &
> ```
> 
> 在日食中，
> 
> 1. 转到菜单帮助，安装新软件
> 2. 对于“Work with”，输入http://download.eclipse.org/technology/m2e/releases/并按 Enter
> 3. 取消选择“仅显示可用软件的最新版本”
> 4. 从列表中选择 Maven Integration for Eclipse，_m2e - Maven Integration for Eclipse（包括 Incubating 组件）1.10.0.20181127-2120_
> 5. 等待“安装软件”完成，信任Eclipse.org Foundation证书，根据提示重启Eclipse
> 6. 转到菜单文件，导入，选择导入向导 Maven - Existing Maven Projects
> 7. 浏览到`quickstart\java\jre\virtual-assistant`pom.xml 所在的 SDK 示例文件夹
> 8. 等待“导入Maven项目”完成
> 9. 编辑 Main.java 以使用有效的对话订阅密钥和区域
> 10. 运行应用程序。

Our idea can also be used normally, but it will cause problems when deployed to the lunix server The sdk log is as follows, please help look at the problem
[LogfilePathAndName.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7004469/LogfilePathAndName.txt)

**Comment by Moang** [comment] 2022-09-20 03:17
I also had the same problem. Local development is ok, but it will cause problems when deployed to the centos7 server.
