### ISSUE TITLE
upload to Google play error, Other developers are using the following content provider authorization: com. Microsoft. cognitiveseervices. speed. util InternalContentProvider

### ISSUE THREAD

**Issue by opop4m** [Azure-Samples/cognitive-services-speech-sdk#2442] opened 2024-06-25 12:35 UTC
upload to Google play error：
![20240624-172415](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/92720868/477b82d2-7bfb-4257-bf3e-51a09e1b15d4)

Please remove the conflicting items from the list first before uploading. Other developers are using the following content provider authorization: com.microsoft.cognitiveservices.speech.util.InternalContentProvider

![Snipaste_2024-06-25_20-31-47](https://github.com/Azure-Samples/cognitive-services-speech-sdk/assets/92720868/4541b9c7-8cf2-4a5c-b49b-c1764ff84a3e)

sdk version: 
implementation("com.microsoft.cognitiveservices.speech:client-sdk:1.38.0")

**Comment by pankopon** [comment] 2024-06-25 20:37
Duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2407

**Closed by pankopon** 2024-06-25 20:37 UTC
Labels: duplicate
