### ISSUE TITLE
C# BatchClient - Transcription in "NotStarted" status for several hours?

### ISSUE THREAD

**Issue by kleindev** [Azure-Samples/cognitive-services-speech-sdk#892] opened 2020-12-07 18:40 UTC
This does not seem normal, we have ~47 transcriptions that appear to be 'stuck' in "NotStarted" status.   We are using the C# batch client and using the web hook call backs.

We do see some transcriptions still completing - I am wondering why the nearly 50 jobs from around 7:50 am - 8 am CST are still "NotStarted".  I have attempted (unsuccessfully) to resubmit the same audio.

Is anyone else seeing this?  Given that it does not appear as simple as just resubmitting (*although, I only tried 1*) - is anyone aware of options to get move out of NotStarted ?

**Comment by pankopon** [comment] 2020-12-07 19:01
@chlandsi @bexxx Could this be duplicate of #891?

**Comment by zhouwangzw** [comment] 2020-12-07 20:21
Could you please let us know the region you are using, and if possible the transcription request ids?

**Comment by kleindev** [comment] 2020-12-07 20:31
Will do:

South Central US

And here are a few of the request ids:

- de811e2f-5fe7-4ac4-a98f-42fc1428fac5
- c6be40c0-ea50-43b3-ba04-f95bf72409f0
- dbefeba4-b574-42d9-8582-650f29bca173

If needed, I have more

**Comment by zhouwangzw** [comment] 2020-12-07 20:57
Thanks. One more question: are you requesting Diarization in your request?

**Comment by kleindev** [comment] 2020-12-07 21:06
Yes I am
 
*side note - I'm only requesting Diarization because without it, custom pronunciations have a string of characters appended to the end of it*

**Comment by rarera** [comment] 2020-12-08 11:10
Hello, I had observed transient errors in an underlying service we use in South Central US. It looks like your transcriptions where in a close time range, can you please resubmit them?

**Comment by rarera** [comment] 2020-12-08 15:18
Can you please provide an example for this: side note - Diarization because without it, custom pronunciations have a string of characters appended to the end of it ? What do you see in your results?

**Comment by kleindev** [comment] 2020-12-08 16:44
I did re-submit and they completed.  I will be sending several in close range (we run a process every 15 minutes to gather and send available audio).  Are they any other options to "re-start" a "NotStarted" job?  Or how long should we wait until the NotStarted state should be abandoned?

Here is some info on Diarization.  It looks like when it "works" it flags the audio as a different speaker - so thats my assumption on why it "works" when it is enabled.  Here is when it works:

![image](https://user-images.githubusercontent.com/9289866/101513559-ee622900-3941-11eb-89bb-063d306acc69.png)
  

When Diarization is not enabled, we get output like this:

supraspinatusdefaaeaddccaaaedbcdb

Others:

tenodesisaeedadbabacbfadccfbabefab
subacromialbaeaddafaeeecbfacafcebdfaab
swivelockcabfcfaaabaaddecdeaada
arthrexeccafdbddfcbabefafeedad

Sample pronunciation entries:

tenosynovitis	teano synovitis
supraspinatus	super spinedace

**Comment by rarera** [comment] 2020-12-08 17:33
Happy that it worked. 

Thank you for providing details about the problem.
This is very helpful. I will discuss this in the team based on your answer. 

Sending the jobs in close range is not a problem in general. The old jobs that are stuck will be timed out and set to failed by our service.

**Comment by pankopon** [comment] 2021-02-17 01:36
@rarera Have there been any changes made or planned? (ref. "This could help us fix a bug in the pipeline that is used when Diarization is not enabled.") Please update.

**Comment by rarera** [comment] 2021-02-18 09:06
Hi kleindev, so this is still the case. I will contact the team on this. Do you have a current example (without diarization)? Maybe together with the transcription id.

**Comment by rarera** [comment] 2021-02-18 10:25
Hi again, I communicated with the team, they are aware of the problem when custom pronunciation is used. A fix is planned but unfortunately I cannot give you a time estimation right now when the fix will go in.

**Comment by pankopon** [comment] 2021-02-18 19:37
Closing this issue since the problem has been identified and there's a fix coming. @rarera Please update here when the work is done and the release schedule is known.

**Closed by pankopon** 2021-02-18 19:37 UTC
Labels: batch, bug, pending close
