### ISSUE TITLE
Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll

### ISSUE THREAD

**Issue by amiddles** [Azure-Samples/cognitive-services-speech-sdk#2002] opened 2023-07-06 14:39 UTC
**Describe the bug**
I have a console app on my local dev machine where I can execute the code to generate audio from azure.  Locally it works fine. But, when I put that same code on a VM in Azure I get an error saying it can't locate or load it's libraries.  I've simplified it down to a console app to prove that it's not IIS or something else.  Clearly something is missing.

**Error message:**

> Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
> System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at Microsoft.CognitiveServices.Speech.Internal.SpeechConfig.speech_config_from_subscription(IntPtr& config, String subscriptionKey, String region)
>    at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
>    at audioTest.Module1.Main()

**To Reproduce**
1. Create a command line console app and add the following to the main method:
2. Install the Imports Microsoft.CognitiveServices.Speech nuget package.
3. modify the modul11.vb file to the following:
```
Imports Microsoft.CognitiveServices.Speech
Module Module1

  Sub Main()
    Dim myText = $"this is a test for {Date.Now.ToLongDateString} and {Date.Now.ToShortTimeString}"

    Net.ServicePointManager.SecurityProtocol = Net.SecurityProtocolType.Tls12
    Try
      Dim config = SpeechConfig.FromSubscription("{key}", "eastus")
      config.SpeechSynthesisVoiceName = "en-CA-ClaraNeural"
      config.SpeechSynthesisLanguage = "en-CA"
      Dim synth = New SpeechSynthesizer(config, Nothing)
      Dim Result = synth.SpeakTextAsync(myText)
      Result.Wait()
      Dim B = Result.Result.AudioData
      If B.Length = 0 Then
        Console.WriteLine("NO DATA")
        Throw New Exception("Missing audio data: " & myText)
      Else
        Console.WriteLine("Data sucessfully returned.")
      End If
    Catch ex As Exception
      Console.WriteLine("Error")
      Console.WriteLine(ex.Message)
    End Try

    Console.WriteLine()
    Console.WriteLine("Done")
    Console.ReadLine()
  End Sub

End Module
```

**Expected behavior**
Normally it should return data from the speech service and indicate that it was successful.  
It's then saved to a file for use.

**Version of the Cognitive Services Speech SDK**
1.30.0

**Platform, Operating System, and Programming Language**
 - OS: Windows
 - Hardware - x64
 - Programming language: VB.net

**Additional context**
The code in this case only fails on an Azure VM, it _does_ work outside of azure in a dev environment run from visual studio.
I suspect there is some kind of missing component but so far I can't isolate it to anything specific.
I did ensure that I have the latest C++ redistributable loaded as well.

**Comment by pankopon** [comment] 2023-07-12 00:23
@amiddles How do you deploy your app to the VM? It is not certain if it's `Microsoft.CognitiveServices.Speech.core.dll` itself or some of its dependencies that cannot be found or loaded.

The first thing to check is whether the dependencies can be located. For `Microsoft.CognitiveServices.Speech.core.dll` they can be listed with `dumpbin` (in Developer Command Prompt for VS 2022) like:
```
> where dumpbin
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\Hostx86\x86\dumpbin.exe

> dumpbin /dependents Microsoft.CognitiveServices.Speech.core.dll
Microsoft (R) COFF/PE Dumper Version 14.36.32535.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file Microsoft.CognitiveServices.Speech.core.dll

File Type: DLL

  Image has the following dependencies:

    ADVAPI32.dll
    CRYPT32.dll
    WS2_32.dll
    Secur32.dll
    ncrypt.dll
    dbghelp.dll
    KERNEL32.dll
    MSVCP140.dll
    MSVCP140_CODECVT_IDS.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    RPCRT4.dll
    api-ms-win-crt-environment-l1-1-0.dll
    ole32.dll
```
To check whether they actually exist on the system, create a cmd batch file e.g. `findDeps.cmd` with the following content
```
@echo off

set myList=ADVAPI32.dll,CRYPT32.dll,WS2_32.dll,Secur32.dll,ncrypt.dll,dbghelp.dll,KERNEL32.dll,MSVCP140.dll,MSVCP140_CODECVT_IDS.dll,VCRUNTIME140_1.dll,VCRUNTIME140.dll,api-ms-win-crt-runtime-l1-1-0.dll,api-ms-win-crt-heap-l1-1-0.dll,api-ms-win-crt-string-l1-1-0.dll,api-ms-win-crt-stdio-l1-1-0.dll,api-ms-win-crt-convert-l1-1-0.dll,api-ms-win-crt-time-l1-1-0.dll,api-ms-win-crt-utility-l1-1-0.dll,api-ms-win-crt-math-l1-1-0.dll,api-ms-win-crt-locale-l1-1-0.dll,api-ms-win-crt-filesystem-l1-1-0.dll,RPCRT4.dll,api-ms-win-crt-environment-l1-1-0.dll,ole32.dll

for %%i in (%myList%) do (
  where %%i 2>nul || echo WARNING: %%i not found
)

pause
```
then run the batch file. Example output:
```
C:\Windows\System32\advapi32.dll
C:\Windows\System32\crypt32.dll
C:\Windows\System32\ws2_32.dll
...
C:\Windows\System32\ole32.dll
Press any key to continue . . .
```
Check for any `WARNING: xyz.dll not found` messages in the output.

If the dependencies (and supposedly their dependencies as well) do exist on the VM then it may be a case of old versions or a problem with the project configuration.

We don't test with VB, but if you build the C# sample https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/csharp/dotnetcore/console the files in the output directory (`samples\bin\Release\netcoreapp3.1` for a Release build) are as follows (excluding input data and runtimes other than win-x64)
```
./Azure.Core.dll
./Microsoft.Bcl.AsyncInterfaces.dll
./Microsoft.CognitiveServices.Speech.csharp.dll
./Microsoft.CognitiveServices.Speech.Remoteconversation.dll
./runtimes/win-x64/native/Microsoft.CognitiveServices.Speech.core.dll
./runtimes/win-x64/native/Microsoft.CognitiveServices.Speech.extension.audio.sys.dll
./runtimes/win-x64/native/Microsoft.CognitiveServices.Speech.extension.codec.dll
./runtimes/win-x64/native/Microsoft.CognitiveServices.Speech.extension.kws.dll
./runtimes/win-x64/native/Microsoft.CognitiveServices.Speech.extension.kws.ort.dll
./runtimes/win-x64/native/Microsoft.CognitiveServices.Speech.extension.lu.dll
./runtimes/win-x64/native/Microsoft.CognitiveServices.Speech.extension.mas.dll
./samples.deps.json
./samples.dll
./samples.exe
./samples.runtimeconfig.json
./System.Text.Json.dll
```
If you copy this structure elsewhere and run `samples.exe` or, in plain Command Prompt (not VS specific), `dotnet samples.dll`, it works as long as dependencies are met.

Can you try the C# sample with e.g. https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/407e9a1139a491898f7a4cab7597f58e9383a610/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L193 (for samples menu 1. Speech recognition samples - 3. Speech continuous recognition with file input, uses `whatstheweatherlike.wav` by default) and test locally, then on VM? This is to ensure that the issue is not VB project specific.

**Comment by amiddles** [comment] 2023-07-13 03:00
@pankopon When I ran that tool all the DLLs are on my local machine for on an azure VM some are missing.  I created a new VM just to be sure that was not the issue and it was also missing the same ones. 
```

C:\Windows\System32\advapi32.dll
C:\Windows\System32\crypt32.dll
C:\Windows\System32\ws2_32.dll
C:\Windows\System32\secur32.dll
C:\Windows\System32\ncrypt.dll
C:\Windows\System32\dbghelp.dll
C:\Windows\System32\kernel32.dll
WARNING: MSVCP140.dll not found
WARNING: MSVCP140_CODECVT_IDS.dll not found
WARNING: VCRUNTIME140_1.dll not found
WARNING: VCRUNTIME140.dll not found
WARNING: api-ms-win-crt-runtime-l1-1-0.dll not found
WARNING: api-ms-win-crt-heap-l1-1-0.dll not found
WARNING: api-ms-win-crt-string-l1-1-0.dll not found
WARNING: api-ms-win-crt-stdio-l1-1-0.dll not found
WARNING: api-ms-win-crt-convert-l1-1-0.dll not found
WARNING: api-ms-win-crt-time-l1-1-0.dll not found
WARNING: api-ms-win-crt-utility-l1-1-0.dll not found
WARNING: api-ms-win-crt-math-l1-1-0.dll not found
WARNING: api-ms-win-crt-locale-l1-1-0.dll not found
WARNING: api-ms-win-crt-filesystem-l1-1-0.dll not found
C:\Windows\System32\rpcrt4.dll
WARNING: api-ms-win-crt-environment-l1-1-0.dll not found
C:\Windows\System32\ole32.dll
Press any key to continue . . .
```

**Comment by pankopon** [comment] 2023-07-13 20:27
@amiddles This output is from the VM? These four files in particular are Visual Studio C++ redist libraries that are mandatory for Speech SDK:
```
WARNING: MSVCP140.dll not found
WARNING: MSVCP140_CODECVT_IDS.dll not found
WARNING: VCRUNTIME140_1.dll not found
WARNING: VCRUNTIME140.dll not found
```
Did you install the C++ redist on the VM? It seems the files are not there. It could be that installation of system libraries is restricted or not allowed in the VM environment, but there should be some message about it when trying to install them.
One potential workaround would be to copy the files from your local machine and put them to the same directory on VM where Speech SDK dlls are, but redist dlls may have dependencies of their own that you'd also need to check for and copy.

**Comment by amiddles** [comment] 2023-07-13 23:47
@pankopon I've installed all three on the VM that are the latest versions.  Remember I  tested this on a completely fresh install of Server 2022 and it doesn't find those file either.  If you spin up an Azure VM for windows server 2022 and run your same test for the dlls does it come up for you?  Can you reproduce my scenario?

**Comment by pankopon** [comment] 2023-07-14 01:07
@amiddles So the system files on VM cannot be added or updated -> please copy them from your local system and try. Put them in the same folder where your app is launched from. Based on `dumpbin` there should be no additional important dependencies:
```
> dumpbin /dependents C:\Windows\System32\msvcp140.dll
  ...
  Image has the following dependencies:

    VCRUNTIME140.dll
    VCRUNTIME140_1.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    KERNEL32.dll

> dumpbin /dependents C:\Windows\System32\msvcp140_1.dll
  ...
  Image has the following dependencies:

    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    KERNEL32.dll

> dumpbin /dependents C:\Windows\System32\vcruntime140_1.dll
  ...
  Image has the following dependencies:

    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    VCRUNTIME140.dll
    KERNEL32.dll

> dumpbin /dependents C:\Windows\System32\vcruntime140.dll
  ...
  Image has the following dependencies:

    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    KERNEL32.dll
```

**Comment by pankopon** [comment] 2023-07-14 23:13
Just to add, I now created an Azure VM of "Windows Server 2022 Datacenter Azure Edition - x64 Gen2".

Connected to the VM over RDP (using the administrator account), created `findDeps.cmd`, ran it in (Administrator) Command Prompt:
```
> findDeps.cmd
C:\Windows\System32\advapi32.dll
C:\Windows\System32\crypt32.dll
C:\Windows\System32\ws2_32.dll
C:\Windows\System32\secur32.dll
C:\Windows\System32\ncrypt.dll
C:\Windows\System32\dbghelp.dll
C:\Windows\System32\kernel32.dll
WARNING: MSVCP140.dll not found
WARNING: MSVCP140_CODECVT_IDS.dll not found
WARNING: VCRUNTIME140_1.dll not found
WARNING: VCRUNTIME140.dll not found
...
```

Then downloaded `VC_redist.x64.exe` from https://learn.microsoft.com/cpp/windows/latest-supported-vc-redist and ran it to install.

Then re-ran `findDeps.cmd` in the same command prompt as previously:
```
> findDeps.cmd
C:\Windows\System32\advapi32.dll
C:\Windows\System32\crypt32.dll
C:\Windows\System32\ws2_32.dll
C:\Windows\System32\secur32.dll
C:\Windows\System32\ncrypt.dll
C:\Windows\System32\dbghelp.dll
C:\Windows\System32\kernel32.dll
C:\Windows\System32\msvcp140.dll
C:\Windows\System32\msvcp140_codecvt_ids.dll
C:\Windows\System32\vcruntime140_1.dll
C:\Windows\System32\vcruntime140.dll
...
```
Also disconnected from and re-connected to the VM, and the redist files continue to exist.

**Comment by amiddles** [comment] 2023-07-15 02:50
@pankopon  The output you posted above is missing the files needed for the speech sdk to work.  When I run it you will notice the files I'm missing are not in your list.  Specifically the "**api-ms-win-crt**" group of dlls.  See below.
```
C:\Windows\System32\advapi32.dll
C:\Windows\System32\crypt32.dll
C:\Windows\System32\ws2_32.dll
C:\Windows\System32\secur32.dll
C:\Windows\System32\ncrypt.dll
C:\Windows\System32\dbghelp.dll
C:\Windows\System32\kernel32.dll
C:\Windows\System32\msvcp140.dll
C:\Windows\System32\msvcp140_codecvt_ids.dll
C:\Windows\System32\vcruntime140_1.dll
C:\Windows\System32\vcruntime140.dll
WARNING: api-ms-win-crt-runtime-l1-1-0.dll not found
WARNING: api-ms-win-crt-heap-l1-1-0.dll not found
WARNING: api-ms-win-crt-string-l1-1-0.dll not found
WARNING: api-ms-win-crt-stdio-l1-1-0.dll not found
WARNING: api-ms-win-crt-convert-l1-1-0.dll not found
WARNING: api-ms-win-crt-time-l1-1-0.dll not found
WARNING: api-ms-win-crt-utility-l1-1-0.dll not found
WARNING: api-ms-win-crt-math-l1-1-0.dll not found
WARNING: api-ms-win-crt-locale-l1-1-0.dll not found
WARNING: api-ms-win-crt-filesystem-l1-1-0.dll not found
C:\Windows\System32\rpcrt4.dll
WARNING: api-ms-win-crt-environment-l1-1-0.dll not found
C:\Windows\System32\ole32.dll
Press any key to continue . . .
```

**Comment by pankopon** [comment] 2023-07-17 06:27
If the dependency dlls cannot be installed on your VM then they need to be included with your app (e.g. copied from your local machine) in the same way as Speech SDK dlls. Sorry, but there is no other way. (for reference, if needed: [Windows DLL search order](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order))

**Comment by pankopon** [comment] 2023-07-17 06:27
Closed as answered. Please open a new issue if more support is needed.

**Closed by pankopon** 2023-07-17 06:27 UTC
Labels: in-review, .NET
