### ISSUE TITLE
Abbreviations improperly changed to City/States

### ISSUE THREAD

**Issue by nstubing** [Azure-Samples/cognitive-services-speech-sdk#515] opened 2020-02-21 22:14 UTC
**Describe the bug**
When processing audio with only a Language Model, If I spoke "LV" or "MD" the abbreviation would be recognized and returned as "LV" and "MD" respectfully.  After creating a speech model with training data containing the LV and MD in the dictations, creating a model with the dataset, and sending the same audio back through with the same Language Model and new Speech Model; The same dictations return "Las Vegas" where I say "LV" and "Maryland" where I say "MD".  I am sure there are more instances of this, but these are the two that I have run in to so far.

I **did not** put "Las Vegas" or "Maryland" anywhere in the training data.  The Language model stays the same, but the speech model is updated. 

**To Reproduce**
1.  Dictate items that contain "LV" or "MD".
2.  Create an audio dataset with dictations containing LV and MD.
3.  Create speech model with that dataset.
4.  Send the same audio through for transcription and where you dictate "LV" it returns "Las Vegas" and where you dictate "MD" it returns "Maryland".

**Expected behavior**
If I dictate "LV" return "LV"
if I dictate "MD" return "MD"

**Platform, Operating System, and Programming Language**
 - OS:Windows
 - Hardware: x64
 - Programming language: C#
 - Browser: Chrome

**Additional context**
-The datasets and models were created using the API so I am forced to use the 20190523 (v4.14b Unified) base model for the models.

**Comment by nstubing** [comment] 2020-02-27 19:29
Actually, looking back on it, the base model of the Language model did change.  The original Language model had the 20191007 base model, and the newly trained Language model was using the 20190523 model.  The newer base models clearly perform better after running some tests,  when are we going to be able to use the newer base models with the api?

**Comment by pankopon** [comment] 2020-06-15 17:21
@nstubing Sorry about the lack of response - is this issue still valid for you or have you been able to use newer base models by now?

**Comment by oscholz** [comment] 2020-06-16 05:05
@nstubing you should be able to use the latest models now. The latest model is 20191202. The easiest way to train a custom model based on the new model is through the Custom Speech feature of Speech Studio at speech.microsoft.com. 
Please let us know what you find when you use the latest model as your baseline model.
I will close this issue for now. If you still have issues on the latest model, please reopen the issue, and we will file a bug in our backlog to dig deeper.

**Comment by nstubing** [comment] 2020-06-18 18:46
I still am unable to use any newer (newer than 20190523) Base Models while creating Speech Models with the API.  @oscholz  I am also unable to re-open this issue since it was closed by a mod.   I know that the portal is "easier" if you are making datasets/models on a small scale by hand, but I have all dataset creation/deployment and model creation/deployment automated through the api since I needed to build a system to allow hundreds of physicians to complete medical documentation and keep human intervention to a minimum. 

I start them on a base model that was created in the portal  with my custom Base Language Model and your Standard AcousticAndLanguage Model (20191007).   Once the Physician dictates and reviews a certain number of recognitions, we automatically make them custom language/acoustic datasets -> language/acoustic models ->endpoint.  The API does allow you to create a Language Model with the 20191202 Base Model, but it does not allow you to create an Acoustic Model with anything more recent than 20190523.  

It is really disappointing that if I want to train an Acoustic model through the API I am forced to downgrade the base model to an inferior one.  

It is really redundant to create separate language and speech datasets, and subsequent language and acoustic models.  When will the V3 api be out of beta?

**Comment by pankopon** [comment] 2020-06-19 00:00
@fmegen Can you please comment on the availability of newer Base Models when Speech Models are created with the API?

**Comment by pankopon** [comment] 2020-06-23 20:59
@fmegen @wolfma61 Please comment on the availability of newer base models in this use case, otherwise we'll presume it's not supported.

**Comment by pankopon** [comment] 2020-06-30 17:26
@fmegen @wolfma61 One more ping, please comment this week or the item will be closed.

**Comment by adebaynast** [comment] 2020-07-04 11:45
Sorry for the late answer, the issue is occurring during the normalization of the input text before the actual adaptation. LV or MD are indeed ambiguous in term of pronunciation: they could be indeed simply "L V" or "Las Vegas". We recommend when adapting the model with audio files to use "L V" and "M D" instead. This will suppress the ambiguity of the pronunciation.

**Comment by pankopon** [comment] 2020-07-06 20:38
Closed since there is no more information available. If you have further questions about a specific topic, please open a new issue with details.

**Closed by pankopon** 2020-07-06 20:38 UTC
Labels: custom speech, question
