### ISSUE TITLE
Exception with an error code: 0x5 (SPXERR_INVALID_ARG)  or 0x21 (SPXERR_INVALID_HANDLE) when trying to Enroll a VoiceProfile for Speaker Identification

### ISSUE THREAD

**Issue by QuackersCoder** [Azure-Samples/cognitive-services-speech-sdk#743] opened 2020-07-23 00:36 UTC
Hi I'm getting the following errors when trying to Enroll a voice profile for speaker identification and the error changes between versions 1.12.1. and 1.13.0

The profile has been checked and is an Identification profile , and exists.

The error occurs when i call
result = await client.EnrollProfileAsync(profile, audioConfig);

I am trying to create the profile, then enroll later...
When i create a voiceprofile to pass into the enrollment like this

var profile = new VoiceProfile(profileId)

..rather than creating one with the client seems to be triggering the error. , Does the Enrollment need the profile creating just before? I cannot see a client method for retrieving a created voiceprofile.

**Expected behaviour**
Enrollment occurs or a more meaningful error message is displayed

**Environment**
Using the windows version of SDK 
OS: windows 10 Version	10.0.18363 Build 18363
Programming language:  C# in  a project  targeting netstandard2.0
Tried enrolling using microphone and wav files and get the same errors.
App: Winforms

Version: Microsoft.CognitiveServices.Speech SDK 1.12.1

Error
Exception with an error code: 0x5 (SPXERR_INVALID_ARG)
Source
Microsoft.CognitiveServices.Speech.csharp

Stack trace
at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
at Microsoft.CognitiveServices.Speech.Internal.SpxFactory.GetDataFromHandleUsingDelegate(GetResultDelegate functionPtr, InteropSafeHandle handle, Int32 maxCharCount)
at Microsoft.CognitiveServices.Speech.VoiceProfileEnrollmentResult..ctor(IntPtr resultHandlePtr)
at Microsoft.CognitiveServices.Speech.VoiceProfileClient.<>c__DisplayClass6_0.b__0(InteropSafeHandle h)
at Microsoft.CognitiveServices.Speech.VoiceProfileClient.<>c__DisplayClass10_01.<RunAsync>b__0() at System.Threading.Tasks.Task1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Ossa.VoiceIdentification.Common.SpeechWrapper.<Enroll_TextIndependentVerification>d__19.MoveNext() in C:\Projects\VoiceIdentification\src\Ossa.VoiceIdentification.Common\SpeechWrapper.cs:line 269
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at Ossa.VoiceIdentification.WindowsClient.Form1.<btnEnrollMicTextIndependant_Click>d__19.MoveNext() in C:\Projects\VoiceIdentification\src\Ossa.VoiceIdentification.WindowsClient\Form1.cs:line 181
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

If I update to Version: Microsoft.CognitiveServices.Speech SDK 1.13.0 I get the following error

   'Exception with an error code: 0x21 (SPXERR_INVALID_HANDLE)'

   
      at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.Internal.SpxFactory.GetDataFromHandleUsingDelegate(GetResultDelegate functionPtr, InteropSafeHandle handle, Int32 maxCharCount)
   at Microsoft.CognitiveServices.Speech.VoiceProfileEnrollmentResult..ctor(IntPtr resultHandlePtr)
   at Microsoft.CognitiveServices.Speech.VoiceProfileClient.<>c__DisplayClass6_0.<EnrollProfileAsync>b__0(InteropSafeHandle h)
   at Microsoft.CognitiveServices.Speech.VoiceProfileClient.<>c__DisplayClass10_0`1.<RunAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ossa.VoiceIdentification.Common.SpeechWrapper.<Enroll_TextDepenentVerification>d__18.MoveNext() in C:\Projects\VoiceIdentification\src\Ossa.VoiceIdentification.Common\SpeechWrapper.cs:line 243
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Ossa.VoiceIdentification.WindowsClient.Form1.<btnEnrollMic_Click>d__15.MoveNext() in C:\Projects\VoiceIdentification\src\Ossa.VoiceIdentification.WindowsClient\Form1.cs:line 127

**Comment by rhurey** [comment] 2020-07-23 19:35
Sorry you hit this...

There's some information missing that enrollment currently needs, and that there isn't an API to provide when creating a VoiceProfile from an ID alone.

I've put a bug in our internal tracking system to address this.

**Comment by suneetnangia** [comment] 2020-07-27 12:41
@rhurey how do we verify the voice later on if we cannot get voiceprofile stored in the service? I am trying to create VoiceProfile("profile guid id") but it fails with the error "Exception with an error code: 0x21 (SPXERR_INVALID_HANDLE)'"

**Comment by lisaweixu** [comment] 2020-07-27 17:02
Hello Suneetnangia,

Your above statement is correct. You would have to keep the voice profile you created from VoiceProfileClient::CreateProfileAsync in order to do verification or identification at the moment.

For the time being, to workaround the issue, you can use the REST API directly. For text-dependent verification, do a HTTP POST like below:
`POST {Endpoint}/speaker/verification/v2.0/text-dependent/profiles/{profileId}/verify`
where, Endpoint for the time being is https://westus.api.cognitive.microsoft.com/, and profileId is the GUID id you have. 

You can try the REST API at [here](https://docs.microsoft.com/en-us/rest/api/speakerrecognition/verification/textdependent/verifyprofile).

Sorry for the inconvenience. This is will be addressed in our next release.

**Comment by suneetnangia** [comment] 2020-07-27 17:13
Thanks for confirming that I wasn't going mad.
I tried the REST API and have another issue which is, when I post a wav file's base64 string data to the service it return-
{
    "error": {
        "code": "InvalidRequest",
        "message": "Audio is too noisy."
    }
}
when I use the same wav file via SDK for verification it returns me the score correctly? Are you doing any processing of wav file in the SDK when we use AudioConfig.FromWavFileInput?  
Also, are you going to have SDK following the new standards i.e. using Azure.Core and open source it?
Cheers.

**Comment by lisaweixu** [comment] 2020-07-27 17:26
The service needs raw PCM data. I have not done any processing other than just sending the raw PCM data. Could it due to the "base64 string data"? I had luck with curl doing HTTP POST to the speaker id service before.

We have "open source" on our road map. I can see open source will be helpful in your case.

**Comment by suneetnangia** [comment] 2020-07-27 21:08
> The service needs raw PCM data. I have not done any processing other than just sending the raw PCM data. Could it due to the "base64 string data"? I had luck with curl doing HTTP POST to the speaker id service before.
> 
> We have "open source" on our road map. I can see open source will be helpful in your case.

Thanks. sending binary data directly worked. Would be nice to have a better error message if data is sent as base64string to reflect the issue.

**Comment by pankopon** [comment] 2020-08-25 18:56
To update, work is now ongoing to add an API that enables creating a VoiceProfile from an ID alone. This is planned for the next Speech SDK release (1.14.0).

Closing this item, please open a new issue if you need further support.

**Comment by AlbertDavletov** [comment] 2020-09-02 23:00
Hi Azure Speaker Recognition team, when are you planning to release the next version (1.14.0) with this fixes?

**Comment by chrisbasoglu** [comment] 2020-09-09 00:10
in approximately 3-4 weeks.

**Comment by lisaweixu** [comment] 2021-01-29 19:31
The fixes is in the latest release of SDK. The latest version is 1.15.

**Comment by xtianus79** [comment] 2022-04-07 14:44
> The fixes is in the latest release of SDK. The latest version is 1.15.

This is still breaking in version 1.20

**Comment by xtianus79** [comment] 2022-04-07 14:44
> The fixes is in the latest release of SDK. The latest version is 1.15.

@lisaweixu this is still breaking in version 1.20

**Comment by xtianus79** [comment] 2022-04-07 17:15
@lisaweixu sorry 1 thing to note is that the error is only coming when using mono/mac versus windows/VS.

**Comment by AparnaJid** [comment] 2022-04-27 08:26
I am having the same issue windows /VS

**Comment by jhakulin** [comment] 2022-04-27 17:53
Issue reopened, and we will check.

**Comment by glharper** [comment] 2022-04-27 18:11
@xtianus79 @AparnaJid Thank you for making us aware of this issue, and for using Speech SDK. Could you provide sample code to reproduce this problem?

**Comment by AparnaJid** [comment] 2022-04-29 07:26
I have used Microsoft sample from Github  
 [speakeridentification.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/8588829/speakeridentification.txt)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/dotnet/speaker-recognition/helloworld/Program.cs) ,  

It is failing in SpeakerIdentificationAsync() @EnrollSpeakerAsync line  . I do have access to speakeridentification preview.

  Please suggest

**Comment by glharper** [comment] 2022-04-29 21:19
@AparnaJid I have found the cause for this issue in the samples. The helloworld.csproj file should have the following lines added on line 78:
    <Content Include="neuralActivationPhrase.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
      <Content Include="TalkForAFewSeconds16.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    
    I will update the sample in the repo to reflect this.

Thanks again for spotting this and letting us know!

**Closed** 2022-04-30 23:02 UTC
Labels: bug
