### ISSUE TITLE
IntentRecognizer not working with LUIS WestEurope app

### ISSUE THREAD

**Issue by nrobert** [Azure-Samples/cognitive-services-speech-sdk#127] opened 2018-12-21 15:14 UTC
**Describe the bug**
I tried to use `IntentRecognizer` with a LUIS app, hosted in WestEurope (https://eu.luis.ai).
I started with the samples and was quickly blocked with this `IntentRecognizer`, where when I send an audio (from audio file for example), the text is well transcribed but then nothing happened about recognition. I just got a canceled event after a long time:

```
Say something...

    Session started event.
RECOGNIZING: Text=tell
RECOGNIZING: Text=current
RECOGNIZING: Text=current weather
CANCELED: Reason=Error
CANCELED: ErrorCode=ConnectionFailure
CANCELED: ErrorDetails=WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR
CANCELED: Did you update the subscription info?

Recognition done.
```

I used exactly the same application on LUIS West US portal (https://www.luis.ai), changing LUIS Subscription key, LUIS App Id and LUIS region, and it is working well:
```
Say something...

    Session started event.
RECOGNIZING: Text=tell
RECOGNIZING: Text=current
RECOGNIZING: Text=current weather
RECOGNIZED: Text=Current weather.
    Intent Id: Weather.GetCondition.
    Language Understanding JSON: {
  "query": "current weather",
  "topScoringIntent": {
    "intent": "Weather.GetCondition",
    "score": 0.9494868
  },
  "entities": []
}.
NOMATCH: Speech could not be recognized.
NOMATCH: Speech could not be recognized.
CANCELED: Reason=EndOfStream

    Session stopped event.

Stop recognition.

Recognition done.
```

In both cases, I used subscription keys of type S0 (not free), apps are targeting English and Speech is enabled in LUIS settings.

Capture (1st call: West US, 2nd call: West Europe):
![image](https://user-images.githubusercontent.com/6305666/50349107-05cc5f80-053b-11e9-9c15-79d2aef58d34.png)

**To Reproduce**
1. Create an app in LUIS WestEurope, which language will be English
2. Add a pre-built domain intent for example, like Weather.GetCondition
3. Add Speech capability in LUIS settings
4. Train and publish.
5. Use `IntentRecognitionSamples` in this repository

**Expected behavior**
IntentRecognizer should return the same thing between WestUs and WestEurope

**Version of the Cognitive Services Speech SDK**
Latest Microsoft.CognitiveServices.Speech NuGet package (1.2.0) for C#

**Platform, Operationg System, and Programming Language**
 - OS: Windows 10 (VM Parallels on Mac)
 - Hardware - x64

**Comment by tjoudeh** [comment] 2018-12-31 18:47
@nrobert this issue is happening with westeurope LUIS app, I tried creating a new key using northeurope region and it is working fine, so https://eu.luis.ai support this but it seems not all the regions. Hope to get an official answer from product group soon.

**Comment by nrobert** [comment] 2019-01-02 11:08
@tjoudeh  you are right, I tried with the same LUIS app (as the West Europe one giving the error) with a North Europe key and it is working, so the problem may be limited to some regions of Europe.

**Comment by vansen** [comment] 2019-01-09 20:19
I am experiencing the same issue. Has there been and updated information on the issue?

**Comment by mahilleb-msft** [comment] 2019-01-11 15:47
Sorry for getting back so late. We can reproduce the issue and are investigating.

Best, Mark

**Comment by mahilleb-msft** [comment] 2019-01-14 09:23
This should be fixed from the service side this week. I'll give an update ones the fix is deployed.
Thanks for your patience,

Mark

**Comment by mahilleb-msft** [comment] 2019-01-17 14:39
@nrobert, @vansen, @tjoudeh - could you please retry? It works for me now...

**Comment by nrobert** [comment] 2019-01-17 14:51
@mahilleb-msft : it works for you... after the fix, right?

**Comment by mahilleb-msft** [comment] 2019-01-17 15:31
Yes, that is correct.

**Comment by nrobert** [comment] 2019-01-17 15:34
Great, I will check tonight once I have a moment and give you a feedback

**Comment by nrobert** [comment] 2019-01-18 08:57
I can confirm that my previous demo is working well now in WestEurope, thanks! May I close the issue?

**Comment by mahilleb-msft** [comment] 2019-01-18 09:22
Thanks for verifying on your end. Closing the issue...

**Closed by mahilleb-msft** 2019-01-18 09:22 UTC
