### ISSUE TITLE
ServiceTimeout, Due to service inactivity the client buffer size exceeded. Resetting the buffer

### ISSUE THREAD

**Issue by johnpaulu** [Azure-Samples/cognitive-services-speech-sdk#842] opened 2020-10-22 17:22 UTC
**Describe the bug**
The issue reappears again, that I have reported here 

https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/490

**To Reproduce**
1. ...
2. ...

**Expected behavior**
Speech to text is terminated

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.
1.7

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 16.04 64b
 - Programming language: Open Java JDK 1.8

**Additional context**
 - Error messages, log information, stack trace, ...

the same logs were provided in the previous bug report

https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/490

 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.

 - Any other additional information

The issue was resolved after reporting it last time, then reappeared again, then resolved again. Today after long time, it appeared again that may suggest that was there any rollback within UKSouth? or overwriting the patch?

Thanks

**Comment by johnpaulu** [comment] 2020-10-22 19:44
this may be also find useful Due to service inactivity the client buffer size exceeded.
 Resetting the buffer. SessionId: f0f1fb871706494eacbc3b6d3e95ecf8

**Comment by johnpaulu** [comment] 2020-10-22 19:45
and for the second case today

Due to service inactivity the client buffer size exceeded. 
Resetting the buffer. SessionId: eb888724d634489db9ceb15e71fafe7b

**Comment by johnpaulu** [comment] 2020-10-22 19:48
and the associated error code: ServiceTimeout

**Comment by jhakulin** [comment] 2020-10-22 19:56
@johnpaulu We will investigate, in the meantime, could you update to latest Speech SDK 1.13.0 ? Is there a reason you use 1.7 version which is quite old ?

**Comment by marlon-br** [comment] 2020-10-29 20:28
I also met this issue today. It was OK earlier and now I constantly receive this error after 10 minutes of speech recognized. Looks like a critical degradation.

And I see the issue on 1.13.0

**Comment by pankopon** [comment] 2020-11-20 20:39
@johnpaulu @marlon-br We have a bug about this on our backlog that was created for https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/490, but unfortunately no ETA for a possible solution yet. We will update here when there is information about the release schedule available. @oscholz FYI.

In the meantime,
- in case using the [batch transcription API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription) is not an option for you,
- and considering that based on https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/490#issuecomment-719041127 the problem is related to the transfer rate of audio input,

then you could try out using a push stream (see continuousRecognitionWithPushStream in https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java#L298) with a short sleep inside the pushStream.write loop, so that the transfer rate is closer to real-time. This is not meant as a solution, just a suggestion to potentially mitigate the issues you are seeing until there is a better fix.

**Comment by pankopon** [comment] 2020-11-30 19:56
Closing this since we have a work item as noted, we'll update when a release with a fix is available. Please create a new issue if you need support on any other topics.

**Closed by pankopon** 2020-11-30 19:56 UTC
Labels: bug, pending close

**Comment by dargilco** [comment] 2021-04-06 23:26
A fix for this issue will be included in Speech SDK version 1.17 likely to be released around mid-May. The recommendation however remains the same: very long audio WAV files should be transcribed using [batch transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription)

**Comment by bobir01** [comment] 2023-07-12 17:33
I am using azure-cognitiveservices-speech==1.29.0 python3.10 SDK , initially it was working fine but now even with small files like 12MB size and length of 1 minute it stucks in this error 
Note I also added pronunciation config to my speech_config but it should be deal

here am attaching my log file 
[my_logs_speechsdk.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/12030697/my_logs_speechsdk.txt)

I created a support ticket on the Azure portal, however no updates at all
