### ISSUE TITLE
SpeechRecognizer in Swedish does not send a final Recognized event.

### ISSUE THREAD

**Issue by LedanDark** [Azure-Samples/cognitive-services-speech-sdk#512] opened 2020-02-17 15:12 UTC
**Describe the bug**
When using the SpeechRecognizer in English I get several Recognizing events that contain the
text that I am speaking. Then I get a final Recognized event, with the overall text analysis. Using the Detailed outputFormat I also get the confidence and list of nbest alternative results. Then I receive a SpeechEnd event.

When using the SpeechRecognizer in Swedish, I also get several Recognizing events that contain the text that I am speaking. Then  I do not get a Recognized event. Then I get a SpeechEnd event.

**To Reproduce**
1. Create a SpeechConfig object, with your credentials, profanity set to raw, detailed outputFormat, 5000ms for initialSilence,2000ms for endSilence, and the language code to "en-US"
2. Create a SpeechRecognizer object from this SpeechConfig, with audio form the default microphone.
3. Run recognition, say "hello world"
4. Repeat steps 1-2, but set the language code to "sv-SE"
5. Run recognition, say "Hej värld"

**Expected behavior**
That regardless of language, the events are triggered in a similar manner.
And that if a Recognizing event is sent, that there will be a final Recognized event.
SpeechStart
Recognizing...(may be several)
Recognized
SpeechEnd

**Version of the Cognitive Services Speech SDK**
Java SDK 1.9.0

**Platform, Operating System, and Programming Language**
 - Ubuntu 18.04
 - Programming language: Java

**Additional context**
 - I have observed that the events sent back are the same for English and French.
 - I have observed the error in Dutch as well.
 - @rhurey Is this a known issue?

**Comment by SquaredCanine** [comment] 2020-02-20 08:55
We observed a similar issue in our application. Would be great to get a fix!

**Comment by jhakulin** [comment] 2020-03-24 01:19
@LedanDark @SquaredCanine We tested with Swedish and could not reproduce the issue. Are you still seeing the problem ?

**Comment by jhakulin** [comment] 2020-03-25 23:17
Closing the issue as not reproduced, let us know if you see issue.

**Closed by jhakulin** 2020-03-25 23:17 UTC
Labels: bug
