### ISSUE TITLE
.Wav File for Asynchronous Conversation Transcription

### ISSUE THREAD

**Issue by MBelkhechine** [Azure-Samples/cognitive-services-speech-sdk#1098] opened 2021-05-23 22:57 UTC
Hi,

I am trying out the C# code sample of the[ Asynchronous Conversation Transcription](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-async-conversation-transcription?pivots=programming-language-csharp). To open the .Wav file, I am using [this Helper.cs](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/helper.cs).

I tried to comment line of the assertion, where it checks for the data but I got an empty result and no speech recognition is reported.

I have tried the process on multiple types of .Wav file (mono-channel, multi-channel) but with no luck.

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech.Remoteconversation Version 1.17.0

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 18.04
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#

**Additional context**
- Error Message: Process terminated. Assertion Failed
  Wrong data tag in wav

**Comment by MBelkhechine** [comment] 2021-05-24 12:56
I have regenerated the .WAV file with the "WAV (Microsoft) signed" format using Audacity and it has solved the issue. The assertion in in [Helper.cs](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/helper.cs) now passes. 

In the previous WAV file, the data sub-chunk comes at a different file offset. After having a closer look at both of the files here is the difference depicted in the following example: 

**Previous File**: RIFFkXWAVEfmt (���>�?��8�qLISTINFOISFTLavf57.83.100data

**WAV (Microsoft) singed file**: RIFFFWAVEfmt �>�data

Notice that in my previous file has extra LIST and INFISFT tags.

Howerever, I am still not able to get any transcription. The result returned is empty. 

Could you please provide a sample compatible WAV file?

**Comment by dargilco** [comment] 2021-05-24 18:31
@MBelkhechine thank you for posting this issue. I'm Darren from the Speech SDK team. If you are using async conversation transcription, it is by design that the service periodically sends empty speech recognition results. This indicates that the service is processing the audio and everything is okay. I will follow up with our technical writers to make sure the public documentation is updated accordingly to mention this. In order to get the recognition results, follow the instructions in the section titled "Get transcription results" in [this page](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-async-conversation-transcription?pivots=programming-language-csharp). If you want to get recognition results in real-time, while you are streaming audio to the Conversational Transcription service, use the "RealTimeAndAsync" mode, as described in the same page.
I'm going to close this issue. Don't hesitate to reactivate if my answer did not help, or open a new issue if you need help with anything else.
Thanks,
Darren

**Closed by dargilco** 2021-05-24 18:31 UTC

**Comment by dargilco** [comment] 2021-05-24 19:04
@MBelkhechine regarding example WAV files, the sample shows katiesteve.wav, which you can find in this repo. The implementation showed in [helper.cs](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/helper.cs) assumes that there is no data chunks interleaved with the audio chunks. That is, after the WAV header, there is only raw audio bytes. If you created the WAV file using a tool that embeds data (tags, time cues) inside the audio, then you will need to update helper.cs to be able to consume this type of file, and skip the data chunks.
