### ISSUE TITLE
Can't Android :install because provider name com.microsoft.cognitiveservices.speech.util.InternalContentProvider is already used by com.fec.moss

### ISSUE THREAD

**Issue by luojt** [Azure-Samples/cognitive-services-speech-sdk#2535] opened 2024-08-09 09:40 UTC
`Error running 'app' The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER Installation failed due to: 'Error code: 'INSTALL_FAILED_CONFLICTING_PROVIDER', message='INSTALL_FAILED_CONFLICTING_PROVIDER: Scanning Failed.: Can't install because provider name com.microsoft.cognitiveservices.speech.util.InternalContentProvider (in package com.*.*) is already used by com.fec.moss'' List of apks: [0] '/apk/debug/app-debug.apk`
This means that another app (with package name com.fec.moss) already has a ContentProvider with the authority com.microsoft.cognitiveservices.speech.util.InternalContentProvider. My app  tries to use the same authority, causing the installation conflict.

**Comment by pankopon** [comment] 2024-08-09 17:35
Duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2463

**Closed by pankopon** 2024-08-09 17:35 UTC
Labels: duplicate
