### ISSUE TITLE
@Darinzhao you can enumerate custom models endpoints logs through [Get Custom Model Endpoint Logs](https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetEndpointLogs), check `.values[].self` on the result.

### ISSUE THREAD

**Issue by Darinzhao** [Azure-Samples/cognitive-services-speech-sdk#1760] opened 2022-11-23 22:00 UTC
@Darinzhao you can enumerate custom models endpoints logs through [Get Custom Model Endpoint Logs](https://westus.dev.cognitive.microsoft.com/docs/services/speech-to-text-api-v3-0/operations/GetEndpointLogs), check `.values[].self` on the result.

_Originally posted by @mahilleb-msft in https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1742#issuecomment-1319835713_

**Comment by Darinzhao** [comment] 2022-11-23 22:05
Hi there,
I want get specific log that I need. But with the method you mentioned I can not get the specific log.As the API document said, if  I need to get the specific log I can use  [Get Custom Model Endpoint Log]. To use this method , it is be required a logid, I have no idea to get this logid. So could help tell how can I get this logid.
Thank you

**Comment by pankopon** [comment] 2022-11-23 23:16
Duplicate of [#1687](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1687)

**Closed by pankopon** 2022-11-23 23:16 UTC
Labels: duplicate
