### ISSUE TITLE
Directly using a stream as input to Speech SDK (from NAudio), speaker recognition cancels

### ISSUE THREAD

**Issue by alexinuk** [Azure-Samples/cognitive-services-speech-sdk#1071] opened 2021-05-10 08:59 UTC
**Describe the bug**

I get cancellation from either Enroll as well as from the RecognizeOnceAsync when using a PushAudioInputStream object to feed data to the sdk (data got from NAudio WasapiLoopbackCapture object).

Cancellation Details are: Bailed out due to wait more than 1 minutes for the result of enrollment or speaker recognition

Same tecnique will work when used for STT service. Saving the corresponding stream to a file and using that file as input to the SpeechRecognizer will work as well, no cancellation results.

**To Reproduce**

Full repro repo can be shared. Please IM over Teams

**Expected behavior**
SpeakerRecognition should be able to work with audio coming from outside pushed to the underdlying stream.

**Version of the Cognitive Services Speech SDK**
1.16

**Platform, Operating System, and Programming Language**
 - OS: Windows 10 21H1
 - Hardware - x64
 - Programming language: C#
 - NAudio package: 1.10.0

**Comment by pankopon** [comment] 2021-05-11 23:19
Hi, as discussed offline the issue is due to a hardcoded limit in the Speech SDK. We now have an internal work item about it (I posted a link on IM), to be considered for the 1.18.0 release, so I'm closing the issue. We'll update the release schedule here when confirmed.

**Comment by oscholz** [comment] 2021-05-20 20:45
marking this as accepted instead, so that @alexinuk will get updated when we resolve this.

**Comment by pankopon** [comment] 2021-08-03 22:13
Closed as fixed in the Speech SDK 1.18.0 release.

**Closed by pankopon** 2021-08-03 22:13 UTC
Labels: accepted, bug
