### ISSUE TITLE
Noise cancellation issue with AudioConfig.fromStreamInput

### ISSUE THREAD

**Issue by ru4sam326** [Azure-Samples/cognitive-services-speech-sdk#2381] opened 2024-05-19 03:17 UTC
**Noise cancellation issue with AudioConfig.fromStreamInput:**

**Description**
Speech SDK recognizer unable to cancel the noise from the audio stream input
 
AudioConfig audioInput = AudioConfig.fromStreamInput( wavStream );
SpeechRecognizer recognizer = new SpeechRecognizer(speechConfig, audioInput);

 
wavestream processing details:
[cognitive-services-speech-sdk/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/WavStream.java at b55026a09e2f807db9289acd6cdd3b623f44b3e9 · Azure-Samples/cognitive-services-speech-sdk (github.com)](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/b55026a09e2f807db9289acd6cdd3b623f44b3e9/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/WavStream.java)

Also when we are specifying the audio processing mentioned in [Use the Microsoft Audio Stack (MAS) - Speech service - Azure AI services | Microsoft Learn](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/audio-processing-speech-sdk?tabs=java) we are getting the below error.
 
Code:
 
MicrophoneCoordinates[] microphoneCoordinates = new MicrophoneCoordinates[7];
microphoneCoordinates[0] = new MicrophoneCoordinates(0, 0, 0);
microphoneCoordinates[1] = new MicrophoneCoordinates(40, 0, 0);
microphoneCoordinates[2] = new MicrophoneCoordinates(20, -35, 0);
microphoneCoordinates[3] = new MicrophoneCoordinates(-20, -35, 0);
microphoneCoordinates[4] = new MicrophoneCoordinates(-40, 0, 0);
microphoneCoordinates[5] = new MicrophoneCoordinates(-20, 35, 0);
microphoneCoordinates[6] = new MicrophoneCoordinates(20, 35, 0);
MicrophoneArrayGeometry microphoneArrayGeometry = new MicrophoneArrayGeometry(MicrophoneArrayType.Planar, microphoneCoordinates);
AudioProcessingOptions audioProcessingOptions = AudioProcessingOptions.create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT, microphoneArrayGeometry, SpeakerReferenceChannel.LastChannel);
AudioConfig audioInput = AudioConfig.fromStreamInput( wavStream, audioProcessingOptions);
SpeechRecognizer recognizer = new SpeechRecognizer(speechConfig, audioInput);
 
Error:
 
java.lang.RuntimeException: Exception with an error code: 0x5 (SPXERR_INVALID_ARG)
	at com.microsoft.cognitiveservices.speech.util.Contracts.throwIfFail(Unknown Source) ~[client-sdk-1.37.0.jar:na]
	at com.microsoft.cognitiveservices.speech.audio.AudioProcessingOptions.create(Unknown Source) ~[client-sdk-1.37.0.jar:na]

**To Reproduce**

We are using websockets to receive the audio stream and giving input like below

public void handleBinaryMessage(WebSocketSession session, BinaryMessage  message) throws Exception {
       byte[] arr = new byte[message.getPayloadLength()];
       message.getPayload().get(arr);
       SpeechConfig speechConfig = SpeechConfig.fromSubscription("**********************", "******");
      speechConfig.setSpeechRecognitionLanguage("en-IN");
        InputStream bStream = new ByteArrayInputStream(arr);
        WavStream wavStream = new WavStream(bStream );
      

        AudioConfig audioInput = AudioConfig.fromStreamInput( wavStream);

        SpeechRecognizer recognizer = new SpeechRecognizer(speechConfig, audioInput);

        recognizer.recognized.addEventListener((s, e) -> {
            if (e.getResult().getReason() == ResultReason.RecognizedSpeech) {
                System.out.println("RECOGNIZED: Text=" + e.getResult().getText());
            } else if (e.getResult().getReason() == ResultReason.NoMatch) {
                System.out.println("NOMATCH: Speech could not be recognized.");
            }
        });

**Expected behavior**

When we are chosing the microphone input noise is being cancelled but not with the stream,

**Version of the Cognitive Services Speech SDK**

1.37 we are using.

**Comment by glharper** [comment] 2024-05-20 13:44
@ru4sam326 Thank you for writing this up here for better visibility from our team's Java experts. I don't believe you need to configure a microphone geometry since you're using a pushStream audio input. Could you try this code and see if it works?
```
AudioProcessingOptions.create(AudioProcessingConstants.AUDIO_INPUT_PROCESSING_ENABLE_DEFAULT);
AudioConfig audioInput = AudioConfig.fromStreamInput( wavStream, audioProcessingOptions);
```

**Comment by pankopon** [comment] 2024-05-21 21:02
Duplicate of Azure incident 505180412. Why create 2 issues about the same topic on different forums?

**Closed by pankopon** 2024-05-21 21:02 UTC
Labels: duplicate
