### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) 

### ISSUE THREAD

**Issue by apobekiaris** [Azure-Samples/cognitive-services-speech-sdk#1636] opened 2022-09-01 06:54 UTC
**Describe the bug**
I am running the `translation-wpf` sample and the library works in my own .net6 apps, also I have installed latest C++

![image](https://user-images.githubusercontent.com/159464/187850522-612056a8-6fb2-41b1-9a1f-ee90cf2e5373.png)

**Comment by apobekiaris** [comment] 2022-09-06 14:05
the screenshot I posted is from when I run this repo `translation-wpf` sample

**Comment by jhakulin** [comment] 2022-09-07 16:02
Thanks for the report, I can reproduce the issue and probably the problem is due to outdated WPF project configuration/template. When creating WPF project as new project, I cannot see any loading issues. I think it is
best to update our WPF samples to use latest template. Will create workitem for that.

**Comment by jhakulin** [comment] 2022-09-07 16:07
Internal workitem refs: 4499252, 4499254

**Comment by glecaros** [comment] 2022-11-10 23:39
These samples have been removed (and a workaround was provided) so I'm closing this item.

**Closed by glecaros** 2022-11-10 23:39 UTC
Labels: accepted
