### ISSUE TITLE
Issue with batch processing python main.py

### ISSUE THREAD

**Issue by SShah30-hue** [Azure-Samples/cognitive-services-speech-sdk#1721] opened 2022-11-02 17:05 UTC
I have been using this code for a while now and it never throwed any errors until now. I am getting the below error when attempting to transcribe more than 99 audio files stored in a blob folder. Before I used to transcribe more than 99 files easily. Any help would be massively appreciated. 

![error](https://user-images.githubusercontent.com/61804269/199805715-19dc444a-c961-4ed8-a93b-d8c936632132.PNG)

**Comment by chschrae** [comment] 2022-11-02 17:31
Hello and thanks for reaching out to us,

Based on your snippit I cannot tell if you are using the SDK or the rest API. Based on the quota documentation here: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-services-quotas-and-limits

it appears there is a limit of 100 concurrent requests when using the SDK but a larger limit on the Batch REST API. Are you hitting any of these limits? If so, there is a way to adjust them here: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-services-quotas-and-limits#speech-to-text-increase-online-transcription-concurrent-request-limit

**Comment by SShah30-hue** [comment] 2022-11-02 17:42
Hi @chschrae - many thanks for your quick take on this. 

I am using REST API - using this script [https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py](url)

No, I don't believe I am hitting the max limits since batch trancription on Standard (S0) allows 1000 max number of files per transcription request and I have used the same script before and it never stopped working at 99.

**Comment by chschrae** [comment] 2022-11-03 16:18
It must be the concurrent request limit since that is near 100. Can you go through the steps to increase your quota or introduce a sleep between requests to see if that solves the problem?

**Comment by SShah30-hue** [comment] 2022-11-03 17:40
There already is sleep introduced in the code if you take a look. The concurrent request limt 100 is for online transcription and not for batch transcription. I tried raising a support request to increase the quota but turns out you need admin priviliges for that which I don't have.

**Comment by chschrae** [comment] 2022-11-03 18:00
The sleep that is in the sample code is checking the transcription status not in between requests. I'm also not sure if you are making many requests or one large request from a single blob. If you would like to share your altered sample code, I could look at that. (remember not to share your subscription key)

It does seem clear though that some limit is being hit at your 99 mark. It could be the blob size limit or the audio file size limit, or the container size limit. Are you able to confirm these are not being hit?

**Comment by SShah30-hue** [comment] 2022-11-03 18:22
I am generating a SAS URI of a container which is used to send requests to transcribe all files within that blob container. In that container, there are only 100 audio files, totalling 78.67 MiB and each ranging from 39.32 KiB to 4.78 MiB. Don't think this is a problem since I have transcribed them before as well and ran the sample code successfully. 

I found the issue - it is to do with the recent change made to the swagger_client. Apparently, the recently approved URL used for importing Swagger Speech API was causing the issue including the use of "CustomSpeechTranscriptionsApi". 

To fix the issue, I simply reverted back to the older URL which uses "DefaultApi" as seen in the attached pictures below. 

What do you think about this?


![1](https://user-images.githubusercontent.com/61804269/199803551-b092fa0b-a564-49d0-a03a-102861455a25.png)

![2](https://user-images.githubusercontent.com/61804269/199803555-2812e12e-e5f3-4ce3-ab63-397438792f35.PNG)

**Comment by chschrae** [comment] 2022-11-03 18:28
@chlandsi It seems you made the change referred to here. Is there a chance this change was in error?

**Comment by zhouwangzw** [comment] 2022-11-10 20:10
I do not think the change in swagger_client itself causes any issues. It is generated code from Swagger specification. The change is to use the official location of Azure REST API specification to generate code instead of hosting it by ourselves. 

From the error shown above (error 401) it looks that the client either uses a wrong api key of speech resource or a wrong region. As described in [main.py](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py#L18) you need to replace the key and region with the one you created on Azure portal (please see [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/batch/python/python-client/main.py#L18) for details.

If you still have issues, please provide us the host name of your POST call targeting the speech service, and the error and the apim-request-id in the response, as well as the rough time of your request, so that we can investigate.

Thanks,

**Comment by eldakms** [comment] 2022-11-10 22:38
@SShah30-hue , this is indeed bug in the sample, the transcription has actually succeeded, but the call the fetch the next result after 100 fails. I will provide the fix in the next days. The problem is the pagination uses a wrong set of auth parameters, in particular this line: 
    auth_settings = ["apiKeyHeader", "apiKeyQuery"]

Should be instead 
    auth_settings = ["api_key"]

Because this is how security is defined in the swagger file.

We are very sorry for the trouble.
P.S. By the way, your transcription succeeded, so you should be able to fetch the results with the above change, there is no need to redo the actual transcription (create_transcription call).

@SShah30-hue , i would appreciate if you could confirm that above workaround solved your problem. thanks!

**Comment by eldakms** [comment] 2022-11-11 09:52
PR with the fix is here: https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/1739, thanks!

**Comment by SShah30-hue** [comment] 2022-11-11 10:58
@eldakms Thanks so much for your quick resolve! I have tested it and all seems to be working fine with the change you have made to the pagination function.

**Comment by glecaros** [comment] 2022-11-14 19:16
Closing the issue based on the latest communication.

**Closed by glecaros** 2022-11-14 19:16 UTC
Labels: Rest API
