### ISSUE TITLE
use  restapi   in   translate-speech-to-text   Can not be  play voice

### ISSUE THREAD

**Issue by daigongzheng** [Azure-Samples/cognitive-services-speech-sdk#795] opened 2020-09-08 11:48 UTC
I use chinaeast2  restapi  subscription key  in   translate-speech-to-text   cannot play sound
![1](https://user-images.githubusercontent.com/70951112/92472311-df1cf380-f20b-11ea-8efc-08588c4c920e.png)
![2](https://user-images.githubusercontent.com/70951112/92472364-efcd6980-f20b-11ea-92e2-c6c2771e3627.png)

**Comment by trrwilson** [comment] 2020-09-08 19:01
Hello! Thanks for getting in touch. Could you please share more about what you're seeing when the playback fails? Specifically:

* Do you receive synthesizing events (e.g. does that last Console.WriteLine in the second picture emit output) or, conversely, do you see any Canceled events with errors that might have more information?
* If you receive synthesizing events, is audio.Length reported as a good (>0) value or is it not providing any data?
* If you're getting far enough to receive [SessionStarted](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.recognizer.sessionstarted?view=azure-dotnet) events out of the TranslationRecognizer, the IDs from that event would be very helpful in examining any of the service traffic in the event there are unexpected responses
* Additionally, if you can collect and share device logs following [the documented steps with the config property](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging), that'd be very helpful in understanding the root cause of the issue you're seeing.

Based on the above, we'll be able to investigate further and/or recommend a fix.

Thanks again!

**Comment by daigongzheng** [comment] 2020-09-09 01:38
I tested it, but can not receive synthesizing events so  this event should not have been executed
![3](https://user-images.githubusercontent.com/70951112/92544271-12996580-f280-11ea-88bb-8ac55e90c7ab.png)

**Comment by daigongzheng** [comment] 2020-09-09 03:36
this is device logs, SessionStarted event(SessionId): e9c444b1cf4b4876bc37668f289b3ab7
![4](https://user-images.githubusercontent.com/70951112/92551464-9ce9c580-f290-11ea-8d33-44ea723eda6d.png)
[Log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5192455/Log.txt)

**Comment by trrwilson** [comment] 2020-09-09 21:02
Thank you for the additional detail! The log and session information was very helpful in reproducing this. I can confirm that I see the same behavior and we're investigating now. It appears that this behavior is unique to ChinaEast2 (it, at least, doesn't reproduce on several other regions tested).

That leads to a question: is there a strong reason that chinaeast2 needs to be used? Although the behavior here should for sure be complete and consistent, chinaeast2 isn't an [officially supported region](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions) for this functionality. I verified that eastasia works and would recommend that as a supported region if it meets your needs.

**Comment by sunt89** [comment] 2020-09-10 01:24
@trrwilson
 Thank you for your reply.

Our customers use Azure China, but they do not have Azure Global subscription, so we need to use the region of Chinaeast2, because the speech service only supports this region in  Azure China

![image](https://user-images.githubusercontent.com/20986998/92670617-fb717b00-f346-11ea-92a5-502b0cd47b79.png)

![image](https://user-images.githubusercontent.com/20986998/92670666-17751c80-f347-11ea-8537-4ea5f79304fe.png)

**Comment by splusq** [comment] 2020-11-02 18:15
we are looking into this.

**Comment by pankopon** [comment] 2020-11-17 03:30
@splusq Is this under active investigation on your side? Please provide an update.

**Comment by BrianMouncer** [comment] 2020-12-07 19:03
No new updates on this issue in 21 days.
I'm closing this issue for now.

**Closed by BrianMouncer** 2020-12-07 19:03 UTC
Labels: bug, pending close
