### ISSUE TITLE
SDK fails to connect to Azure services with error "[645277]: 167749ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:1006 TS:852, TransportError: connection:0x18131440, code=5, string=Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508. "

### ISSUE THREAD

**Issue by debdeep82** [Azure-Samples/cognitive-services-speech-sdk#1017] opened 2021-03-30 10:26 UTC
We tried both java and cpp based application with speechsdk with Speech Transcription (Recognizer) and with BOT frameowork config for directline speech in linux (rhel 7.9). Tried following link
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-rhel-centos-7.

compressed-audio-input
from-microphone
text-to-speech

Can you please suggest how the error should be resolved.

Case 1: 
[436587]: 2092ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:650 [0x7b0cc0]CSpxAudioStreamSession::ProcessNextAudio: no audio buffer in the m_audioBuffer.
[436587]: 2134ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:678 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[436587]: 2134ms SPX_TRACE_ERROR:  trace_message.cpp:193 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:678
[436587]: 2134ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:2399 FORCE-Closing tlsio instance.
[436587]: 2134ms SPX_TRACE_ERROR:  trace_message.cpp:193 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_close Line:2399
[436587]: 2134ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  web_socket.cpp:857 WS open operation failed with result=1(WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED), code=2508[0x000009cc]
[436587]: 2134ms SPX_TRACE_ERROR:  trace_message.cpp:193 Error: File:/home/vsts/work/1/s/source/core/common/web_socket.cpp Func:OnWebSocketOpened Line:857
[436587]: 2134ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:1006 TS:1583, TransportError: connection:0x10009860, code=5, string=Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508.
[436587]: 2134ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:2032 Response: On Error: Code:5, Message: Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508..
[436587]: 2134ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2664 TryChangeState; audioState/uspState: 2/1000 => 2/-1 USP-ERRORERROR
[436587]: 2134ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:2046 OnError: site->Error() ... error='Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508.'

Case2 :

[450283]: 76331ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:913 TS:3, Flush audio buffer.
[450283]: 76331ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:650 [0x7f90b82abaa0]CSpxAudioStreamSession::ProcessNextAudio: no audio buffer in the m_audioBuffer.
[450283]: 76331ms SPX_DBG_TRACE_SCOPE_EXIT:  audio_stream_session.cpp:1035 StartRecognizing
[450283]: 76331ms SPX_DBG_TRACE_SCOPE_ENTER:  usp_reco_engine_adapter.cpp:52 ~CSpxUspRecoEngineAdapter
[450283]: 76331ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:53 ~CSpxUspRecoEngineAdapter: this=0x0x7f9048034740
[450283]: 76331ms SPX_DBG_TRACE_SCOPE_EXIT:  usp_reco_engine_adapter.cpp:52 ~CSpxUspRecoEngineAdapter
[450283]: 76331ms SPX_TRACE_INFO: AZ_LOG_INFO:  web_socket.cpp:762 DoWork: open transport.
[450283]: 76331ms SPX_TRACE_INFO: AZ_LOG_INFO:  web_socket.cpp:516 Start to open websocket. WebSocket: 0x48009040, wsio handle: 0x48041fc0
[450283]: 76331ms SPX_TRACE_INFO: AZ_LOG_INFO:  tlsio_openssl.c:1963 create_openssl_instance by TLS_method.
[450283]: 76331ms SPX_TRACE_INFO: AZ_LOG_INFO:  tlsio_openssl.c:1791 load_system_store not implemented on this platform
[450283]: 76472ms SPX_DBG_TRACE_SCOPE_ENTER:  web_socket.cpp:224 ~WebSocket
[450283]: 76472ms SPX_DBG_TRACE_SCOPE_EXIT:  web_socket.cpp:224 ~WebSocket
[450283]: 77176ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:678 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
[450283]: 77176ms SPX_TRACE_ERROR:  trace_message.cpp:193 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:678
[450283]: 77176ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  tlsio_openssl.c:2399 FORCE-Closing tlsio instance.
[450283]: 77176ms SPX_TRACE_ERROR:  trace_message.cpp:193 Error: File:/home/vsts/work/1/s/external/azure-c-shared-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_close Line:2399
[450283]: 77176ms SPX_TRACE_ERROR: AZ_LOG_ERROR:  web_socket.cpp:857 WS open operation failed with result=1(WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED), code=2508[0x000009cc]
[450283]: 77176ms SPX_TRACE_ERROR:  trace_message.cpp:193 Error: File:/home/vsts/work/1/s/source/core/common/web_socket.cpp Func:OnWebSocketOpened Line:857
[450283]: 77176ms SPX_TRACE_INFO: AZ_LOG_INFO:  uspimpl.cpp:1006 TS:849, TransportError: connection:0x48006c90, code=5, string=Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508.
[450283]: 77176ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:2032 Response: On Error: Code:5, Message: Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508..
[450283]: 77176ms SPX_DBG_TRACE_VERBOSE:  usp_reco_engine_adapter.cpp:2664 TryChangeState; audioState/uspState: 2/1000 => 2/-1 USP-ERRORERROR
[450283]: 77176ms SPX_TRACE_ERROR:  usp_reco_engine_adapter.cpp:2046 OnError: site->Error() ... error='Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508.'
[450283]: 77176ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:2197 Error: Creating/firing ResultReason::Canceled result
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  factory_helpers.h:56 Creating object via SpxFactoryEntryCreateObject: N9Microsoft17CognitiveServices6Speech4Impl21CSpxRecognitionResultE as N9Microsoft17CognitiveServices6Speech4Impl21ISpxRecognitionResultE
[450283]: 77177ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:23 CSpxRecognitionResult
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  create_object_helpers.h:51 SpxCreateObjectWithSite: Attempted SetSite(CSpxRecognitionResult), objectWithSite==nullptr
[450283]: 77177ms SPX_DBG_TRACE_FUNCTION:  recognition_result.cpp:93 InitErrorResult
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.cpp:138 LogPropertyAndValue: this=0x0x7f9048007570; name='RESULT-ErrorDetails'; value='Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508.'
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1206 [0x7f90b82abaa0]CSpxAudioStreamSession::WaitForRecognition_Complete: ...
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.cpp:138 LogPropertyAndValue: this=0x0x7f90b82cc438; name='IsKeywordRecognizer'; value=''
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1348 [0x7f90b82abaa0]CSpxAudioStreamSession::FireResultEvent
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.cpp:138 LogPropertyAndValue: this=0x0x7f9048007570; name='RESULT-ErrorDetails'; value='Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508.'
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.cpp:138 LogPropertyAndValue: this=0x0x7f9048007570; name='RESULT-ErrorDetails'; value='Connection failed (no connection to the remote host). Internal error: 1. Error details: Code: 2508. SessionId: b6bf9228f11e43049971884039feadc6'
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  property_bag_impl.cpp:138 LogPropertyAndValue: this=0x0x7f90b82cc438; name='IsKeywordRecognizer'; value=''
[450283]: 77177ms SPX_DBG_TRACE_VERBOSE:  audio_stream_session.cpp:1367 [0x7f90b82abaa0]CSpxAudioStreamSession::FireResultEvent: Firing RecoResultEvent(Canceled): SessionId: b6bf9228f11e43049971884039feadc6

**Comment by debdeep82** [comment] 2021-03-30 17:34
Thanks Brian for your revert. We have checked this link (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-configure-openssl-linux?pivots=programming-language-csharp)
and tried the necessary propertis in code. But it didn't still work. 
We think the openssl setting is applicable for rhel 7 and rhel 8 both ? Right now we are trying to deploy it in rhel 7.

**Comment by rhurey** [comment] 2021-03-30 18:26
> [450283]: 77176ms SPX_TRACE_ERROR: AZ_LOG_ERROR: tlsio_openssl.c:678 error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

Is the trace line that's blocking the connection.

There's not a lot of logging *why* the validation failed, but since it's not complaining about CRL download issues, the cause is typically that the root cert store isn't found or doesn't contain the cert issuer.

You did this?

> # Set SSL cert file location
> # (this is required for any development/testing with Speech SDK)
> export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt

**Comment by debdeep82** [comment] 2021-03-31 10:50
@BrianMouncer @rhurey thank you evry much for prompt feedback. 
export SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt helped to make the cpp linux based example working with connectivity correctly established.

Please help us with one more quesry we have raised (https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1016) when we are trying to deploy the java aplication in rhel 7.9. Today we user the .so files from SpeechSDK-Linux-1.16.0.tar.gz (retrieved from wget -O SpeechSDK-Linux.tar.gz https://aka.ms/csspeech/linuxbinary ) and deployed .so files 

-rwxrwxrwx. 1 root root 6443784 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.core.so
-rwxrwxrwx. 1 root root   84960 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.extension.codec.so
-rwxrwxrwx. 1 root root  130360 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.extension.audio.sys.so
-rwxrwxrwx. 1 root root  468248 Mar 31 08:50 libMicrosoft.CognitiveServices.Speech.extension.kws.so
[root@hybay5vm1 so]#

And jar  fieles we used in our application classpath are 

-rwxrwxrwx. 1 root root   106901 Mar 29 14:52 bot-schema-4.6.0-preview3.jar
-rwxrwxrwx. 1 root root   503880 Mar 29 14:53 commons-lang3-3.9.jar
-rwxrwxrwx. 1 root root    66519 Mar 29 14:53 jackson-annotations-2.9.0.jar
-rwxrwxrwx. 1 root root   348635 Mar 29 14:53 jackson-core-2.10.0.jar
-rwxrwxrwx. 1 root root  1400944 Mar 29 14:54 jackson-databind-2.10.0.jar
-rwxrwxrwx. 1 root root    70820 Mar 29 14:54 jackson-datatype-joda-2.9.8.jar
-rwxrwxrwx. 1 root root   100674 Mar 29 14:54 jackson-datatype-jsr310-2.9.9.jar
-rwxrwxrwx. 1 root root   589289 Mar 29 14:54 joda-time-2.7.jar
**-rwxrwxrwx. 1 root root 10547027 Mar 31 08:58 client-sdk-1.16.0.jar**

But when the application is invoked we are hitting following exception :

Mar 31 UTC 2021 09:53:21 AM.937347| 7201  |  OrigTrunkLeg$3                | 0| Id ERROR | S:3 Unexpected userLevel exception (task: OTL.connectionStateChange) exception occured:
                                  |       |                               | java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Ljava/lang/String;)V
                                  |       |                               |     at com.microsoft.cognitiveservices.speech.SpeechConfig.setTempDirectory(Native Method)
                                  |       |                               |     at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:74)
                                  |       |                               |     at hpe.opencall.media.exampoclets.bot.BotService.connect(BotService.java:243)
                                  |       |                               |     at hpe.opencall.media.exampoclets.bot.BotService$2.trunkLegStateChange(BotService.java:199)
                                  |       |                               |     at hp.opencall.media.service.OrigTrunkLeg$3.runTask(OrigTrunkLeg.java:483)
                                  |       |                               |     at hp.opencall.media.platform.FWTask.startTask(FWTask.java:221)
                                  |       |                               |     at hp.opencall.media.platform.FWThread.run(FWThread.java:356)

Could you please suggest us what we may be doing wrong and do you have any README with using java clent-sdk in linux to make such a application working where java will be doing jni calls towards spech sdk .so libraries.

**Comment by rhurey** [comment] 2021-03-31 16:32
Since this issue is resolved I'm going to close it, and we can continue looking at 1017 there.

**Closed by rhurey** 2021-03-31 16:32 UTC
