### ISSUE TITLE
Getting Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by saisandeeppalla** [Azure-Samples/cognitive-services-speech-sdk#517] opened 2020-02-24 11:21 UTC
Hi, 

I have used Microsoft cognitive speech service in my C# code and accessing the input from microphone. It worked fine when the code is in my local system. When I published the code to a azure app service and run the code then I am getting the exception "Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)". Below is the code snippet.

I have a angular front end application with backend .Net core API in which I used the Speech service and I am deploying the API to azure app service.

Can Someone help me how to proceed on this ? 

var config = SpeechConfig.FromSubscription("------------------------", "---------");

            using (var recognizer = new SpeechRecognizer(config))
            {
                var result = await recognizer.RecognizeOnceAsync();

                if (result.Reason == ResultReason.RecognizedSpeech)
                {
                    Console.WriteLine($"We recognized: {result.Text}");
                }
                else if (result.Reason == ResultReason.NoMatch)
                {
                    Console.WriteLine($"NOMATCH: Speech could not be recognized.");
                }
                else if (result.Reason == ResultReason.Canceled)
                {
                    var cancellation = CancellationDetails.FromResult(result);
                    Console.WriteLine($"CANCELED: Reason={cancellation.Reason}");

                    if (cancellation.Reason == CancellationReason.Error)
                    {
                        Console.WriteLine($"CANCELED: ErrorCode={cancellation.ErrorCode}");
                        Console.WriteLine($"CANCELED: ErrorDetails={cancellation.ErrorDetails}");
                        Console.WriteLine($"CANCELED: Did you update the subscription info?");
                    }
                }
                return await Task.FromResult<string>(result.Text);
            }

**Comment by chrisbasoglu** [comment] 2020-02-24 17:14
Azure App Service runs on servers in the cloud.  Those servers don't have microphones (since the microphones would be somewhere in the datacetner were customers can't physically go).  If you wish to create a web app for your customers to use the microphone from the browser/web, you should use the javascript version of the SDK, and embedd that js code into your web page.

**Comment by saisandeeppalla** [comment] 2020-02-25 08:15
@chrisbasoglu Thank you. Actual I am having a front end angular application. Can I use the Javascript SDK in angular application ? Is there any docs related to that ??

**Comment by saisandeeppalla** [comment] 2020-02-25 13:43
I tried to use Javascript SDK in angular using npm install  **npm install microsoft-cognitiveservices-speech-sdk** and I am getting the error  **"Runtime error: Unable to contact server. StatusCode: 500, undefined Reason: ReferenceError: process is not defined"**  when recognizer.RecognizeOnceAsync is called.

const speechConfig = SpeechConfig.fromSubscription('---------', '--------');
    speechConfig.speechRecognitionLanguage = 'en-US';
    const audioConfig  = AudioConfig.fromDefaultMicrophoneInput();
    let recognizer = new SpeechRecognizer(speechConfig, audioConfig);
    recognizer.recognizeOnceAsync(
      (result: SpeechRecognitionResult) => {
        window.console.log(result.text);
        recognizer.close();
        recognizer = undefined;
      },
      err => {
        window.console.log(err);
        recognizer.close();
        recognizer = undefined;
      });

**Comment by rhurey** [comment] 2020-02-25 17:24
This is the same error as https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/131, I'll see if I can get a fix out soon.

**Comment by rhurey** [comment] 2020-03-05 00:40
V1.10.0 has the fix and released. Closing.

**Closed by rhurey** 2020-03-05 00:40 UTC
Labels: bug

**Comment by kouroshsalahshoor** [comment] 2022-09-02 13:53
How can I do this in a Blazor server side?

**Comment by simonziegler** [comment] 2023-02-05 09:27
@kouroshsalahshoor I have the same issue. Did you get a resolution?

**Comment by kouroshsalahshoor** [comment] 2023-02-07 18:33
Hi Simon,

Sorry for late answer. I was busy.

Unfortunately I didn't have time to solve it, but I believe the problem is that there is just one instance of Blazor server side. So i think the speech file must be saved on the server for each user and then be given to each user seperately.

I hope i helped

kourosh
________________________________
