### ISSUE TITLE
Speech is not recognized on HoloLens at random times (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)

### ISSUE THREAD

**Issue by rfurmaniak** [Azure-Samples/cognitive-services-speech-sdk#835] opened 2020-10-15 13:41 UTC
**Describe the bug**
We are using Speech Recognition in several projects, and starting sometime around August/September (maybe new update of OS, maybe update of library) it started to fail randomly. When calling StartRecognition, following error is given:
"0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)"

Reinstalling the application always helps. Restarting the device - not so often. Error also seem to randomly go away after some time. It has been reported on several devices in several different locations. It started popping up without on production version of our store application without any updates by the users. 

We also received information that switching audio setting to mono helped to unblock the feature. Changing used microphone by connecting a bluetooth device also fixed the issue.

**To Reproduce**
1. Recreate Speech Recognition as in tutorial for Unity.
2. Call StartRecognition
3. Exception will be thrown (not always)

It is hard to pinpoint what exactly is producing this issue, because the behavior seemed very random. I also repeat that it started to occur without application update, so it does not seem to be a code error (but it could have started after OS update)

**Expected behavior**
Start recognition does not throw exception and correctly captures speech.

**Version of the Cognitive Services Speech SDK**
1.13, but it also happened on earlier versions

**Platform, Operating System, and Programming Language**
 - OS: Windows Holographic 10.0.19041.1117, firmware version 11971.01.01.200609.F
 - Hardware - HoloLens 2, ARM, built from Unity 2019.4.0f1 using IL2CPP backend
 - Programming language: C#

**Additional context**
Here is a stack trace:
Exception with an error code: 0x13 (SPXERR_START_RECOGNIZING_INVALID_STATE_TRANSITION)   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail (System.IntPtr hr) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Microsoft.CognitiveServices.Speech.Recognizer.StartContinuousRecognition () [0x00000] in <00000000000000000000000000000000>:0 \r\n  at UnityEngine.Experimental.LowLevel.PlayerLoopSystem+UpdateFunction.Invoke () [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Microsoft.CognitiveServices.Speech.Recognizer.DoAsyncRecognitionAction (System.Action recoImplAction) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Microsoft.CognitiveServices.Speech.SpeechRecognizer.<StartContinuousRecognitionAsync>b__29_0 () [0x00000] in <00000000000000000000000000000000>

**Comment by BrianMouncer** [comment] 2020-10-15 17:26
Could you [collect detailed logs](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) while preproducing this error condition on a device?

Note: I would expect a different error if it was a cert issue, but since you are hitting this is on HL2, I know there is an current issue where some HL2 devices do not trust the new Digicert Baltimore G2 CA out of the box.  The devices will download an updated trusted root CA list eventually, but if you open edge and browse to this https URI, that should force the device to download a current root CA list to validate the root CA that is the parent of the certs azure services have been changing over to.  It wouldn't hurt to try doing this on a device hitting your issue, and see if it resolves the issue. and if you can send us details logs files from your repro case, we can look at what internal state transition is being hit unexpectedly.

Thanks...

https://global-root-g2.chain-demos.digicert.com/info/index.html

**Comment by jhakulin** [comment] 2020-10-16 04:06
@rfurmaniak could you share your Unity script or sample which reproduces the issue ? Are you using streams input with push/pull stream API and Unity's microphone or do you create audio config via default microphone using Speech SDK?

**Comment by rfurmaniak** [comment] 2020-10-16 06:40
@jhakulin Yes, here is the script that we are using for capturing speech:
`public class AzureSpeechToText : Singleton<AzureSpeechToText>
    {
        [SerializeField] [Tooltip("Sets language to match system language. Default language is english")]
        private bool autoSetLanguage = true;

        public SpeechRecognizer Recognizer { get; private set; }
        private SpeechConfig _currentConfig;

        //language selection: "en-GB", "en-AU", "en-US", "de-DE", "pl-PL", "hi-IN", "ko-KR", "fr-FR", "es-ES"
        private string _currentLangCode = "en-US";

        private void Start()
        {
            if (autoSetLanguage)
                SetLanguage(CultureInfo.CurrentUICulture.IetfLanguageTag);

            var speechConfig = AppSettings.Instance.SpeechConfig;
            _currentConfig = SpeechConfig.FromSubscription(speechConfig.SubscriptionKey, speechConfig.Region);
            _currentConfig.SpeechRecognitionLanguage = _currentLangCode;
        }

        private void CreateRecognizer()
        {
            if (Recognizer != null)
            {
                Recognizer.Dispose();
                Recognizer = null;
            }

            Recognizer = new SpeechRecognizer(_currentConfig);
        }

        private async void OnDisable()
        {
            if (Recognizer != null)
                await EndRecognizing();
        }

        /// <summary>
        /// Starts speech recognition.
        /// </summary>
        public async Task StartRecognizing()
        {
            CreateRecognizer();
            await Recognize();
        }

        /// <summary>
        /// Finishes speech recognition
        /// </summary>
        public async Task EndRecognizing()
        {
            if (Recognizer == null)
                return;

            await PauseRecognize().ConfigureAwait(false);
            Recognizer.Dispose();
        }

        /// <summary>
        /// Starts recognizer
        /// </summary>
        /// <returns></returns>
        public async Task Recognize()
        {
            await Recognizer.StartContinuousRecognitionAsync();
        }

        /// <summary>
        /// Stops Recognizer
        /// </summary>
        /// <returns></returns>
        public async Task PauseRecognize()
        {
            await Recognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
        }

        private void SetLanguage(string newLangCode)
        {
            _currentLangCode = newLangCode;
        }
    }`

Other script that handles user input only calls StartRecognizing() - and this call will produce the exception.
So, as you can see, we are using default microphone and Speech SDK.

@BrianMouncer thank you for your response, we will pass over this link to our support and incorporate detailed logs in the next test version of our application and try to collect those. I will paste them here once we acquire them.

**Comment by rfurmaniak** [comment] 2020-10-16 06:58
Additional context: capturing speech always works in Unity Editor.

**Comment by rfurmaniak** [comment] 2020-10-27 07:37
[speech_logs.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/5443629/speech_logs.txt)

Here is a detailed speech log

**Comment by jhakulin** [comment] 2020-11-02 16:58
@rfurmaniak The problem based on your log is related to certificate verification. SSL routines:ssl3_get_server_certificate:certificate verify failed

There is quite recent change in Speech SDK certificates used by service and that has caused issues with HL2 devices. 
Microsoft is working on updating the required certificate to HL2 OS images. For next steps, could you try following:
1. Make sure you have the latest OS update done for HL2
2. Visit https://global-root-g2.chain-demos.digicert.com/info/index.html in Edge of your HL2 device
3. Try the repro again

**Comment by pankopon** [comment] 2020-11-17 04:30
@rfurmaniak Is this issue still valid for you or was it resolved by the suggested steps? Please update.

**Comment by rfurmaniak** [comment] 2020-11-17 10:48
@pankopon It seems that the issue has been resolved. We could not reproduce it for two weeks now. However, I cannot say if it was due to the steps you suggested or not. There have been OS updates on HL2 during this period, which may have also fixed this issue.
Thanks for the help :)

**Comment by pankopon** [comment] 2020-11-18 05:09
Closed as resolved.

**Closed by pankopon** 2020-11-18 05:09 UTC
Labels: bug
