### ISSUE TITLE
RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE) in Microsoft Azure Notebook

### ISSUE THREAD

**Issue by bancanus** [Azure-Samples/cognitive-services-speech-sdk#684] opened 2020-06-13 08:31 UTC
I am testing Azure Cognitive Services Speech API for voice recognition in Microsoft Azure Notebook. I have the code given from

MIcrosoft Guide: Link given Below

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-microphone?tabs=dotnet%2Cx-android%2Clinux%2Cjava-runtime&pivots=programming-language-python#sample-code

The code is:

import azure.cognitiveservices.speech as speechsdk

speech_key, service_region = "YourSubscriptionKey", "YourServiceRegion"
speech_config = speechsdk.SpeechConfig(subscription="XXXX", region="XXXX")

speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)

print("Say something...")

result = speech_recognizer.recognize_once()

if result.reason == speechsdk.ResultReason.RecognizedSpeech:
print("Recognized: {}".format(result.text))
elif result.reason == speechsdk.ResultReason.NoMatch:
print("No speech could be recognized: {}".format(result.no_match_details))
elif result.reason == speechsdk.ResultReason.Canceled:
cancellation_details = result.cancellation_details
print("Speech Recognition canceled: {}".format(cancellation_details.reason))
if cancellation_details.reason == speechsdk.CancellationReason.Error:
print("Error details: {}".format(cancellation_details.error_details))

I am getting following error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-15fab0a3387a> in <module>
      6 
      7 # Creates a recognizer with the given settings
----> 8 speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config)
      9 
     10 # Creates a speech synthesizer using the default speaker as audio output.

~/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech.py in __init__(self, speech_config, audio_config, language, source_language_config, auto_detect_source_language_config)
    795 
    796 
--> 797         self._impl = self._get_impl(impl.SpeechRecognizer, speech_config, audio_config, language, source_language_config, auto_detect_source_language_config)
    798 
    799     def recognize_once(self) -> SpeechRecognitionResult:

~/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech.py in _get_impl(reco_type, speech_config, audio_config, language, source_language_config, auto_detect_source_language_config)
    857         if language is None and source_language_config is None and auto_detect_source_language_config is None:
    858             if audio_config is None:
--> 859                 return reco_type._from_config(speech_config._impl)
    860             return reco_type._from_config(speech_config._impl,  audio_config._impl)
    861         if language is not None:

RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)
[CALL STACK BEGIN]

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1b72f8) [0x7f076f3f52f8]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x32ca98) [0x7f076f56aa98]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d15f2) [0x7f076f40f5f2]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d2596) [0x7f076f410596]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x328234) [0x7f076f566234]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d15f2) [0x7f076f40f5f2]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x1d2596) [0x7f076f410596]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x2f2e94) [0x7f076f530e94]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x265243) [0x7f076f4a3243]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x263892) [0x7f076f4a1892]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x263f8a) [0x7f076f4a1f8a]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x264386) [0x7f076f4a2386]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(+0x162675) [0x7f076f3a0675]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so(recognizer_create_speech_recognizer_from_config+0xe1) [0x7f076f3975c1]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x1cd7a5) [0x7f076fd497a5]
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/azure/cognitiveservices/speech/_speech_py_impl.so(+0x15bc0e) [0x7f076fcd7c0e]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x91) [0x56234e2ba921]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196f8b) [0x56234e341f8b]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196206) [0x56234e341206]
/home/nbuser/anaconda3_501/bin/python(_PyFunction_FastCallDict+0x3d7) [0x56234e342897]
/home/nbuser/anaconda3_501/bin/python(_PyObject_FastCallDict+0x26f) [0x56234e2badaf]
/home/nbuser/anaconda3_501/bin/python(_PyObject_Call_Prepend+0x63) [0x56234e2bfa73]
/home/nbuser/anaconda3_501/bin/python(PyObject_Call+0x3e) [0x56234e2ba7ee]
/home/nbuser/anaconda3_501/bin/python(+0x16aefb) [0x56234e315efb]
/home/nbuser/anaconda3_501/bin/python(+0x19d137) [0x56234e348137]
/home/nbuser/anaconda3_501/bin/python(_PyObject_FastCallDict+0x8b) [0x56234e2babcb]
/home/nbuser/anaconda3_501/bin/python(_PyObject_FastCallKeywords+0xaa) [0x56234e34248a]
/home/nbuser/anaconda3_501/bin/python(+0x19cf4e) [0x56234e347f4e]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x10c5) [0x56234e36d715]
/home/nbuser/anaconda3_501/bin/python(PyEval_EvalCodeEx+0x329) [0x56234e342cb9]
/home/nbuser/anaconda3_501/bin/python(PyEval_EvalCode+0x1c) [0x56234e343a4c]
/home/nbuser/anaconda3_501/bin/python(+0x1bf37b) [0x56234e36a37b]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x91) [0x56234e2ba921]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(_PyGen_Send+0x256) [0x56234e34af36]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x13b5) [0x56234e36da05]
/home/nbuser/anaconda3_501/bin/python(_PyGen_Send+0x256) [0x56234e34af36]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x13b5) [0x56234e36da05]
/home/nbuser/anaconda3_501/bin/python(_PyGen_Send+0x256) [0x56234e34af36]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x115) [0x56234e2ba9a5]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196f8b) [0x56234e341f8b]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196f8b) [0x56234e341f8b]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196206) [0x56234e341206]
/home/nbuser/anaconda3_501/bin/python(_PyFunction_FastCallDict+0x3d7) [0x56234e342897]
/home/nbuser/anaconda3_501/bin/python(_PyObject_FastCallDict+0x26f) [0x56234e2badaf]
/home/nbuser/anaconda3_501/bin/python(_PyObject_Call_Prepend+0x63) [0x56234e2bfa73]
/home/nbuser/anaconda3_501/bin/python(PyObject_Call+0x3e) [0x56234e2ba7ee]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x1abb) [0x56234e36e10b]
/home/nbuser/anaconda3_501/bin/python(+0x1964c6) [0x56234e3414c6]
/home/nbuser/anaconda3_501/bin/python(+0x1971cf) [0x56234e3421cf]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x10c5) [0x56234e36d715]
/home/nbuser/anaconda3_501/bin/python(+0x19fab4) [0x56234e34aab4]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x91) [0x56234e2ba921]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x19662e) [0x56234e34162e]
/home/nbuser/anaconda3_501/bin/python(+0x1971cf) [0x56234e3421cf]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x19fab4) [0x56234e34aab4]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x91) [0x56234e2ba921]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x19662e) [0x56234e34162e]
/home/nbuser/anaconda3_501/bin/python(+0x1971cf) [0x56234e3421cf]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x19fab4) [0x56234e34aab4]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x91) [0x56234e2ba921]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x19662e) [0x56234e34162e]
/home/nbuser/anaconda3_501/bin/python(_PyFunction_FastCallDict+0x1bc) [0x56234e34267c]
/home/nbuser/anaconda3_501/bin/python(_PyObject_FastCallDict+0x26f) [0x56234e2badaf]
/home/nbuser/anaconda3_501/bin/python(_PyObject_Call_Prepend+0x63) [0x56234e2bfa73]
/home/nbuser/anaconda3_501/bin/python(PyObject_Call+0x3e) [0x56234e2ba7ee]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x1abb) [0x56234e36e10b]
/home/nbuser/anaconda3_501/bin/python(_PyGen_Send+0x134) [0x56234e34ae14]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x115) [0x56234e2ba9a5]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196f8b) [0x56234e341f8b]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(PyEval_EvalCodeEx+0x6c8) [0x56234e343058]
/home/nbuser/anaconda3_501/bin/python(+0x198bd6) [0x56234e343bd6]
/home/nbuser/anaconda3_501/bin/python(PyObject_Call+0x3e) [0x56234e2ba7ee]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x1abb) [0x56234e36e10b]
/home/nbuser/anaconda3_501/bin/python(+0x19662e) [0x56234e34162e]
/home/nbuser/anaconda3_501/bin/python(_PyFunction_FastCallDict+0x1bc) [0x56234e34267c]
/home/nbuser/anaconda3_501/bin/python(_PyObject_FastCallDict+0x26f) [0x56234e2badaf]
/home/nbuser/anaconda3_501/bin/python(+0x2044b2) [0x56234e3af4b2]
/home/nbuser/anaconda3_501/bin/python(_PyObject_FastCallDict+0x8b) [0x56234e2babcb]
/home/nbuser/anaconda3_501/bin/python(+0x19cf4e) [0x56234e347f4e]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196f8b) [0x56234e341f8b]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196f8b) [0x56234e341f8b]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196f8b) [0x56234e341f8b]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196206) [0x56234e341206]
/home/nbuser/anaconda3_501/bin/python(+0x1971cf) [0x56234e3421cf]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(PyEval_EvalCodeEx+0x329) [0x56234e342cb9]
/home/nbuser/anaconda3_501/bin/python(PyEval_EvalCode+0x1c) [0x56234e343a4c]
/home/nbuser/anaconda3_501/bin/python(+0x1bf37b) [0x56234e36a37b]
/home/nbuser/anaconda3_501/bin/python(_PyCFunction_FastCallDict+0x91) [0x56234e2ba921]
/home/nbuser/anaconda3_501/bin/python(+0x19cdfc) [0x56234e347dfc]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(+0x196206) [0x56234e341206]
/home/nbuser/anaconda3_501/bin/python(+0x1971cf) [0x56234e3421cf]
/home/nbuser/anaconda3_501/bin/python(+0x19ced5) [0x56234e347ed5]
/home/nbuser/anaconda3_501/bin/python(_PyEval_EvalFrameDefault+0x2fa) [0x56234e36c94a]
/home/nbuser/anaconda3_501/bin/python(PyEval_EvalCodeEx+0x329) [0x56234e342cb9]
/home/nbuser/anaconda3_501/bin/python(+0x198b39) [0x56234e343b39]
/home/nbuser/anaconda3_501/bin/python(PyObject_Call+0x3e) [0x56234e2ba7ee]
/home/nbuser/anaconda3_501/bin/python(+0x20e2f7) [0x56234e3b92f7]
/home/nbuser/anaconda3_501/bin/python(Py_Main+0x316) [0x56234e3c3a16]
/home/nbuser/anaconda3_501/bin/python(main+0xee) [0x56234e28b75e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f0798620830]
/home/nbuser/anaconda3_501/bin/python(+0x1c847b) [0x56234e37347b]
[CALL STACK END]

**Comment by pankopon** [comment] 2020-06-15 03:11
Hi, thank you for the report and sorry about the trouble. This is a known issue, and we have a backlog item for Python support for Azure functions but no definite schedule yet. Please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/437 for discussion on possible workarounds.

**Comment by pankopon** [comment] 2020-06-15 03:11
Closed as duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/437.

**Closed by pankopon** 2020-06-15 03:11 UTC

**Comment by JacoLin** [comment] 2020-08-20 07:36
// Creates an instance of a speech config with specified subscription key and service region.
    // Replace with your own subscription key and service region (e.g., "westus").
    auto speechConfig = SpeechConfig::FromSubscription("XXXXXXXXXXXXXXXXXXXXXXX", "eastasia");     

    auto sourceLanguageConfig = SourceLanguageConfig::FromLanguage("zh-TW");
    auto audioConfig = AudioConfig::FromDefaultMicrophoneInput();  
  
    // Creates a speech recognizer.

    auto recognizer = SpeechRecognizer::FromConfig(speechConfig, sourceLanguageConfig, audioConfig);  <------RuntimeError: Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)    
    cout << "Say something...\n";
..............
........

My Microphone works very well in JavaScript SDK Sample code with Chrome or Edge Browser, but in the C++ WIN, program code is always NG as above.

PC: Lenovo ThinkPad Notebook (Core i7 8th Gen)
OS: Win10 x64 professional 1909
Development tool: Visual Studio C++ 2019 professional

**Comment by pankopon** [comment] 2020-08-25 00:41
@JacoLin Please open a new issue on any new questions, I only happened to check this closed item by accident... However, if you are going to use the default microphone then you don't need AudioConfig. Can you please try the basic quickstart (C++/Windows) below, does it not work for you?
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/windows/from-microphone

**Comment by JacoLin** [comment] 2020-08-25 10:23
@pankopon  thanks for your reply,   
 I marked the default microphone setting, it doesn't work and get the exception code  SPXERR_MIC_NOT_AVAILABLE.  I guess it is related to antivirus software, but I can't make sure now.   I will get a pure window10 environment without any antivirus software to test this.

**Comment by mikekistler** [comment] 2021-07-22 16:27
I hit this problem in devdivcodingdays

**Comment by Minxiangliu** [comment] 2021-11-05 06:59
> @pankopon thanks for your reply, I marked the default microphone setting, it doesn't work and get the exception code SPXERR_MIC_NOT_AVAILABLE. I guess it is related to antivirus software, but I can't make sure now. I will get a pure window10 environment without any antivirus software to test this.

I can use it normally after I turn off the antivirus software.

**Comment by JacoLin** [comment] 2021-11-05 08:18
> > @pankopon thanks for your reply, I marked the default microphone setting, it doesn't work and get the exception code SPXERR_MIC_NOT_AVAILABLE. I guess it is related to antivirus software, but I can't make sure now. I will get a pure window10 environment without any antivirus software to test this.
> 
> I can use it normally after I turn off the antivirus software.

Yes, you are right. I have determined and must turn off the anti-virus software to be able to use.
turn off antivirus software to use this function , I think that's not a good idea.
