### ISSUE TITLE
Azure TTS pronounces prices and other decimal numbers incorrectly in Spanish

### ISSUE THREAD

**Issue by fabswt** [Azure-Samples/cognitive-services-speech-sdk#1945] opened 2023-05-09 16:39 UTC
**Describe the bug**

Azure TTS pronounces prices and other decimal numbers incorrectly in Spanish.

**To Reproduce**

I got this using the REST API but the issue is the same using Voice Gallery, so:

1. Go to Voice Gallery on speech.microsoft.com
2. Create a new piece of content with text `€2,75` (Tried with es-ES-AbrilNeural but same with other voices.)
3. Press the Play button

**Expected behavior**

Take this Spanish text:

> €2,75

e.g.:

> Su café negro costará €2,75.

Expected: It should be pronounced:

> dos euros con setenta y cinco (centimos)

Observed: instead, it's being pronounced as:

> dos coma siete cinco euros

This is not limited to prices: try `3,14`. It gets pronounced as a meaningless "tres coma uno cuatro" while it should be "tres coma catorce".

**Version of the Cognitive Services Speech SDK**
Irrelevant. But observed today May 9th, 2023.

**Platform, Operating System, and Programming Language**
Irrelevant.

**Additional context**

Building a chatbot for learning languages. This kind of mistake is a major issue.

**Comment by ForrestGumb** [comment] 2023-05-10 04:07
Will improve currency reading on es-ES and es-MX. Plan to be fixed on 2023/06/02.
For "3,14", it's by design. The readout will be consistent with other input like "3,141" "3,1415".

**Comment by fabswt** [comment] 2023-05-10 09:40
It's not much better for French:

> Très bien, ça fait 2,50 euros alors.

Observed: `2,50` is being pronounced as "deux virgule cinquante euros". It's not completely incorrect, but it's awkward.
Expected: "deux euros cinquante".

**Comment by yulin-li** [comment] 2023-05-29 15:11
@ForrestGumb could you please help to check the latest comment about French?

**Comment by pankopon** [comment] 2023-07-10 20:55
@ForrestGumb Any update on the status?

**Comment by Kerry-LinZhang** [comment] 2023-07-19 03:00
follow up the left issue reported with:

Observed: 2,50 is being pronounced as "deux virgule cinquante euros". It's not completely incorrect, but it's awkward.
Expected: "deux euros cinquante".

@ForrestGumb do we have any plan for the fix?

**Comment by ForrestGumb** [comment] 2023-07-19 03:03
We've fixed currency reading issue on es-ES-ElviraNeural, es-ES-AlvaroNeural voce.
Now, 
€2,75 read as "dos euros con setenta y cinco céntimos".
€2,50 read as "dos euros con cincuenta céntimos".

TTS team fix issue on hero voices first, then on other voices. You can find TTS voice list here https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts. In each locale, voice listed in top is hero voices.

**Comment by ForrestGumb** [comment] 2023-07-19 03:14
@fabswt, For French I tried fr-FR-DeniseNeural and fr-FR-HenriNeural.
"€2,50" read as "deux euros cinquante" as you expected.
On which voice do you found this issue?

**Comment by Kerry-LinZhang** [comment] 2023-07-19 03:45
Hi @fabswt which voice did you tried when encounter the issue case, could you please double check it again?

**Comment by M-Hietala** [comment] 2023-10-04 14:31
Closing this one as not commented in a while.

**Closed by M-Hietala** 2023-10-04 14:31 UTC
Labels: bug, text-to-speech, accepted, service-side issue
