### ISSUE TITLE
Is there any way to transcribe all audios in a blob folder at once?

### ISSUE THREAD

**Issue by tuanle07** [Azure-Samples/cognitive-services-speech-sdk#554] opened 2020-03-18 01:37 UTC
Currently, we have to send several transcription requests to the REST Api for each blob file. Is there a way to do it in batch? For example, sending a transcription request for all blobs in a folder? Thanks.

**Comment by wolfma61** [comment] 2020-03-19 06:49
we are working on a new API version that will entail this feature. Unfortunately it is still a few weeks out...

Wolfgang

**Comment by tuanle07** [comment] 2020-03-19 08:22
> we are working on a new API version that will entail this feature. Unfortunately it is still a few weeks out...
> 
> Wolfgang

@wolfma61 : thanks for your reply. Please keep me updated on this as soon as the API becomes available! :)

**Comment by harmandeepsinghkalsi** [comment] 2020-05-13 05:22
I think we have batch transcription in place for that @tuanle07

**Comment by tomaszpe** [comment] 2020-05-14 14:25
Guys, how about using this example solution: https://github.com/rlagh2/callcenteranalytics?
BTW: has anyone tried to run this? I got multiple errors when trying to run it.

**Comment by tuanle07** [comment] 2020-05-14 14:30
@harmandeepsinghkalsi : is there any documentation for that? Thanks

**Comment by tomaszpe** [comment] 2020-05-14 14:31
only on GitHub; I didn't find anything outside.

**Comment by tuanle07** [comment] 2020-05-14 14:35
@tomaszpe : I don’t think bulk folder transcription is supported yet thou.

**Comment by tuanle07** [comment] 2020-05-14 14:36
@wolfma61 : Hi Wolfgang, any news on the new API? Thanks

**Comment by wolfma61** [comment] 2020-05-14 14:56
at the earliest next week ...

**Comment by harmandeepsinghkalsi** [comment] 2020-05-15 02:36
@tuanle07 - Actually the article at github is kind of mocking the batch scenario by getting all the files at once and then looping over it one by one and doing post call. V2.0 does not support batch transcription yet. I don't know why it was called batch transcription though ?

**Comment by harmandeepsinghkalsi** [comment] 2020-05-15 02:37
@tomaszpe I ran that example, it works fine for me. Please let me know what errors are you getting?

**Comment by wolfma61** [comment] 2020-05-15 06:55
it is called 'batch' because you submit the job, and collect the results later...
like in the good old days of punch cards (yes, I'm old)

but we soon will be allow you to submit a bunch (or batch) of files ;)

**Comment by tomaszpe** [comment] 2020-05-15 14:17
@harmandeepsinghkalsi - for example, after opening the sln file I have 35 Intellisense errors. When I enter the required info about storage, keys etc - I have the following note: 
![image](https://user-images.githubusercontent.com/9729598/82060126-39c39a00-96c7-11ea-88a3-a43a396529b4.png)
and the error from build: error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)
I'm a novice in development so it's hard to me find out the cause.
If you are able to help I'll be more than grateful :)
Otherwise I don't want you to spend too much time on it.

**Comment by harmandeepsinghkalsi** [comment] 2020-05-15 14:28
I also faced the same error  @tomaszpe . Did you first clone to local and opened it in VS? If yes , try cloning the project directly from repository in VS . There is an option , to clone from repository when you open VS. Please try this and then check if all the needed packages are installed or not.

**Comment by tomaszpe** [comment] 2020-05-15 17:36
@harmandeepsinghkalsi  - I did as you suggested: cloned from a repo when I open VS. Cloning was successful:
![image](https://user-images.githubusercontent.com/9729598/82079518-4229ce00-96e3-11ea-9248-759b987a270d.png)
However, I got still 35 errors and the same message as above and I'm stuck :(
Any ideas are welcome.

**Comment by tomaszpe** [comment] 2020-05-15 18:17
@harmandeepsinghkalsi - update;partial success :). I checked packages, installed updates and after that there was only 1 error - screenshot below:
![image](https://user-images.githubusercontent.com/9729598/82082865-0c87e380-96e9-11ea-9973-d411d9d0505b.png)
Any hints what to do next?

**Comment by harmandeepsinghkalsi** [comment] 2020-05-15 19:46
What is the version of CsvHelper you installed? Install 12.1.2 and check

**Comment by tomaszpe** [comment] 2020-05-18 07:58
Hi @harmandeepsinghkalsi - I have 15.0.5. Should I revert back to 12.1.2 and check then? Below is the screen with packages I have
![image](https://user-images.githubusercontent.com/9729598/82188382-162e6880-98ee-11ea-82d9-01a6e83777b2.png)

**Comment by harmandeepsinghkalsi** [comment] 2020-05-18 08:00
Yes please revert to 12.1.2 and check once. I am hoping it should resolve the error.

**Comment by tomaszpe** [comment] 2020-05-18 08:10
@harmandeepsinghkalsi  Magic happened, thank you :) I'm step forward. However... it cannot validate subscription. Here's the screen

**Comment by tomaszpe** [comment] 2020-05-18 08:11
@harmandeepsinghkalsi once again the screen: 
![image](https://user-images.githubusercontent.com/9729598/82189535-d7011700-98ef-11ea-8639-ed60eb3a3590.png)
My subs is Active, this is for sure. Did I write something wrong when pasting info about storage , keys etc?

**Comment by harmandeepsinghkalsi** [comment] 2020-05-18 08:28
It is good that process started atleast. Error states that there could be multiple reasons for the issue. 
1. Subscription active - Yes
2. You regenerated subs key -- update it in the subscription page. 
3. If subscription is new -- wait for 15 minutes

If all of the above is fine . Please verify once the subscription **Speech_SubscriptionKey** only.

Need to see what you are providing before giving suggestions.

**Comment by tomaszpe** [comment] 2020-05-18 08:55
@harmandeepsinghkalsi here's the screen with what I provide
![image](https://user-images.githubusercontent.com/9729598/82193326-8a203f00-98f5-11ea-8c42-5d644a81d8f0.png)
I also regenerated Speech subscription key. What now?

**Comment by harmandeepsinghkalsi** [comment] 2020-05-18 09:17
Configuration looks good to me . 
As mentioned in the error, if you regenerated the subscription , you should update it on the subscription page(need to check where to update, I am not sure about that) .

Can you try one thing? Hit the below URL from the postman and try once , if it work for you 

**POST**: https://northeurope.cris.ai/api/speechtotext/v2.0/transcriptions

**Request Body:** 

```
{
    "results": [],
    "recordingsUrl": "<Provide the blob SAS URL>",
    "models": []
    "locale": "en-US",
    "name": "Bulk transcription",
	    "properties": {
        "PunctuationMode": "DictatedAndAutomatic",
        "ProfanityFilterMode": "Masked",
        "AddWordLevelTimestamps": "False",
        "AddSentiment": "False",
       "TranscriptionResultsContainerUrl": <Provide the container SAS Url>(Optional)
    }
}
``` 

Please provide the subscription key is the headers.
Ocp-Apim-Subscription-Key: <Your subscription key>

Check if it works fine for you or the same error exists.

**Comment by tomaszpe** [comment] 2020-05-18 11:17
@harmandeepsinghkalsi Thanks for the code! I only changed Content-Type to "media/wav", not text/plain. The results:
![image](https://user-images.githubusercontent.com/9729598/82207143-a62ddb80-9909-11ea-94b1-57fa3725237c.png)
I tried here with both wav and mp3 files - the result was a above
I changed the endpoint to the one I have in my subscription and it seems to work:
![image](https://user-images.githubusercontent.com/9729598/82207268-d6757a00-9909-11ea-81e8-80092a1206c2.png)
When I tried this setup with VS - I got the following message:
![image](https://user-images.githubusercontent.com/9729598/82207316-ebeaa400-9909-11ea-8eb9-9be9e159da8d.png)
Any ideas here?

**Comment by harmandeepsinghkalsi** [comment] 2020-05-18 11:24
@tomaszpe  Can we have a working session ?

**Comment by tomaszpe** [comment] 2020-05-18 11:35
@harmandeepsinghkalsi sure. When are you available? I'm available now, for example. How can we connect? I can send a Teams or Zoom invite if you send me your email.

**Comment by harmandeepsinghkalsi** [comment] 2020-05-19 18:33
@tomaszpe : Answering your queries:
1. The media type should be **application/json**
2. I see the POST URL is not what I said to use . Please use this **https://northeurope.cris.ai/api/speechtotext/v2.0/transcriptions**
3. The **recordingsUrl** is not correct . You are passing the StorageConnectionString , but it needs the url of the audio blob. You can get that by right clicking the blob and Generate SAS URL.
4. Also the **TranscriptionResultsContainerUrl** is not correct. Again you need to pass the SAS URL.  To get that ,under your storage service , go to **Storage Explorer (preview) -> BLOB CONTAINERS -> Right click your container and generate the SAS URL.**

**Comment by tomaszpe** [comment] 2020-05-20 08:56
Hi @harmandeepsinghkalsi . I did what you said and have the following error:
![image](https://user-images.githubusercontent.com/9729598/82426430-224e2d80-9a88-11ea-94f4-951d4c1378e0.png)
When I move over the red cros on the left I have the message: Expected < ',' instead of ' " '>
I found the following info on Stackoverflow: https://stackoverflow.com/questions/55512856/how-to-use-batch-transcription-api-through-python but I don't if this has any use here.
I'll appreciate your help.

**Comment by harmandeepsinghkalsi** [comment] 2020-05-20 09:30
@tomaszpe after "models": [] , there should be ','(comma)

Also put TranscriptionResultsContainerUrl in ""(double-quotes)

**Comment by tomaszpe** [comment] 2020-05-20 09:59
@harmandeepsinghkalsi - I corrected and now there is no error in code it seems. However, I got the same error as in the VS: 
![image](https://user-images.githubusercontent.com/9729598/82432982-13b84400-9a91-11ea-824c-4cabaaa9d27f.png)
My subscription is Active - as below
![image](https://user-images.githubusercontent.com/9729598/82433096-3e0a0180-9a91-11ea-98e6-f7001c1592a9.png)
I really don't know where is the issue.

**Comment by harmandeepsinghkalsi** [comment] 2020-05-20 11:19
What was the postman result ?
Also you need **speech to text** service and **text analytics** service for this code to run .

**Comment by tomaszpe** [comment] 2020-05-20 11:30
@harmandeepsinghkalsi that was the result from Postman:
![image](https://user-images.githubusercontent.com/9729598/82441102-b8408300-9a9d-11ea-830f-15a300c48066.png)
As for the Cognitive service - yes, I have it up and running (both for S2T and text analytics) for the app in VS.
But even with Postman it didn't work :(. Somewhere I have trouble with subs validation

**Comment by harmandeepsinghkalsi** [comment] 2020-05-20 12:45
What are you passing in the headers? 

You should take the key from **Keys and Endpoints** under your S2T service . Take any key (Key 1 or Key2) . You should pass that key in Headers as **ocp-apim-subscription-key**. Are you giving this key or the subscription key you showed in the screenshot above. Please check once!

![image](https://user-images.githubusercontent.com/10211042/82447026-4a0fb680-9ac5-11ea-8305-2dbf25ffe9ba.png)

**Comment by tomaszpe** [comment] 2020-05-20 14:50
@harmandeepsinghkalsi I think I got the reason! I had my subs for Cognitive Services with Pricing Tier "Free" and not "Standard". I changed it for Standard, waited 15 mins and got the result :)
![image](https://user-images.githubusercontent.com/9729598/82460194-2b0b2780-9ab9-11ea-80db-f89f14f7d53b.png)
The code executed was the following:
![image](https://user-images.githubusercontent.com/9729598/82460422-6ad20f00-9ab9-11ea-9ac8-e222a56c8392.png)
Now I'll clone repo in a clear VS, put appropriate keys/info and we'll see. Keep fingers crossed!

**Comment by harmandeepsinghkalsi** [comment] 2020-05-20 15:06
Great! It worked for you .

**Comment by tomaszpe** [comment] 2020-05-20 15:25
@harmandeepsinghkalsi it works just fine with VS now! Thank you very much for your time, help and patience :) Consider solved!

**Comment by harmandeepsinghkalsi** [comment] 2020-05-20 15:29
Awesome News! Happy Learning !

**Comment by pankopon** [comment] 2020-06-13 00:59
Closing the issue as a solution was provided.

**Closed by pankopon** 2020-06-13 00:59 UTC

**Comment by tuanle07** [comment] 2020-06-19 05:14
@pankopon : why was this issued marked as closed? 
@wolfma61 : any updates on this feature pls? Thanks.

**Comment by pankopon** [comment] 2020-06-20 03:52
@tuanle07 I mistook the conclusion above for a usable solution, sorry about that. But the API v3.0 is now available as well, is this what you were looking for?
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/batch-transcription

> With the new v3.0 API, you have the choice of transcribing one or more audio files, or process a whole storage container.

**Comment by tuanle07** [comment] 2020-06-20 04:06
@pankopon : Thanks. This is what I’m looking for. One more question, is there a way to transcribe all blobs in a specific folder in a container instead of transcribing the whole container?
