### ISSUE TITLE
Windows 11 Language Service status code 400

### ISSUE THREAD

**Issue by svaidyansfb** [Azure-Samples/cognitive-services-speech-sdk#1853] opened 2023-02-27 12:40 UTC
**Describe the bug**
On running the python version of the call-center scenario, I am getting a 400 http status code exception:

Exception: The POST request to https://***.cognitiveservices.azure.com//language/analyze-conversations/jobs?api-version=2022-05-15-preview returned a status code 400 that was not in the expected status codes: [<HTTPStatus.ACCEPTED: 202>]

**To Reproduce**
1.  Create Speech Service and Language Service components (after getting approval from CS Gate team).
2.  Clone repo "git clone https://github.com/Azure-Samples/cognitive-services-speech-sdk.git".
3.  Run "scenarios\python\console\call-center>python call_center.py with required arguments of speech and language services".
4.  This results in an exception getting raised with "a status code 400 that was not in the expected status code".

**Expected behavior**
Language service output as a json file with readacted PII and confidence scores, summarization, etc.

**Version of the Cognitive Services Speech SDK**
azure-cognitiveservices-speech 1.25.0

**Platform, Operating System, and Programming Language**
 - Windows 11
 - x64 (intel CORE i5)
 - Programming language: Python
 - Running in command line

**Additional context**

**Comment by goergenj** [comment] 2023-02-27 22:45
It looks to me that the issue is the "//" in the URI.

_Exception: The POST request to https://***.cognitiveservices.azure.com **//** language/analyze-conversations/jobs?api-version=2022-05-15-preview returned a status code 400 that was not in the expected status codes: [<HTTPStatus.ACCEPTED: 202>]_

We will file a PR to fix this. Meanwhile you should be able to fix this locally.

**Comment by goergenj** [comment] 2023-02-28 16:55
Adding @ut-karsh fyi and follow-up.

**Comment by ut-karsh** [comment] 2023-02-28 17:54
Hi @svaidyansfb, could you please confirm whether the fix above works for you?

**Comment by vaidya-ti** [comment] 2023-03-02 04:20
Thanks for the follow-up @pankopon and @ut-karsh.  Please let me know how to fix the auto generated post request locally.

**Comment by pankopon** [comment] 2023-03-04 00:35
@vaidya-ti My guess is to try changing
```
CONVERSATION_ANALYSIS_PATH = "/language/analyze-conversations/jobs";
```
to
```
CONVERSATION_ANALYSIS_PATH = "language/analyze-conversations/jobs";
```
in `call_center.py`. @ut-karsh may confirm.

**Comment by ut-karsh** [comment] 2023-03-07 21:09
Yes, please change the post request to https://***.cognitiveservices.azure.com/language/analyze-conversations/jobs?api-version=2022-05-15-preview. @svaidyansfb / @vaidya-ti could you please confirm that this fixed it for you?

**Comment by ut-karsh** [comment] 2023-05-03 20:31
@vaidya-ti additionally, assuming you have access to the gated preview, please use the latest API version as mentioned in the sample here: https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/summarization/quickstart?pivots=rest-api&tabs=conversation-summarization%2Cwindows#example-request

**Comment by pankopon** [comment] 2023-05-23 02:52
Closed as resolved since no further updates, please open a new issue if more support is needed.

**Closed by pankopon** 2023-05-23 02:52 UTC
Labels: in-review, Rest API
