### ISSUE TITLE
Not able run the SSML with background audio.

### ISSUE THREAD

**Issue by pmanvi** [Azure-Samples/cognitive-services-speech-sdk#1420] opened 2022-02-21 13:19 UTC
**Describe the bug**

The moment we include background audio
Ex:
val synthesizer = SpeechSynthesizer(speechConfig, null)
val result = synthesizer.SpeakSsml("""<speak version="1.0" xml:lang="en-US" xmlns:mstts="http://www.w3.org/2001/mstts">
   <mstts:backgroundaudio src="https://actions.google.com/sounds/v1/crowds/battle_crowd_celebration.ogg" volume="0.7" fadein="3000" fadeout="4000"/>
   <voice name="Microsoft Server Speech Text to Speech Voice (en-US, JennyNeural)">
    Hello! see this background message being played ... it just runs along with our text, you can here crowd celebration voice
 </voice>
 </voice>""".trimIndent()

val httpHeaders = HttpHeaders()
httpHeaders.cacheControl = CacheControl.noCache().headerValue
println("${result.audioData.size}")
val response = ResponseEntity<Any?>(InputStreamResource(ByteArrayInputStream(result.audioData)), httpHeaders, HttpStatus.OK)

Please note that above ssml with background message works fine with azure portal.

**To Reproduce**
1.  Execute the above code (we tried both with free tier and standard subscription)
2. We would

**Expected behavior**
We should be able to listen to voice with background message

**Version of the Cognitive Services Speech SDK**
implementation(group= "com.microsoft.cognitiveservices.speech", name= "client-sdk", version= "1.18.0", ext= "jar")
   
**Platform, Operating System, and Programming Language**
 - OS: Mac
 - Hardware - x64, x86, ARM, ...
 - Programming language: Java (Kotlin)
 - Browser - NA

**Additional context**
 - No errors message Error messages, stream returns '0' byte
- No log message seen in SDK

**Comment by trrwilson** [comment] 2022-02-25 19:35
@yulin-li can you comment on the expected behavior with `<mstts:backgroundaudio/>`? I'd actually never seen this extension before!

**Comment by yulin-li** [comment] 2022-02-28 07:57
Hi @pmanvi thanks for reaching out, I checked your SSML, looks it's incomplete.

You can follow the[doc](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#add-background-audio) to add `<speak>` tag.

I modified your SSML and the following works.

```xml
<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">
<mstts:backgroundaudio src="https://actions.google.com/sounds/v1/crowds/battle_crowd_celebration.ogg" volume="0.7" fadein="3000" fadeout="4000"/>
<voice name="en-US-JennyNeural">Hello! see this background message being played ... it just runs along with our text, you can here crowd celebration voice
</voice></speak>
```

**Comment by pankopon** [comment] 2022-04-19 00:53
Closed as resolved, please open a new issue if more support is needed.

**Closed by pankopon** 2022-04-19 00:53 UTC
Labels: pending close

**Comment by johnmalatras** [comment] 2022-05-10 20:51
Hi @pankopon and @yulin-li - this still seems to be broken. The example that @yulin-li posted above does not include any background audio when I submit it.
