### ISSUE TITLE
Android run into 0x21 (SPXERR_INVALID_HANDLE)

### ISSUE THREAD

**Issue by hannesa2** [Azure-Samples/cognitive-services-speech-sdk#2110] opened 2023-10-20 06:09 UTC
In my Android arm64 device I run often into

```
E  FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.bmwgroup.unreal.grumpycat, PID: 54043
    java.util.concurrent.ExecutionException: java.lang.RuntimeException: Exception with an error code: 0x21 (SPXERR_INVALID_HANDLE)
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.carcontrol.service.stt.SpeechToTextService.startRecord(SpeechToTextService.kt:85)
        at com.carcontrol.service.ws.WebSocketService$listenToMicro$1.invokeSuspend(WebSocketService.kt:302)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f9a9442, Dispatchers.Default]
        Caused by: java.lang.RuntimeException: Exception with an error code: 0x21 (SPXERR_INVALID_HANDLE)
        at com.microsoft.cognitiveservices.speech.util.Contracts.throwIfFail(Unknown Source:46)
        at com.microsoft.cognitiveservices.speech.RecognitionResult.<init>(Unknown Source:36)
        at com.microsoft.cognitiveservices.speech.SpeechRecognitionResult.<init>(Unknown Source:0)
        at com.microsoft.cognitiveservices.speech.SpeechRecognizer$1$1.run(Unknown Source:12)
        at com.microsoft.cognitiveservices.speech.Recognizer.doAsyncRecognitionAction(Unknown Source:14)
        at com.microsoft.cognitiveservices.speech.SpeechRecognizer$1.call(Unknown Source:10)
        at com.microsoft.cognitiveservices.speech.SpeechRecognizer$1.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

Does someone has an idea how to get rid of it ?

**Comment by jpalvarezl** [comment] 2023-10-20 09:29
Hi @hannesa2, unfortunately there is not enough context currently provided in the description, for us to be able to help you. In order to be able to more effectively assist you, could you provide the following:

- SDK version
- Brief description of what you are attempting (Speech to text, text to speech, etc.)
- Logs ([here](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging#android) are some instructions on how to extract logs from the SDK in Android)
- Details on the environment you are running (Android? If so which OS version?)

Thank you very much!

**Comment by hannesa2** [comment] 2023-10-20 15:31
I use `api "com.microsoft.cognitiveservices.speech:client-sdk:1.32.1"` 
and I do a SST and often I run with this code

        speechConfig =  SpeechConfig.fromSubscription("<My secret>", "westeurope")
        destroyMicrophoneStream()
        microphoneStream = MicrophoneStream()

        SpeechRecognizer(speechConfig, AudioConfig.fromStreamInput(MicrophoneStream.create()))
        val resultText = speechRecord.recognizeOnceAsync().get().text

into the given error. 
I use Android 13 on arm64
Sorry,this is all I know

**Comment by chschrae** [comment] 2023-10-23 18:13
Hi @hannesa2  I am unable to reproduce your error, can you gather a log using this:
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-use-logging
Also it could be something related to the MicrophoneStream you are using in relation to the lifetime of the stream. I see you are calling create from within the constructor. Can you call create and assign it to a variable to make sure it is kept alive?

**Closed** 2023-11-06 18:21 UTC
Labels: pending close
