### ISSUE TITLE
Some methods that cannot use conversation normally

### ISSUE THREAD

**Issue by lenqing6** [Azure-Samples/cognitive-services-speech-sdk#1564] opened 2022-07-07 10:03 UTC
Describe the bug
I want to use the function of removing the specified participant, but it does not take effect after executing the method

Call the createconversationasync method and store the conversation in memory. After a few minutes, call some methods of conversation, such as removeparticipantasync, muteallparticipantsasync Neither error reporting nor effectiveness;

Expected behavior
Conversation can be created.

Version of the Cognitive Services Speech SDK
1.21.0

Platform, Operating System, and Programming Language

OS: Windows 11
Hardware - x64
Programming language: java

**Comment by jhakulin** [comment] 2022-07-08 14:23
@lenqing6 Thanks for the report, could you please provide a log based on the instructions here ? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging. That would help us to understand better what happens.

**Comment by lenqing6** [comment] 2022-07-11 01:41
@jhakulin Thank you for your reply.The error I got through the log is returned.
[88405]: 369214ms SPX_THROW_HR_IF:  speechapi_c_conversation.cpp:51 (0x005) = 0x5
[88405]: 369296ms SPX_TRACE_ERROR:  exception.cpp:119 About to throw Exception with an error code: 0x5 (SPXERR_INVALID_ARG) 
[CALL STACK BEGIN]

    > conversation_update_participant

    - 00000000032F1DF0 (SymFromAddr() error: The specified module cannot be found.)



[CALL STACK END]


[88405]: 369296ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:106 CSpxHandleTable::TrackHandle p=0x0000000038ACA780
[88405]: 369296ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:116 CSpxHandleTable::TrackHandle class=ExceptionWithCallStack, h=0x0000000038ACA780, p=0x0000000038ACA780, tot=1
[88405]: 369296ms SPX_RETURN_ON_FAIL:  speechapi_c_conversation.cpp:55 hr = 0x38aca780
[88405]: 376506ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:175 CSpxHandleTable::StopTracking(h) h=0x0000000038ACA780
[88405]: 376506ms SPX_DBG_TRACE_VERBOSE:  handle_table.h:190 CSpxHandleTable::StopTracking(h) class=ExceptionWithCallStack, h=0x0000000038ACA780, p=0x0000000038ACA780, tot=0
[976096]: 376515ms SPX_TRACE_VERBOSE:  web_socket.cpp:97 Message sent. Success=1, Type=1, Size=196 B, Time=2022-07-11T01:31:45.6232321Z, TimeInQueue=5 ms

**Comment by lenqing6** [comment] 2022-07-11 06:55
[841113]: 1464326ms SPX_TRACE_VERBOSE:  web_socket.cpp:97 Message sent. Success=1, Type=1, Size=196 B, Time=2022-07-11T06:53:10.6143987Z, TimeInQueue=13 ms
The event was successfully issued but the operation was not performed

**Comment by lenqing6** [comment] 2022-07-12 02:54
@ralph-msft Thank you for your reply.
[samTest.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9089022/samTest.log)
Line 220 of the log is the conversation removeparticipantasync method, which was successfully executed but did not respond correctly.

Line 221 of the log is the conversation mutepartitionasync method, which was successfully executed and received the correct return.

Line 225 of the log is the conversation unmutepartitionasync method, which was successfully executed and received the correct return.

The problem is 220 lines.

**Comment by ralph-msft** [comment] 2022-07-12 03:54
Thanks for sharing the logs.

A few more questions for you:
* Are you calling .get() on the futures returned from your calls to ...async() methods? From the logs it looks like you are attempting to start transcriptions before the join has completed. For example:
```Java
conversationTranslator.joinConversationAsync(conversation, "the host").get();
conversationTranslator.startTranscribingAsync().get();
```
* How many guests are joining the conversation?
* Which guest are you attempting to remove from the conversation? Are you using the participant ID to remove guests? It is not possible to remove the host from the conversation.
* Could you please share the minimum code that reproduces your issue? This should include the code for the host that creates the conversation, the code for any guests joining the conversation, as well as the logs for both the host and client.

**Comment by lenqing6** [comment] 2022-07-12 07:05
![image](https://user-images.githubusercontent.com/96234501/178429410-ff0f1c84-1033-4a6b-8cd7-81dcb93ebfc9.png)

**Comment by lenqing6** [comment] 2022-07-12 09:16
`  private String createConversationAsync() throws ExecutionException, InterruptedException {

        // Replace these values with the details of your Cognitive Speech subscription

        String subscriptionKey = "subscriptionKey";

        // Replace below with your region identifier from here: https://aka.ms/speech/sdkregion
        String region = "southeastasia";

        // Sets source and target languages.
        // Replace with the languages of your choice, from list found here: https://aka.ms/speech/sttt-languages
        String fromLanguage = "en-US";

        // Set this to the display name you want for the conversation host
        String displayName = "The host";

        // Set audio format
        long samplesPerSecond = 16000;
        short bitsPerSample = 16;
        short channels = 8;
        List<String> targetLanguage = Arrays.asList("ja-JP", "en-US", "zh-TW");

        // Create the push stream
        PushAudioInputStream pushStream = AudioInputStream.createPushStream(AudioStreamFormat.getWaveFormatPCM(samplesPerSecond, bitsPerSample, channels));
        AudioConfig audioInput = AudioConfig.fromStreamInput(pushStream);

        // Create an instance of the speech translation config
        var config = SpeechTranslationConfig.fromSubscription(subscriptionKey, region);
        config.setSpeechRecognitionLanguage(fromLanguage);
        config.addTargetLanguage("ja-JP");
        config.addTargetLanguage("zh-CN");
        config.addTargetLanguage("en-US");

        // Create the conversation
        var conversation = Conversation.createConversationAsync(config).get();
        // Start the conversation so the host user and others can join
        conversation.startConversationAsync();

        // Get the conversation ID. It will be up to your scenario to determine how this is shared with other participants.
        String conversationId = conversation.getConversationId();
        System.out.println("Created " + conversationId + " conversation");

        // At this point, you can use the conversation object to manage the conversation.
        // For example, to mute everyone else in the room you can call this method:
        //conversation.muteAllParticipantsAsync();

        // Configure which audio source you want to use. If you are using a text only language, you
        // can use the other overload of the constructor that takes no arguments
        //       var audioConfig = AudioConfig.fromDefaultMicrophoneInput();
        var conversationTranslator = new ConversationTranslator(audioInput);
        // You should connect all the event handlers you need at this point
        conversationTranslator.sessionStarted.addEventListener((s, e) ->
        {
            System.out.println("Session started: " + e.getSessionId());
            System.out.println(e);

        });

        conversationTranslator.participantsChanged.addEventListener((s, e) ->
        {
            System.out.println("The following participant(s) have");
            switch (e.getReason()) {
                case JoinedConversation:
                    if (Objects.equals(e.getParticipants().get(0).getDisplayName(), "the user")){
                        conversation.muteParticipantAsync(e.getParticipants().get(0).getId());
                    }
                        System.out.println("joined");
                    break;
                case LeftConversation:
                    System.out.println("left");
                    break;
                case Updated:
                    if (Objects.equals(e.getParticipants().get(0).getDisplayName(), "the user")){
                        conversation.removeParticipantAsync(e.getParticipants().get(0).getId());
                    }
                    System.out.println("been updated");
                    break;
            }
            System.out.println(":");


            for (Participant participant : e.getParticipants()) {
                System.out.println(participant.getDisplayName());

            }
        });
        /*conversationTranslator.textMessageReceived.addEventListener((s, e) ->
        {
            System.out.println("Received an instant message from " + e.getResult().getParticipantId() + ": '{e.Result.Text}'");
            for (Map.Entry<String, String> entry : e.getResult().getTranslations().entrySet()) {

                System.out.println("Received an instant message from " + entry.getKey() + ": " + entry.getValue() + "");

            }
        });*/
        conversationTranslator.transcribed.addEventListener((s, e) ->
        {
            System.out.println("Received a transcription from " + e.getResult().getParticipantId() + ": " + e.getResult().getText() + "");
            for (Map.Entry<String, String> entry : e.getResult().getTranslations().entrySet()) {

                System.out.println("Translated into " + entry.getKey() + ": " + entry.getValue() + "");
                conversationTranslator.sendTextMessageAsync(entry.getKey() + ": " + entry.getValue() + "");

            }
        });
        /*conversationTranslator.transcribing.addEventListener((s, e) ->
        {
            System.out.println("Received a partial transcription from " + e.getResult().getParticipantId() + ": " + e.getResult().getText() + "");

            for (Map.Entry<String, String> entry : e.getResult().getTranslations().entrySet()) {
                System.out.println("Translated into " + entry.getKey() + ": " + entry.getValue() + "");
            }
        });*/
        // Enter the conversation to start receiving events
        conversationTranslator.joinConversationAsync(conversation, displayName).get();
        // You can now send an instant message to all other participants in the room
        //conversationTranslator.sendTextMessageAsync("The instant message to send");

        // If specified a speech-to-text language, you can start capturing audio
        conversationTranslator.startTranscribingAsync();
        /*  System.out.println("Started transcribing. Press Ctrl + c to stop");*/
        return conversation.getConversationId();
    }
}`

**Comment by ralph-msft** [comment] 2022-07-19 22:27
Thanks for sharing the code. We were able to reproduce the issue you are seeing with removing participants. We are working on a fix for this but don't have an ETA to share at this time.

In the meantime, in going over your code above I wanted to point some potential issues:
- You need to call ```.get()``` on the ```Future<>``` returned from all of the SDK Async() methods. You are missing that in several places in the code above. For example: ```conversation.startConversationAsync()```
- You are specifying an 8 channel audio source which is not supported by the ConversationTranslator. Please use mono (1 channel) audio instead
- You should always register an event handler for the ```ConverationTranslator.canceled```. This will be main way that any errors are reported
- Please note that your event handler code will be called on a different thread than your main code. This means that any exceptions raised there won't be visible to the rest of the code

**Closed** 2023-09-08 03:10 UTC
Labels: bug, accepted
