### ISSUE TITLE
Exception (SPXERR_MIC_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by rambabuk1222** [Azure-Samples/cognitive-services-speech-sdk#436] opened 2019-11-16 18:24 UTC
**Describe the bug**
I have implemented same code in my bot framework (c#) project

**To Reproduce**

                            var config = SpeechConfig.FromSubscription("*************", "westus");
                            using (var recognizer = new SpeechRecognizer(config, AudioConfig.FromDefaultMicrophoneInput()))
                            {
                                
                                await recognizer.StartCont
![Bot Error](https://user-images.githubusercontent.com/12018103/68997431-3f6a2f80-089e-11ea-8a1b-47bb92ffcc07.PNG)
inuousRecognitionAsync();

                            }

**Expected behavior**
When I speak app should be take voice and convert into text and send to bot.

**Version of the Cognitive Services Speech SDK**
3.0

**Platform, Operating System, and Programming Language**
 - OS: azure
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#
 - Browser : Chrome and MS Teams

**Additional context**
 -  Exception with an error code: 0xe (SPXERR_MIC_NOT_AVAILABLE)

**Comment by drparam** [comment] 2019-11-20 23:12
I have the same exact issue and appreciate if anyone in BOT team can provide solution for above speech to text. This works fine in emulator when the Visual studio project is run but not after deploying. So connecting the emulator to azure web bot app is throwing same error message (SPXERR_MIC_NOT_AVAILABLE). Appreciate if this can be resolved at the earliest.

**Comment by chrisbasoglu** [comment] 2019-11-22 22:28
@rambabuk1222  we need some more details.  For example you say the OS is azure.  What does that mean?  You say the programming language is C#, but the Browser is chrome and MS Teams, how are you running your C# program within Chrome or MS Teams?

@drparam  where are deploying to?

**Comment by jhakulin** [comment] 2019-11-22 22:58
Mic related problem are most often related to your specific HW configuration and not the problem in Speech SDK. Please ensure microphone is working OK in your machine, ideally if you are able to verify that your audio drivers support 16bit 16kHz PCM audio capture that would be the same as Speech SDK is using.

**Comment by BrianMouncer** [comment] 2019-11-22 23:01
I usually see SPXERR_MIC_NOT_AVAILABLE if using the from microphone APIs on a device with no input device. That or from a UWP app that hasn’t requested and accepted the microphone capability.

If you’re using the emulator or using remote desktop, you will need to modify your connection settings so that you redirect audio (by default Terminal Services only redirects speakers, you need to also redirect the microphone).

If you actually want to use the app on a device with no microphone, then switch to using the from file or stream input methods.  Here is one example, https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/dotnet/from-file

**Comment by rambabuk1222** [comment] 2019-11-23 22:11
Thanks for you response. I'm using speech SDK for Microsoft bot framework project. When I run the app in enumerator it works fine.After hosting it into azure, It is not working as I expected. please find complete c# code below. I tested my microphone with similar [online app](https://microsoft.github.io/BotFramework-WebChat/06.f.hybrid-speech/) and its working fine.


```

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Schema;
using Microsoft.CognitiveServices.Speech;
using Microsoft.CognitiveServices.Speech.Audio;

namespace Microsoft.BotBuilderSamples.Bots
{
    public class EchoBot : ActivityHandler
    {
        protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync(MessageFactory.Text($"Echo: {turnContext.Activity.Text}"), cancellationToken);
            var config = SpeechConfig.FromSubscription("----------------------------", "northeurope");
            using (var recognizer = new SpeechRecognizer(config, AudioConfig.FromDefaultMicrophoneInput()))
            {
                await turnContext.SendActivityAsync(MessageFactory.Text($"Echo: Please some words."), cancellationToken);
                var result=  await recognizer.RecognizeOnceAsync();

                await turnContext.SendActivityAsync(MessageFactory.Text($"Echo: {result.Text}"), cancellationToken);
            }
        }

        protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            foreach (var member in membersAdded)
            {
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    await turnContext.SendActivityAsync(MessageFactory.Text($"Hello and welcome!"), cancellationToken);
                }
            }
        }
    }
}
```

**Comment by chrisbasoglu** [comment] 2019-11-25 00:20
^^ After hosting it into azure, It is not working as I expected
Azure VMs don;t have microphones.  Can you be more detailed about your scenario?

**Comment by drparam** [comment] 2019-11-26 20:03
Hi Chris

Thanks for getting back. I think we need to understand the scenario here to be precise in finding answer. Can I setup a call so we can do a screensharing session to solve this issue, please?

If you can share your email, I will then send an invite based on your availability.

Regards

[cid:image001.png@01D4243D.2D1346B0]
[cid:image002.jpg@01D4243D.2D1346B0]
[A drawing of a face  Description automatically generated]
Dr. Subramani Paramasivam (MANI)    PhD., MVP, MCT, MCSE, MCITP
Principal Solutions Architect & Program Lead
DAGEOP
Head Quarters: 27 LONGBRIDGE ROAD, BARKING, ENGLAND, IG11 8TN, UK
Research & Development: Chennai, INDIA    |    Sales & Marketing: Kuala Lumpur, MALAYSIA.
Tel: 0044 (0) 203 086 8701  |  Mob: 0044 (0) 746 0305 107
Email: mani@dageop.com<mailto:mani@dageop.com>  |  Web: www.dageop.com<http://www.dageop.com/>
[cid:image003.jpg@01D4243D.2D1346B0]<https://twitter.com/dageop>      [cid:image004.jpg@01D4243D.2D1346B0] <https://uk.linkedin.com/in/dageop>       [cid:image005.jpg@01D4243D.2D1346B0] <https://www.facebook.com/YOUR-SQL-MAN-LTD-591645464193445/>       [cid:image006.jpg@01D4243D.2D1346B0] <https://www.youtube.com/user/YourSQLMAN>


DISCLAIMER- YOUR SQL MAN LIMITED T/A DAGEOP

This e-mail message is intended only for the use of the addressee (i.e. Intended Recipient). If you are not the intended recipient and have erroneously received this message, please delete it immediately and notify the sender. The information contained herein (including any attachments) may be privileged and confidential and protected from disclosure under applicable laws. You are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this message or any attachments is strictly prohibited and is unlawful. Any information expressed in this e-mail as well if this is a forwarded message, does not necessarily reflect the views of Your SQL Man Ltd t/a DAGEOP. The sender or the company is not responsible for any damage caused by a virus or alteration of the e-mail by a third party or any error or omission in the contents of the message that arise, as a result of e-mail.

**Comment by drparam** [comment] 2019-11-29 10:12
Hi Chris

I have recorded the issue with speech to text and the quick 2 minutes video is available for you here<https://1drv.ms/u/s!AnTZZKrEsfCHg5BaVG5kssU3u_ULgQ?e=CPG4OT>.
The source code is available in this github<https://github.com/rambabuk1222/EchoBot> for you to test the same.

Appreciate a quick turn around on this as we have been waiting to find a solution for a long time.

Regards

[cid:image001.png@01D4243D.2D1346B0]
[cid:image002.jpg@01D4243D.2D1346B0]
[A drawing of a face  Description automatically generated]
Dr. Subramani Paramasivam (MANI)    PhD., MVP, MCT, MCSE, MCITP
Principal Solutions Architect & Program Lead
DAGEOP
Head Quarters: 27 LONGBRIDGE ROAD, BARKING, ENGLAND, IG11 8TN, UK
Research & Development: Chennai, INDIA    |    Sales & Marketing: Kuala Lumpur, MALAYSIA.
Tel: 0044 (0) 203 086 8701  |  Mob: 0044 (0) 746 0305 107
Email: mani@dageop.com<mailto:mani@dageop.com>  |  Web: www.dageop.com<http://www.dageop.com/>
[cid:image003.jpg@01D4243D.2D1346B0]<https://twitter.com/dageop>      [cid:image004.jpg@01D4243D.2D1346B0] <https://uk.linkedin.com/in/dageop>       [cid:image005.jpg@01D4243D.2D1346B0] <https://www.facebook.com/YOUR-SQL-MAN-LTD-591645464193445/>       [cid:image006.jpg@01D4243D.2D1346B0] <https://www.youtube.com/user/YourSQLMAN>


DISCLAIMER- YOUR SQL MAN LIMITED T/A DAGEOP

This e-mail message is intended only for the use of the addressee (i.e. Intended Recipient). If you are not the intended recipient and have erroneously received this message, please delete it immediately and notify the sender. The information contained herein (including any attachments) may be privileged and confidential and protected from disclosure under applicable laws. You are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this message or any attachments is strictly prohibited and is unlawful. Any information expressed in this e-mail as well if this is a forwarded message, does not necessarily reflect the views of Your SQL Man Ltd t/a DAGEOP. The sender or the company is not responsible for any damage caused by a virus or alteration of the e-mail by a third party or any error or omission in the contents of the message that arise, as a result of e-mail.

From: Subramani Paramasivam
Sent: 26 November 2019 20:03
To: Azure-Samples/cognitive-services-speech-sdk <reply@reply.github.com>; Azure-Samples/cognitive-services-speech-sdk <cognitive-services-speech-sdk@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure-Samples/cognitive-services-speech-sdk] Exception (SPXERR_MIC_NOT_AVAILABLE) (#436)

Hi Chris

Thanks for getting back. I think we need to understand the scenario here to be precise in finding answer. Can I setup a call so we can do a screensharing session to solve this issue, please?

If you can share your email, I will then send an invite based on your availability.

Regards

[cid:image001.png@01D4243D.2D1346B0]
[cid:image002.jpg@01D4243D.2D1346B0]
[A drawing of a face  Description automatically generated]
Dr. Subramani Paramasivam (MANI)    PhD., MVP, MCT, MCSE, MCITP
Principal Solutions Architect & Program Lead
DAGEOP
Head Quarters: 27 LONGBRIDGE ROAD, BARKING, ENGLAND, IG11 8TN, UK
Research & Development: Chennai, INDIA    |    Sales & Marketing: Kuala Lumpur, MALAYSIA.
Tel: 0044 (0) 203 086 8701  |  Mob: 0044 (0) 746 0305 107
Email: mani@dageop.com<mailto:mani@dageop.com>  |  Web: www.dageop.com<http://www.dageop.com/>
[cid:image003.jpg@01D4243D.2D1346B0]<https://twitter.com/dageop>      [cid:image004.jpg@01D4243D.2D1346B0] <https://uk.linkedin.com/in/dageop>       [cid:image005.jpg@01D4243D.2D1346B0] <https://www.facebook.com/YOUR-SQL-MAN-LTD-591645464193445/>       [cid:image006.jpg@01D4243D.2D1346B0] <https://www.youtube.com/user/YourSQLMAN>


DISCLAIMER- YOUR SQL MAN LIMITED T/A DAGEOP

This e-mail message is intended only for the use of the addressee (i.e. Intended Recipient). If you are not the intended recipient and have erroneously received this message, please delete it immediately and notify the sender. The information contained herein (including any attachments) may be privileged and confidential and protected from disclosure under applicable laws. You are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this message or any attachments is strictly prohibited and is unlawful. Any information expressed in this e-mail as well if this is a forwarded message, does not necessarily reflect the views of Your SQL Man Ltd t/a DAGEOP. The sender or the company is not responsible for any damage caused by a virus or alteration of the e-mail by a third party or any error or omission in the contents of the message that arise, as a result of e-mail.

**Comment by jhakulin** [comment] 2019-11-29 19:59
Thanks a lot for all the details and test code, we will try that and let you know.

**Comment by jhakulin** [comment] 2019-12-02 03:15
@drparam Please check the following tutorial on how to create voice enabled bot using speech SDK.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk

**Comment by drparam** [comment] 2019-12-02 03:54
Thanks for getting back. I have tried this and as it was not working, I have reached out with recorded video and full github code in my previous response. I have been chasing with this work for more than a month speaking to various Microsoft AI team members and as per their last suggestion tried to reach via Github. I am afraid that we are going in circles but not reaching a working solution. Before deployment it works fine in my local emulator, but not after deploying. I really appreciate if you can see the demo video and the code provided and advise on a working solution. 
NOTE:
The provided Github solution is a simple solution a copy of Microsoft Github sample and based on the suggested documents.

**Comment by jhakulin** [comment] 2019-12-02 05:10
Thanks for more information, it is not certainly good if even the tutorial I linked did not help you get further. I will discuss with the engineers working on creating voice enabled bots and we'll try to get more information about the issue.

Regarding your sample and video, I did look those, but personally I do not know (yet) what microphone the bot sample actually tries to use when bot is deployed to Azure Portal. When running Bot sample locally, it uses your machine's microphone which works.

**Comment by gghizila** [comment] 2019-12-02 05:30
Can you try to connect using this test application instead of the emulator: 
https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client 

Make sure that your bot is enabled for direct line speech channel in the azure portal for your bot. We will investigate what happens in the case of emulator in the meantime.

**Comment by gghizila** [comment] 2019-12-02 05:53
As far as I can see from the original code you are not trying to use the dialog connector API but speech recognition API. Speech recognition API is unaware of the bot existence it gets audio and generates text in response. Can you tell more about the app that runs the SDK?  
- Is this a UWP app? 
- I could not figure out from the video where is your app, is that the bot emulator that has your code? 
- is the client app (not the bot) running on your local computer?

**Comment by gghizila** [comment] 2019-12-02 21:42
I had to delete a couple of my answers as I kept getting it wrong and I was not sure what is the scenario. Still not sure but after chatting with members or our team we know what is not working and can't work. 

I am simply reiterating some of the statements from Chris and Jarno but the bot code is running on the service there is no way that running in the service gives access to the microphone on the client machine (nor on the service machine but that does not matter much). Running it locally it does access the microphone on your machine but there is no component on the service where you can simply open the microphone and expect to be redirected to the client. 

What we offer right now is the ability to connect your bot to a channel that allows you to stream audio to it not just plain activities, the link previously shared[Tutorial: Voice-enable your bot using the Speech SDK]( https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/tutorial-voice-enable-your-bot-speech-sdk) should give you the information you need to get this going. 

Note that this approach will not require to use the speech SDK in the bot but in the client application. Also emulator will not provide you with the audio from client yet you can use this sample aplication to connect to your bot with voice:  Direct Line [Speech Client](https://github.com/Azure-Samples/Cognitive-Services-Direct-Line-Speech-Client/blob/master/README.md). Hope this helps. 

If you have trouble handling any of the steps in the tutorial, please let us know.

**Comment by bos-sudhakar** [comment] 2019-12-03 14:11
Will this work on web or only console application? if yes how?

**Comment by gghizila** [comment] 2019-12-03 16:18
The API has C#, Java, Xamarin and quite a few other projections so one can develop apps on Windows, Android, iOS or middle tier web services, console apps are just the simplest to understand the entire flow. Of course the microphone is not available in web services directly, one will have to stream the audio and use stream based APIs instead of microphone, there are a number of samples for that. For a browser there is the [javascript SDK](https://github.com/microsoft/cognitive-services-speech-sdk-js/) that can handle that.

**Comment by jhakulin** [comment] 2019-12-05 04:27
Closing this as the issue is known and solution proposed. Let us know if there is more information needed.

**Closed by jhakulin** 2019-12-05 04:27 UTC

**Comment by karthikcs** [comment] 2021-05-12 07:54
Hi, I am getting this error while I am trying to use Microphone different from default mic. I think I am not providing proper DEVICE_ID. I am writing my client in python on Windows 10 local machine. Here is my code snippet (Modified from Azure Example).  Can you please through light on how to get proper DEVICE_ID of a mic on Windows 10
```
def translation_once_from_mic(src_lang, dest_lang, outfile):
    """performs one-shot speech translation from input from an audio file"""
    # <TranslationOnceWithMic>
    # set up translation parameters: source language and target languages
    print(src_lang, dest_lang)
    translation_config = speechsdk.translation.SpeechTranslationConfig(
        subscription=speech_key, region=service_region,
        speech_recognition_language=str(src_lang),
        target_languages=([str(dest_lang)]))
    # audio_config = speechsdk.audio.AudioConfig(use_default_microphone=True)
    audio_config = speechsdk.audio.AudioConfig(device_name="MMDEVAPI\AudioEndpoints")
```

**Comment by karthikcs** [comment] 2021-05-12 09:14
Friends,
I figured it out..  I was reading Microsoft Docs [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-select-audio-input-devices#audio-device-ids-on-windows-for-desktop-applications). I understood the format of the device ID will be as `{0.0.1.00000000}.{5f23ab69-6181-4f4a-81a4-45414013aac8}`

When I was going through all the properties of the device driver in Control panel, I found the property called `Device Instance Path`. If you leave the initial part which is the path like `SWD\MMDEVAPI\{0.0.1.00000000}.{8c85a4e8-3a66-4857-8883-96d100179b47}`. The last part of this value is the Device ID. Hope this helps..

**Comment by samkuls** [comment] 2021-08-31 13:06
Getting exception when deploy Speech SDK on Azure webapp SPXERR_MIC_NOT_AVAILABLE

Describe the bug
When I am trying to deplpy my Speech SDK (from Microphone To Speech)on Azure webapp getting SPXERR_MIC_NOT_AVAILABLE though it is working locally and over local iis deployed also.

To Reproduce
Steps to reproduce the behavior:
Write below method on .net core api and deploy on Azure

    public async Task<IActionResult> MicrophoneToSpeechAsync(string languageIso6391Code)
    {
        var subscription = _config.GetValue<string>("SubscriptionId");
        var location = _config.GetValue<string>("Region");
        var config = SpeechConfig.FromSubscription(subscription, location);
        config.SpeechRecognitionLanguage = string.IsNullOrWhiteSpace(languageIso6391Code) ? "en-us" : 
        languageIso6391Code;

        // Creates a speech recognizer.
        using (var recognizer = new SpeechRecognizer(config))
        {
            Console.WriteLine("Say something...");
            var result = await recognizer.RecognizeOnceAsync();
            List<SpeechCommonService.DetectedLanguage> language = null;
            // Checks result.
            if (result.Reason == ResultReason.RecognizedSpeech)
            {
                Console.WriteLine($"We recognized: {result.Text}");
         
            }
        }
}
Extected behaviour it should understand the spoken words over microphone and convert it to text.

**Comment by rhurey** [comment] 2021-08-31 14:54
It may be better to open this as a new issue.

Can you help clarify your intentions? When running in a webapp, the code will be executed in the cloud, where there isn't a microphone. If you want to recognize speech from a web page, the [JavaScript version](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk) of the Speech SDK can do that.

**Comment by samkuls** [comment] 2021-09-06 09:05
@rhurey : my intention is to create one api which can be consumed by my organization to perform STT through microphone. i need solution in .Net. Thanks in advance.

**Comment by samkuls** [comment] 2021-09-07 06:21
@gghizila : I am using Speech SDK in Service API. How to use stream based APIs instead of microphone in c#??
Thanks.
