### ISSUE TITLE
Error when trying to initialize speechsdk.SpeechConfig in Python

### ISSUE THREAD

**Issue by chagen24** [Azure-Samples/cognitive-services-speech-sdk#582] opened 2020-04-13 20:50 UTC
When I try to initialize the Python speech sdk's SpeechConfig object, I receive an error. The code looks like:

`speech_key, service_region = "<my-key>", "https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken"`

`speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)`

(with "<my-key>" containing the key found in my Azure Cognitive Services Speech "Keys and Endpoints" blade)

This is the error that I'm getting:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-9c603860c1fd> in <module>
      1 speech_key, service_region = "<my-key>", "https://westus2.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
----> 2 speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

~\Anaconda3\envs\unicart_speech\lib\site-packages\azure\cognitiveservices\speech\speech.py in __init__(self, subscription, region, endpoint, host, auth_token, speech_recognition_language)
     52             speech_recognition_language: OptionalStr = None):
     53 
---> 54         self._impl = self._get_impl(impl.SpeechConfig, subscription, region, endpoint, host, auth_token,
     55                 speech_recognition_language)
     56 

~\Anaconda3\envs\unicart_speech\lib\site-packages\azure\cognitiveservices\speech\speech.py in _get_impl(config_type, subscription, region, endpoint, host, auth_token, speech_recognition_language)
    143             if endpoint is not None or host is not None or auth_token is not None:
    144                 raise ValueError(generic_error_message)
--> 145             _impl = config_type._from_subscription(subscription, region)
    146         elif region is not None and auth_token is not None:
    147             if endpoint is not None or host is not None or subscription is not None:

RuntimeError: Exception with an error code: 0x5 (SPXERR_INVALID_ARG)
[CALL STACK BEGIN]

    > source_lang_config_release

    - source_lang_config_release

    - speech_config_from_subscription_internal

    - 00007FFD0458C958 (SymFromAddr() error: Attempt to access invalid address.)

    - 00007FFD0450E543 (SymFromAddr() error: Attempt to access invalid address.)

    - PyCFunction_Call

    - Py_CheckFunctionResult

    - PyEval_EvalFrameDefault

    - Py_CheckFunctionResult

    - PyEval_EvalFrameDefault

    - PyEval_EvalCodeWithName

    - PyFunction_Vectorcall

    - PySequence_Check

    - Py_CheckFunctionResult

    - PyEval_EvalFrameDefault

    - PyEval_EvalCodeWithName

[CALL STACK END]

**Comment by pankopon** [comment] 2020-04-13 20:58
Hi, the value of service_region needs to be one of the supported regions as documented at https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions. In your example it seems to be westus2 - so instead of ""https://westus2.api..." you need to use "westus2".

**Comment by chagen24** [comment] 2020-04-13 21:04
Thank you for your reply. I deleted the resource and spun up a new one in "eastus" (which is listed as a supported region in the list you linked). My code now looks like this:

`speech_key, service_region = "<my-key>", "https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken"`

`speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)`

But I am still getting the same error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-7a670ec7a945> in <module>
      1 speech_key, service_region = "73a2dd12f9a14e378e5b940c1dd775d4", "https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
----> 2 speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)

~\Anaconda3\envs\unicart_speech\lib\site-packages\azure\cognitiveservices\speech\speech.py in __init__(self, subscription, region, endpoint, host, auth_token, speech_recognition_language)
     52             speech_recognition_language: OptionalStr = None):
     53 
---> 54         self._impl = self._get_impl(impl.SpeechConfig, subscription, region, endpoint, host, auth_token,
     55                 speech_recognition_language)
     56 

~\Anaconda3\envs\unicart_speech\lib\site-packages\azure\cognitiveservices\speech\speech.py in _get_impl(config_type, subscription, region, endpoint, host, auth_token, speech_recognition_language)
    143             if endpoint is not None or host is not None or auth_token is not None:
    144                 raise ValueError(generic_error_message)
--> 145             _impl = config_type._from_subscription(subscription, region)
    146         elif region is not None and auth_token is not None:
    147             if endpoint is not None or host is not None or subscription is not None:

RuntimeError: Exception with an error code: 0x5 (SPXERR_INVALID_ARG)
[CALL STACK BEGIN]

    > source_lang_config_release

    - source_lang_config_release

    - speech_config_from_subscription_internal

    - 00007FFD0458C958 (SymFromAddr() error: Attempt to access invalid address.)

    - 00007FFD0450E543 (SymFromAddr() error: Attempt to access invalid address.)

    - PyCFunction_Call

    - Py_CheckFunctionResult

    - PyEval_EvalFrameDefault

    - Py_CheckFunctionResult

    - PyEval_EvalFrameDefault

    - PyEval_EvalCodeWithName

    - PyFunction_Vectorcall

    - PySequence_Check

    - Py_CheckFunctionResult

    - PyEval_EvalFrameDefault

    - PyEval_EvalCodeWithName



[CALL STACK END]

**Comment by chagen24** [comment] 2020-04-13 21:06
Also, if I try to contact "https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken" with my browser, the following is the response I'm getting:

{"error":{"code":"404","message": "Resource not found"}}

**Comment by pankopon** [comment] 2020-04-14 01:30
Please use only a short region identifier for the value of service_region. So instead of

`
speech_key, service_region = "<my-key>", "https://eastus.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
`

do

`
speech_key, service_region = "<my-key>", "eastus"
`

**Comment by pankopon** [comment] 2020-04-15 17:43
Closing as resolved, please re-open if necessary.

**Closed by pankopon** 2020-04-15 17:43 UTC

**Comment by JoshAshDowner** [comment] 2024-12-12 00:43
Hey I am having the same issue except I have the short region name from the list of azure short regions, confirmed as the region from my azure speech resource "australiasoutheast" 
I am running this inside a vs code venv of python 3.7.3, but I keep getting that same error "ValueError: cannot construct SpeechConfig with the given arguments"

my code snippet is below

`ai_region = os.getenv("australiaeast")
ai_key = os.getenv("bingus")
ai_endpoint = os.getenv("https://australiaeast.api.cognitive.microsoft.com/")


speech_config = speechsdk.SpeechConfig(subscription=ai_key, region=ai_region)
speech_config.speech_recognition_language="en-GB"`
