### ISSUE TITLE
English Speech Transcribed Correctly but Language Tagged as Chinese

### ISSUE THREAD

**Issue by 0necolor** [Azure-Samples/cognitive-services-speech-sdk#2321] opened 2024-03-30 09:14 UTC
## Description
Using the speech-to-text service with `AutoDetectSourceLanguageConfig` configured to detect both Chinese and English, the service correctly transcribes spoken English with a Chinese accent but incorrectly identifies the language of the transcription as Chinese instead of English.

## Steps to Reproduce
1.  Configure the speech-to-text service to use `AutoDetectSourceLanguageConfig` with both Chinese and English specified as the languages to detect.  (en-US zh-CN)
2.  Submit an audio clip of a Chinese speaker saying "what are you doing?" in English with a Chinese accent.
3.  Observe the transcription result and the language identification.

## Expected Behavior
The speech-to-text service is expected to transcribe the English phrase accurately and identify the language correctly as English, even when spoken with a Chinese accent.

## Actual Behavior
The service accurately transcribes the English phrase "what are you doing?"  However, it tags the language of the transcription as Chinese (zh-CN).

**Comment by 0necolor** [comment] 2024-03-30 09:14
Is there any solution and I hope someone will get back to me soon, this issue is affecting my product experience

**Comment by 0necolor** [comment] 2024-04-19 02:19
nobody?

**Comment by ralph-msft** [comment] 2024-04-22 18:00
Unfortunately, I am not able to reproduce the issue you are experiencing. Could you please provide the following:
* Sample audio file that reproduces the incorrect language detection
* The SDK logs when this incorrect detection detection occurs. You can find instructions on how to capture these here: https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-logging

**Comment by pankopon** [comment] 2024-05-16 01:23
Closed as not reproducible and no further requested information received.

**Closed by pankopon** 2024-05-16 01:23 UTC
Labels: in-review, pending close
