### ISSUE TITLE
CognitiveServices.Speech.core.so assembly can't be loaded - xamarin Android 12 Emulator x86_64 - API 31

### ISSUE THREAD

**Issue by pasha-o** [Azure-Samples/cognitive-services-speech-sdk#1457] opened 2022-04-07 23:49 UTC
**Describe the bug**
@glharper , @jgardner04 Targeting new android API 31 on a fresh emulator on Pixel 5, API 31 with X86-64 processor, the DLL won't load.
libMicrosoft.CognitiveServices.Speech.core.so assembly:<unknown assembly> type:<unknown type> member:(null)

**Expected behavior**
dll should load

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech Version 1.20.0 for Xamarin Forms

**Platform, Operating System, and Programming Language**
 - OS: Android API 31
 - Hardware - x86-64
 - Programming language: C#

**Additional context**
There is no way to change the processor to only X86 in the Android SDK manager for Pixel 5 API 31

**Comment by dargilco** [comment] 2022-04-08 19:55
Adding @jhakulin

**Comment by jhakulin** [comment] 2022-04-11 18:14
@pasha-o Thanks for the report. We will investigate and let you know what we can find out.

**Comment by jhakulin** [comment] 2022-04-12 00:01
@pasha-o The problem is that currently Speech SDK NuGet for Xamarin do not contain x86_64 binary for Android, but only x86. If Android Studio do not support x86 emulation for API 31 (Android 12) and onwards, this is a gap, which we can fix in the future releases. For now, are you able to test your app using earlier Android API version and x86 emulator? 

Alternatively if you want to do some tailoring, it could be possible to take x86_64 native library from Speech SDK .aar package from Maven repository in Azure blob storage (see https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-sdk?tabs=android%2Cubuntu%2Cios-xcode%2Cmac-xcode%2Candroid-studio) and place the x86_64 binary there into your Xamarin application.

**Comment by jhakulin** [comment] 2022-04-12 04:42
Internal task 4179271

**Comment by pasha-o** [comment] 2022-04-12 18:21
hi, @jhakulin thanks for the note. according to android [link](https://developer.android.com/games/optimize/64-bit), the apps must support the 64-bit architecture. Do you happen to know when you'd have support for the x86_64 binary as I feel android will move away from 32-bit.

**Comment by jhakulin** [comment] 2022-04-12 19:27
@pasha-o Thanks, we do support 64-bit ARM architecture in the NuGet. We will add x86_64 support for Android NuGet for Xamarin as well in the next release (currently x86_64 is available in .aar package). Are you targeting x86_64 Xamarin to emulator only or to actual Android device which is using Intel's x64? 

Below quick instructions on how to build Xamarin project with x86_64 architecture included. 
1) Add reference to Microsoft.CognitiveServices.Speech.csharp.dll to Xamarin main project (which you can find from NuGet lib\monoandroid directory when unzipped)
2) Add AndroidNativeLibrary (which you can find from .aar client-sdk-1.20.0\jni\x86_64 directory) to Android project (Mouse right click -> Add -> Existing item) and set the BuildAction to AndroidNativeLibrary
![image](https://user-images.githubusercontent.com/16473503/163037117-6fa05a4d-a62e-425f-933b-5ac8ee4c1733.png)

See also following which might help.
https://docs.microsoft.com/en-us/xamarin/android/platform/native-libraries

**Comment by pasha-o** [comment] 2022-04-14 23:45
Thanks, @jhakulin - your explanation helped. looking forward to the next release. Is there a timeline for the next release?

**Comment by jhakulin** [comment] 2022-04-15 00:04
@pasha-o x86_64 support in NuGet for Android would go to 1.22.0 Speech SDK release, where ETA is end of May 2022.

**Comment by pankopon** [comment] 2022-04-19 00:26
Internal work item ref. 4179271.

**Comment by jhakulin** [comment] 2022-06-13 14:46
Support for x86_64 Android emulation has been added to 1.22.0 Speech SDK release for Xamarin. Closing the issue.

**Closed by jhakulin** 2022-06-13 14:46 UTC
Labels: enhancement, accepted
