### ISSUE TITLE
Speech recognition not working with restart of continuousRecognitionAsync

### ISSUE THREAD

**Issue by jahnviss** [Azure-Samples/cognitive-services-speech-sdk#1120] opened 2021-06-03 09:59 UTC
We are using Twilio JS SDK for audio video call web application.
For Speech to text we used Azure speech recognition service having latest version from https://csspeechstorage.blob.core.windows.net/drop/1.17.0/RawJavaScriptSDK/microsoft.cognitiveservices.speech.sdk.bundle.js

In our application we have more than one users connected so multiple media streams are there.
To get the speech to text result for multiple users, I have used 2 speechSDK object, 2 speechConfig object and 2 audioConfig objects so it will not conflict. 

Everything works fine until any user restart his mic. On mic off/on we simply disable/enable twilio audio tracks. 

For speech recognition I am using stopContinuousRecognitionAsync(),then dispose() and remove the item from an array on mic off. When user again turns ON his mic, I am using startContinuousRecognitionAsync(). But in this case, speech recognition behaves wierd. when local user speaks two events are fired same time for local and remote. that is console.error messages I have set in recognizing and recognized events are fired for local and remote both, when local user is speaking. When remote user speaks no event gets fired.

Can you help us that **what is going wrong here that issue occurs only when stopContinuousRecognitionAsync() and startContinuousRecognitionAsync() is performed.**

Below is the code I used.

initialization :
-------------------
this.initCaptionModal = function(){
            subscriptionKey = "using account key here"; 
            serviceRegion = "northcentralus";
            languageSourceOptions  = "en-US";
            languageTargetOptions = "en-US";
			
            if (!!window.SpeechSDK) {
              SpeechSDK = window.SpeechSDK;
            }
            if (!!window.SpeechSDK) {
              SpeechSDKRemote = window.SpeechSDK;
            }
            speechConfig = SpeechSDK.SpeechTranslationConfig.fromSubscription(subscriptionKey, serviceRegion);
            speechConfigRemote = SpeechSDKRemote.SpeechTranslationConfig.fromSubscription(subscriptionKey, serviceRegion);
			
            if(speechConfigRemote){
              speechConfigRemote.speechRecognitionLanguage = languageSourceOptions;
              speechConfigRemote.addTargetLanguage(languageTargetOptions);
            }
            
			if(speechConfig){
              speechConfig.speechRecognitionLanguage = languageSourceOptions;
              speechConfig.addTargetLanguage(languageTargetOptions);          
            }
	}
	
for local users: 
--------------------
 this.startLocalCaption = function(){
            
            // if doesn't exist already
             if(!_this.localRecognizer){

              console.error("in startLocalCaption");
              var localNewStream = new MediaStream();
              localNewStream.addTrack($rootScope.localAudioTrack.mediaStreamTrack);
              console.error(localNewStream, "remote audio stream for = "+ $rootScope.localPartiIdentity);

              var localAudioConfig  = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();
              _this.localRecognizer = new SpeechSDK.SpeechRecognizer(speechConfig, localAudioConfig);
              _this.localRecognizer.startContinuousRecognitionAsync();
              console.error("Speech recognizier initialized for = "+$rootScope.localPartiIdentity);

              //  The event recognizing signals that an intermediate recognition result is received.
              _this.localRecognizer.recognizing = function(s, e){
                  console.error('LOCAL recognizing text=>', e.result.text);
              };
            
              //  The event recognized signals that a final recognition result is received.
              _this.localRecognizer.recognized = function(s, e){
                  $rootScope.caption = true;
                  console.error('LOCAL recognized text=>', e.result.text);
                
              };
            }
        }

for remotely connected user 		
------------------------------
this.startRemoteCaption = function(){

		//check for each connnected participants 
          room.participants.forEach(function (remoteParticipant, val) {
              console.error(remoteParticipant);
              var partiId = remoteParticipant.identity;
              
              // if doesn't exist already
              if (_this.remoteRecognizer.hasOwnProperty(partiId) == false) { 

                rtracks = twilioCall.getTracksByType(remoteParticipant,'audio');
                
                remoteAudioStream = new MediaStream();
                rtracks.forEach(function (track) {
        
					//audio exist and is enabled
                    console.error(track,"::remote audio track");
                    if (track.kind == "audio" && track.isEnabled) {

                      remoteAudioStream.addTrack(track.mediaStreamTrack);
                      console.error(remoteAudioStream, "remote audio stream for = "+ partiId);
                      if(remoteAudioStream){
                          
                          //participant wise recognizing object
                          audioConfig  = SpeechSDKRemote.AudioConfig.fromStreamInput(remoteAudioStream);
                          _this.remoteRecognizer[partiId] = new SpeechSDKRemote.SpeechRecognizer(speechConfigRemote, audioConfig);
                          _this.remoteRecognizer[partiId].startContinuousRecognitionAsync();
                          console.error("Speech recognizier initialized for = "+partiId);

                          //intermittent result
                          _this.remoteRecognizer[partiId].recognizing = function(s, e){
                            console.error(partiId + ' - REMOTE recognizing text = ', e.result.text);
                          };

                          //final result
                          _this.remoteRecognizer[partiId].recognized = function(s, e){
                            console.error(partiId + ' - REMOTE recognized text = ', e.result.text);
                          };
						}
					}
				});
			}
		});

}

**Comment by BrianMouncer** [comment] 2021-06-05 00:58
I'm not sure, but from what you describe, but since you descript the events firing twice and or for the wrong user stream, the first thing I would look at is if the event handlers are getting torn down and reconnected as you expect them to be when you lose and regain audio...

Next would see if the "partiId" and "localPartiIdentity" are correct during both connect  and reconnect scenarios.
Because it sounds like there might be an unexpected code path where its not disconnecting the right party, or maybe just connecting to the right party twice???

If that looks correct, then can you try to reproduce the issue using static audio files loaded into stream and the speech sdk, and send us a concise repo of the issue?

In the mean time, I will ask one of our JS devs if they ahve any other suggestions.

Thanks,

**Comment by jahnviss** [comment] 2021-06-07 07:05
[logs for speech recognition.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6606466/logs.for.speech.recognition.txt)

Please check attached logs.

First of all, I am not reconnecting Twilio participant, I am just disabling/enabling audio track. so remote user's audio track exist on my local machine, and those are attached. ..so I did not understood your point of _" first thing I would look at is if the event handlers are getting torn down and reconnected as you expect them to be when you lose and regain audio.."_

moreover local and remote participant ids are showing correct in Recognized listeners. I have also consoled speechRecognizer object, so inside that object there is prevMediaStream and in that IDs of media stream are also different.

check logs in that bacec11ff3254811ae61985af3df63fc_204709178_0 ID is remote user's ID, but when that user has mute himself and unmute, next time when he was speaking no recognizing or recognized listeners called. Instead when local user who is 169_user_0 ID, is speaking the recognizing and recognier listeners are called for both the users that is,
bacec11ff3254811ae61985af3df63fc_204709178_0 
169_user_0 

you can check this behaviour are the text **"me a CE is remote"** where actually local user that is 169_user_0 was speaking that "bacec ....is a remote user"  but recognizing object was showing on following line

**"liveCaption.js?b3.2:204 bacec11ff3254811ae61985af3df63fc_204709178_0 - recognizing text =  me a CE is remote"**

is there any other way we can debug it more or check where the issue is ? what else we can apply here? can you please send this logs to your JS developers, whats wrong is happening on mute/unmute which is actually Recognizer.stopContinuousRecognitionAsync(); and Recognizer.startContinuousRecognitionAsync();

**Comment by jahnviss** [comment] 2021-06-08 13:33
Further I tried with work around , that instead of only using stopContinuousRecognitionAsync() and startContinuousRecognitionAsync(), I disposed and unset
speechSDK, speechConfig objects, i assigned undefined into those objects. but still when next time I start live caption feature with fresh initialization like,

if (!!window.SpeechSDK) {
    SpeechSDK = window.SpeechSDK;
}
speechConfig = SpeechSDK.SpeechTranslationConfig.fromSubscription(subscriptionKey, serviceRegion);

issue still exist. and when local user speaks, **it calls local and remote's recognizing and recognized events.**
**no event called when remote user speaks.**

Everything works fine only when I reload the web page. so is there anything stored in any object inside speech.js file which I got from below link?

https://csspeechstorage.blob.core.windows.net/drop/1.17.0/RawJavaScriptSDK/microsoft.cognitiveservices.speech.sdk.bundle.js

**Comment by jahnviss** [comment] 2021-06-10 09:20
[liveCaption.js.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6629970/liveCaption.js.txt)


I have used  speechConfig object as,
speechConfigRemote = SpeechSDKRemote.SpeechTranslationConfig.fromSubscription(subscriptionKey, serviceRegion);
and now recognizer is used as,
audioConfig  = SpeechSDKRemote.AudioConfig.fromStreamInput(remoteAudioStream);
_this.remoteRecognizer[partiId] = new SpeechSDKRemote.TranslationRecognizer(speechConfigRemote, audioConfig);

still issue exist, use of TranslationRecognizer doesn;t fix the issue.

I have attached whole live caption js file, the initial function I call is, startLiveCaption()

**Comment by glharper** [comment] 2021-06-10 15:16
@jahnviss I've updated some of your code, but am not sure if that will address your issue. Please let me see the console output when you try to reproduce with the code I've added. 
[liveCaption_updated.js.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6632562/liveCaption_updated.js.txt)

**Comment by jahnviss** [comment] 2021-06-14 04:26
I have used your code, changes of variable declaration, callback functions and logs. I have commented xxxRecognizer.close() line inside stopContinuous call back function as it was throwing error,

13:17:09.241 liveCaption.js?b3.2:396 stopContinuous error for localRecognizer: TypeError: Cannot read property 'close' of undefined
(anonymous) @ liveCaption.js?b3.2:396
(anonymous) @ speech.js?b3.2:1922
Promise.then (async)
marshalPromiseToCallbacks @ speech.js?b3.2:1911
TranslationRecognizer.stopContinuousRecognitionAsync @ speech.js?b3.2:11548
closeLocalCaptionModal @ liveCaption.js?b3.2:389
turnOffLiveCaption @ liveCaption.js?b3.2:459
resetLiveCaption @ liveCaption.js?b3.2:470

13:17:09.532 liveCaption.js?b3.2:436 stopContinuous error for be5a1752281e472f8c770af29446f4ca_204614834_0: TypeError: Cannot read property 'close' of undefined
(anonymous) @ liveCaption.js?b3.2:436
(anonymous) @ speech.js?b3.2:1922
Promise.then (async)
marshalPromiseToCallbacks @ speech.js?b3.2:1911
TranslationRecognizer.stopContinuousRecognitionAsync @ speech.js?b3.2:11548
closeRemoteCaptionModal @ liveCaption.js?b3.2:429
turnOffLiveCaption @ liveCaption.js?b3.2:461
resetLiveCaption @ liveCaption.js?b3.2:470

I have tried with SpeechTranslationConfig.fromSubscription and  SpeechConfig.fromSubscription. 

Attached logs are with  SpeechConfig.fromSubscription....
[logs for the given code.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6645615/logs.for.the.given.code.txt)

In that please notice logs at below timings I mentioned. The remote user who unmute or turned on his mic again, speech recognizer gets initialized and session started is also called, but somehow recognizing event is not getting called. after wards.....whatever local user will speak, recognizing and recognized both events will show logs of local user and remote user. what affects recognizer object when startContinuous called 2nd time? 

remote user turned first @ 15:19:13.437 time and stopContinuous call back was called.
remote user turned on his mic @ 15:19:21.547 time and Speech recognizier initialized for that id.
Also, @time 15:19:22.591 session started logs can be seen. Remote user was speaking but no recognizing or recognized event was fired.
When local user started to speak @15:19:38.627 saying "no recognition for remote audio", it was showing recognizing events for both local user and remote users.

**Comment by glharper** [comment] 2021-06-14 16:32
@jahnviss Remove all your delete calls, such as `delete _this.remoteRecognizer[partiId];`. 
What's happening is stopContinuousRecognitionAsync asynchronously tears down existing connections and tells the backend that the recognition session is ending. But because the deletes (lines 352 or 372) happen synchronously immediately after the stopContinuousRecognitionAsync(), the object is deleted before the existing connection is torn down, and so the callbacks and object member will exhibit undefined behavior. Does that makes sense?

**Comment by jahnviss** [comment] 2021-06-15 11:49
I have removed delete line and also put undefined line with timeout. 
I checked that .close() runs first and then after a second it is changed to undefined like below,

_this.localRecognizer.stopContinuousRecognitionAsync(
                  function () {
                     console.error(`stopContinuous callback for localRecognizer`);
                      _this.localRecognizer.close();
                      setTimeout(function(){
                        _this.localRecognizer = undefined;
                      },1000);
                      
                  },
                  function (err) {
                   console.error(`stopContinuous error for localRecognizer: ${err}`);
                      _this.localRecognizer.close();
                      setTimeout(function(){
                        _this.localRecognizer = undefined;
                      },1000);
                    });
            str="";
          }
		  

- So now stopContinuous is working with .close() method properly. But that did not fix the issue. 
- So as I mentioned earlier when remote user mutes his mic, stopContinuous will be called for him. 
- then again when he turns his mic ON, startContinuous will be called for him. 
- After this "sessionStarted id" logs are also filed for this particular remote user.
- But no recognizing events get fired.

When local user speaks, same audio of local, it shows duplicate recognizing events for the local user and remote user both...so logs shown are like

console.error(partiId + ' - recognizing text = ', e.result.text);
console.error(partiId + ' - recognized text = ', e.result.text);
console.error('LOCAL recognizing text=>', e.result.text);
console.error('LOCAL recognized text=>', e.result.text);

So it is taking one audio stream only for multiple users after mute and unmute.
**After reloading the page it works fine again until the next mute/unmute.**

**We were using free plan in which 1 concurrent request was mentioned, we changed that plan to standard in which 100 concurrent request for Base model is mentioned. But that also did not fix the issue so now we changed it back to free plan.**


As per our use case, **we have more than one participants connected with their own device**, situated remotely. so will https://docs.microsoft.com/en-in/azure/cognitive-services/speech-service/multi-device-conversation **be more suitable approach** to user rather than speechRecogniser or TranslationRecognizer with multiple objects ?

**Comment by glharper** [comment] 2021-06-15 20:53
@jahnviss Conversation Transcription may indeed be a better fit for what you're attempting here, with the a server host (not sure if this would be Local in your case?) setting up the conversation itself, then joining, and then all client participants joining the conversation that the remote host has set up. There's a guide to setting this up in JS [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-conversation-transcription?pivots=programming-language-javascript).

Having said that, the issue you're having with the current code is with re-enabling the microphone audio streams, and I don't think the SDK is actually at fault. May I ask why you're stopping recognition on mute? If the mic is muted, no audio data will be written to the stream (and then sent for recognition), correct?

**Comment by jahnviss** [comment] 2021-06-16 07:00
Thanks for your suggestion of Conversion Transcription. I will try that.

I have already tried with not using stop/start continuousRecognitionAsync when mic is turned mute/unmute. But in our application when call gets connected, there will be a button called Live Caption so clicking on it this feature will be turned on.
So now again user clicks on it, this feature will be turned OFF. so if not on Mic mute/unmute , I will have to use stop/start continuousRecognitionAsync functions on this feature OFF. Even I tried not using stop/start continuous function on feature off, but at least I will have to use stop on call end. so now next if user re-connects call without refreshing the page, startContinuouseAsync will be used...and again I will get the same issue.

On feature Off/ON, call disconnect and reconnect without refresh issue produces.
The issue doesn't occur only if page is refreshed after the use of stopContinuousAsync function

**Comment by jahnviss** [comment] 2021-06-22 08:43
Any feedback on my last comment? Its not about mute and unmute, whenever stopContinuous and startContinuous called on Live Caption feature off/on , that time also bug exist.

**Comment by glharper** [comment] 2021-06-23 14:10
@jahnviss I'm attaching a sample test page using two recognizers and start/stopContinuousRecognition calls for both on a microphone input. It seems to work for me, can you confirm it works for you?
[from-mic-1120-June-2021.html.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6702440/from-mic-1120-June-2021.html.txt)

**Comment by glharper** [comment] 2021-07-21 23:50
@jahnviss The latest version of SpeechSDK for JavaScript, which includes a fix for this issue, is now live, available for Node via npm install ([npm page here](https://www.npmjs.com/package/microsoft-cognitiveservices-speech-sdk)) and browser via include (https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@latest/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js
). Thanks again for using Speech SDK!

**Closed by glharper** 2021-07-21 23:50 UTC
Labels: question
