### ISSUE TITLE
Language Identification from Blob Triggered Azure Function

### ISSUE THREAD

**Issue by harounshehata** [Azure-Samples/cognitive-services-speech-sdk#1299] opened 2021-11-09 11:48 UTC
**Describe the bug**
Goal is to identify the language from a Blob Stream inside of an Azure Function using the SourceLanguageRecognizer.
I have tried two approaches which did **not** work.
1. Using recognize_one() with a SAS URI to the blob
2. Using start_continuous_recognition() with a PushAudioInputStream

**To Reproduce**
1. Recognizing with Blob Sas URI 
```
def language_identification(locale, blobname):
    languages.append(locale)
    speech_config = speechsdk.SpeechConfig(subscription=subscription_key, region=service_region)
    speech_config.set_property(property_id=speechsdk.PropertyId.SpeechServiceConnection_SingleLanguageIdPriority,
                               value='Accuracy')
    auto_detect_source_language_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=languages)
    audio_input = speechsdk.audio.AudioConfig(filename=blobname)
    speech_language_detection = speechsdk.SourceLanguageRecognizer(speech_config=speech_config,
                                                                   auto_detect_source_language_config=auto_detect_source_language_config,
                                                                   audio_config=audio_input)
    result = speech_language_detection.recognize_once()
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        logging.info("RECOGNIZED: {}".format(result))
        locale = result.properties[speechsdk.PropertyId.SpeechServiceConnection_AutoDetectSourceLanguageResult]
        logging.info("Detected Language: {}".format(locale))
        return locale
    elif result.reason == speechsdk.ResultReason.NoMatch:
        logging.warning("No speech could be recognized - use the phone country code as main language")
        return locale
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        logging.info("Speech Recognition canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            raise Exception("Error details: {}".format(cancellation_details.error_details))
```
Where blobname is a correct Sas URI to the .wav file in the Azure Storage Account
Here I receive the following error:
![image](https://user-images.githubusercontent.com/14542540/140916554-c84281a7-4dc1-4e87-b501-868e0e5c581b.png)
seems like the SDK is not able to handle remote file locations

2. Tried to read the audio Stream I receive from the Blob Storage trigger in the Azure Function

```
def language_identification_stream(locale, audioBlob):
    languages.append(locale)
    speech_config = speechsdk.SpeechConfig(subscription=subscription_key, region=service_region)
    speech_config.set_property(property_id=speechsdk.PropertyId.SpeechServiceConnection_SingleLanguageIdPriority,
                               value='Accuracy')
    speech_config.set_property(speechsdk.PropertyId.Speech_LogFilename, "./LogFile.txt")
    auto_detect_source_language_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=languages)
    audio_steam = speechsdk.audio.PushAudioInputStream()

    audio_input = speechsdk.audio.AudioConfig(stream=audio_steam)
    source_language_recognizer = speechsdk.SourceLanguageRecognizer(speech_config=speech_config,
                                                                   auto_detect_source_language_config=auto_detect_source_language_config,
                                                                   audio_config=audio_input)
    done = False
    detailResult = ""
    def stop_cb(evt):
        """callback that signals to stop continuous recognition upon receiving an event `evt`"""
        print('CLOSING on {}'.format(evt))
        nonlocal done
        done = True

    def audio_recognized(evt):
        """
        callback that catches the recognized result of audio from an event 'evt'.
        :param evt: event listened to catch recognition result.
        :return:
        """
        if evt.result.reason == speechsdk.ResultReason.RecognizedSpeech:
            logging.info("RECOGNIZED: {}".format(evt.result.properties))
            if evt.result.properties.get(speechsdk.PropertyId.SpeechServiceConnection_AutoDetectSourceLanguageResult) == None:
                logging.info("Unable to detect any language")
            else:
                detectedSrcLang = evt.result.properties[speechsdk.PropertyId.SpeechServiceConnection_AutoDetectSourceLanguageResult]
                jsonResult = evt.result.properties[speechsdk.PropertyId.SpeechServiceResponse_JsonResult]
                nonlocal detailResult
                detailResult = json.loads(jsonResult)
                startOffset = detailResult['Offset']
                duration = detailResult['Duration']
                if duration >= 0:
                    endOffset = duration + startOffset
                else:
                    endOffset = 0
                logging.info("Detected language = " + detectedSrcLang + ", startOffset = " + str(startOffset) + " nanoseconds, endOffset = " + str(endOffset) + " nanoseconds, Duration = " + str(duration) + " nanoseconds.")
                
    # Connect callbacks to the events fired by the speech recognizer
    source_language_recognizer.recognized.connect(audio_recognized)
    source_language_recognizer.session_started.connect(lambda evt: print('SESSION STARTED: {}'.format(evt)))
    source_language_recognizer.session_stopped.connect(lambda evt: print('SESSION STOPPED {}'.format(evt)))
    source_language_recognizer.canceled.connect((lambda evt: print('CANCELED {}'.format(evt))))
    # stop continuous recognition on either session stopped or canceled events
    source_language_recognizer.session_stopped.connect(stop_cb)
    source_language_recognizer.canceled.connect(stop_cb)

    # Start continuous speech recognition
    source_language_recognizer.start_continuous_recognition()
    
    try:
        while(True):
            readSamples = audioBlob.read(size= 10000)
            if not readSamples:
                print("Print Writing Stream done")
                logging.info("Logging Writing Stream done")
                break
            audio_steam.write(readSamples)
            time.sleep(.1)
    finally:
        audio_steam.close()
        audioBlob.close()
        while not done:
            time.sleep(.5)

    source_language_recognizer.stop_continuous_recognition()
    return detailResult
```

Where _languages_ is an array of 4 language codes and _audioBlob_ is of type azure.functions.blob.InputStream
Error message:
![Capture_LI](https://user-images.githubusercontent.com/14542540/140920046-fc56d17c-8633-4b91-a8bd-391b62a2fffa.jpg)

**Expected behavior**
Expecting a correct response from the SourceLanguageRecognizer for either stream or remote file.

**Version of the Cognitive Services Speech SDK**
1.19.0

**Platform, Operating System, and Programming Language**
 - Linux Azure Function v3
 - Programming language: Python 3.9.7

**Additional context**

[LogFile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7504401/LogFile.txt)
[harounitalien_+396648414202_0064030f5e74b281-11111.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7510811/harounitalien_%2B396648414202_0064030f5e74b281-11111.zip)

**Comment by jhakulin** [comment] 2021-11-09 17:44
@harounshehata Thanks for report. Based on the log, result is NoMatch, which probably means the data fed into push stream is silence (or not fully correct). Are you pushing stream from Blob storage containing wave files ? Could you provide one example wave file for us (You can attach it to this issue.) ? Does the sample work if you run it locally without Azure function?

**Comment by harounshehata** [comment] 2021-11-10 07:55
@jhakulin the file works when using the transcription service directly with the source language specified explicitly, additionally the language recognition also works if the application (using recognize_once() and local filepath) is run locally without Azure function.

**Comment by jhakulin** [comment] 2021-11-10 23:34
@harounshehata If the Azure function project runs locally ok, the problem might be due to connections are not set correctly inside Azure portal, so check that information about connection bindings you have set in local.settings.Json file in your project are set also in the Azure portal also, (e.g. input and output connections to Azure blob storage(s))

**Comment by harounshehata** [comment] 2021-11-11 08:27
@jhakulin no you miss understood me. The Azure Function does not run successfully neither in the Portal nor locally. This is language identification part is just a small section we were trying to add to an already  running Azure Function that uses the .wav files from the Blob Storage to Transcribe and Translate them successfully. Connections, files, deployment and everything else works, we have already proven that by using the Transcription and Translation service of the speech sdk!
We now wanted to make the function more generic by first detecting the language of the .wav file before we transcribe and translate it. We have tried the two above mentioned approaches:
1.
We **never** got the language identification working using a Stream, in our case we get a azure.functions.blob.InputStream from the Blob Trigger and convert this to an **PushAudioInputStream()** to try and get it working, but as you can see from the logs the SpeechRecognitionService always returns a CANCELED event. Without any details to why it canceled it.

2.
We also tried to to use the **recognize_once()** method to give the service the complete file and once and get the recognized language back. In our context of the Azure Function we don't have the File locally but in a blobstorage, we have created a SAS URI for this specific blob see line, where blobname is a complete SAS URI to the .wav file in the Azure Storage Account.
`audio_input = speechsdk.audio.AudioConfig(filename=blobname)`
This returns and error and it seems like the Service is not able to handle locations on a remote storage...
Just to make sure that we are doing everything correctly we have create a simple local python script and used the **recognize_once()** method to point to the same .wav file, but this time it was stored on our local machine. This returned a sucessful results, leading us to believe that the .wav file as well as the code works correctly and that it is in fact the SAS URI that breaks our function.

It might make things more clear if you try to replicate the environment by:

1. Creating a Storage Account
2. Creating a python Azure Function with a Blob Trigger
3. Uploading a .wav file to the Storage account
4. Using the InputStream from the Blob Trigger to Identify the language with the speech sdk

**Comment by jhakulin** [comment] 2021-11-15 03:27
@harounshehata Thanks for the details and we can reproduce the issue. There is some issue with the stream input when using SourceLanguageRecognizer. We will let you know once we have a fix for that.

**Comment by jhakulin** [comment] 2021-11-15 04:04
@harounshehata Actually I backup a little as source_language_recognizer.recognize_once() works with the blob trigger, however I had problems with continuous version and callbacks but that might be separate problem.
Also I changed the wav file to 16kHz mono and shortened it to 5sec (attached the file)

Please try the function below with the attached wave file

```
# Specify the AutoDetectSourceLanguageConfig, which defines the number of possible languages
auto_detect_source_language_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=["it-IT", "en-US"])

def main(myblob: func.InputStream):
    logging.info(f"Python blob trigger function processed blob \n"
                 f"Name: {myblob.name}\n"
                 f"Blob Size: {myblob.length} bytes")

    speech_language_detection_once_from_blob(myblob)
    logging.info(f"exit function\n")

def speech_language_detection_once_from_blob(myblob):
    speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
    speech_config.set_property(speechsdk.PropertyId.Speech_LogFilename, "log.txt")

    # Set the Priority (optional, default Latency, either Latency or Accuracy is accepted)
    speech_config.set_property(property_id=speechsdk.PropertyId.SpeechServiceConnection_SingleLanguageIdPriority, value='Latency')

    # setup the audio stream
    stream = speechsdk.audio.PushAudioInputStream()
    audio_config = speechsdk.audio.AudioConfig(stream=stream)

    # Creates a source language recognizer using a file as audio input, also specify the speech language
    source_language_recognizer = speechsdk.SourceLanguageRecognizer(
        speech_config=speech_config, auto_detect_source_language_config=auto_detect_source_language_config, audio_config=audio_config)

    # push data to sdk
    n_bytes = 32000
    try:
        while(True):
            frames = myblob.read(n_bytes // 2)
            print('read {} bytes'.format(len(frames)))
            if not frames:
                break

            stream.write(frames)
            time.sleep(.1)
    finally:
        # stop recognition and clean up
        myblob.close()
        stream.close()

    # Starts speech language detection, and returns after a single utterance is recognized. The end of a
    # single utterance is determined by listening for silence at the end or until a maximum of 15
    # seconds of audio is processed. It returns the detection text as result.
    # Note: Since recognize_once() returns only a single utterance, it is suitable only for single
    # shot detection like command or query.
    # For long-running multi-utterance detection, use start_continuous_recognition() instead.
    result = source_language_recognizer.recognize_once()

    # Check the result
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
        logging.info("RECOGNIZED: {}".format(result))
        detectedSrcLang = result.properties[speechsdk.PropertyId.SpeechServiceConnection_AutoDetectSourceLanguageResult]
        output = detectedSrcLang
        logging.info("Detected Language: {}".format(detectedSrcLang))
    elif result.reason == speechsdk.ResultReason.NoMatch:
        logging.info("No speech could be recognized: {}".format(result.no_match_details))
    elif result.reason == speechsdk.ResultReason.Canceled:
        cancellation_details = result.cancellation_details
        logging.info("Speech Language Detection canceled: {}".format(cancellation_details.reason))
        if cancellation_details.reason == speechsdk.CancellationReason.Error:
            logging.info("Error details: {}".format(cancellation_details.error_details))

    logging.info(f"EXIT speech_language_detection_once_from_blob\n")
```
[harounitalien_mono_5sec.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7535779/harounitalien_mono_5sec.zip)

**Comment by harounshehata** [comment] 2021-11-15 08:30
@jhakulin It works when using the 'Latency' model and you're attached 16kHz mono file.
With my original file and the 'Latency' model he recognizes czech (cs-CZ) and using the 'Accuracy' model he is not able to detect any language.

**Comment by harounshehata** [comment] 2021-11-15 08:32
Is there a way to apply to audio transformation (16kHz mono and shortened) to the stream I receive in the Azure Function?
and should the same preprocessing be applied to the Transcribe model of the speech sdk (so far the transcriptions with the original audio files looked good)?

**Comment by jhakulin** [comment] 2021-11-15 20:28
@harounshehata Problem seems to be more related to LID service not working optimally with the stereo (2 channel) streams. With mono stream (and even when using the original samplerate 22.050kHz you had), the accuracy model works ok.

**Comment by jhakulin** [comment] 2021-11-15 22:09
@harounshehata In the meantime when we are checking the service side support for stereo, using numpy library you should be able to convert the stereo data to mono. For example. using following works with your original wav file:

```
    # push data to sdk
    n_bytes = 32000
    try:
        while(True):
            frames = myblob.read(n_bytes // 2)
            mono_data = np.frombuffer(frames, dtype='<i2')
            if not frames:
                break
            stream.write(mono_data)
            time.sleep(.1)
    finally:
        # stop recognition and clean up
        myblob.close()
        stream.close()
```
You need to add `import numpy as np` and numpy in the requirements.txt

**Comment by jhakulin** [comment] 2021-11-16 02:47
@harounshehata You can use numpy library to do basic data manipulation, the following code I tested converts the original audio data (22.050kHz stereo PCM) to 22.050kHz mono. With that modification I get correct results with Accuracy model when using your original wav file

```
    # push data to sdk
    n_bytes = 32000
    try:
        while(True):
            frames = myblob.read(n_bytes // 2)
            np_data = np.frombuffer(frames, dtype='<i2')
            mono_data = np_data[::2]
            mono_data = np.ascontiguousarray(mono_data)
            if not frames:
                break
            stream.write(mono_data)
            time.sleep(.1)
    finally:
        # stop recognition and clean up
        myblob.close()
        stream.close()
```
In order to use numpy, you need to `import numpy as np` and add `numpy` in requirements.txt

We are checking the service side support for stereo file in the meantime.

**Comment by harounshehata** [comment] 2021-11-16 17:52
@jhakulin thank you it works when converting it to a mono stream, I have some general questions before we close this issue:

1. Why do I have to iterate through the stream an read 16000 bytes in each iteration, I know that the amount of bytes are dictated by the sample rate, but we are using the recognize_once() method, can't I just read all the content of the stream in one go and write it to the PushAudioStream?
2. Is there a way to improve the quality, some of the files I tested with could not be recognized
3. What should I do if I have more that 4 languages in my pool? There is no numeric confidence value in the response. So I can't just rerun it multiple times with different languages and take the one with the best confidence.

**Comment by jhakulin** [comment] 2021-11-16 18:03
@harounshehata Glad to know it helps, 
1) You do not need to do that as we get here the whole blob at once, please see the modified examples in the previous comments.
2) Were you using Accuracy or Latency mode ? Could you please share some of the files, which does not work?
3) Will check

**Comment by harounshehata** [comment] 2021-11-16 18:31
I was using the Accuracy model, here are the files
[audioSamples.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7548928/audioSamples.zip)
Thank you for checking 👍

**Comment by jhakulin** [comment] 2021-11-18 19:52
@harounshehata Audio samples (in audioSamples.zip) are 8kHz and in 14bit precision. LID service expects 16bit precision. After converting the files (using sox) to 16bit precision, LID produces correct results. 
Related to your question if you have more than 4 languages, please see the documentation below, recommendation is to use continuous recognition in that case.
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-automatic-language-detection?pivots=programming-language-python
Let me know if this helps.

**Comment by jhakulin** [comment] 2021-11-20 00:42
Closing this issue as answered and solution given. @harounshehata Thanks a lot for the details, we will improve our documentation and LID service side to allow multiple formats.

**Closed by jhakulin** 2021-11-20 00:42 UTC

**Comment by harounshehata** [comment] 2021-11-21 19:37
You have stated earlier that the continuous recognition seems to have and issue, so I guess our choice is to wait till it's fixed right.
Anyways, thanks a lot for your support and the great insight into the service!
