### ISSUE TITLE
Using the Python sample, able to generate captions for MP3 and WMV but MP4 is giving ERROR

### ISSUE THREAD

**Issue by SudheeshWarrier** [Azure-Samples/cognitive-services-speech-sdk#2019] opened 2023-07-20 13:56 UTC
Code sample: https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/scenarios/python/console/captioning

I am using this sample here to create captions for videos I have. I am able to generate captions for MP3 and WMV files. But for MP4, it is not working. It is not giving any specific error, just that the result is empty.

The code goes into this line ones: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/633b8fd841a98deeb8b22319271487dffd518755/scenarios/python/console/captioning/captioning.py#L340

And then the recognition is automatically stopped and the control goes back to:
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/633b8fd841a98deeb8b22319271487dffd518755/scenarios/python/console/captioning/captioning.py#L183C19-L183C19
and gives list index out of range error:

`last_caption = captions[-1]`

I tried it with two different versions of GStreamer (gstreamer-1.0-msvc-x86_64-1.18.4.msi and gstreamer-1.0-msvc-x86_64-1.18.3.msi), but no luck.

**Comment by jpalvarezl** [comment] 2023-07-20 16:50
Thank you for reporting! I am opening up this issue to the rest of the team to see how we can best assist.

**Comment by SudheeshWarrier** [comment] 2023-07-21 03:57
Also, note that I am running this on Windows 10

**Comment by jpalvarezl** [comment] 2023-07-21 19:31
Hello again, after asking around the team for possible ways to figure this out:
- It is possible that GStreamer is not able to decode the format of the audio of your MP4 file. You can use this tool to figure that out: https://mediaarea.net/en/MediaInfo 
- Are you able to try this with in the C# SDK? This would help discard if it's a problem with the sample itself or the Python API for the SDK.
- Otherwise, if you are able to share with us the sample (or fragment of it), we can have a closer look.

**Comment by jhakulin** [comment] 2023-08-18 17:10
@SudheeshWarrier MP4 requires to use ANY format when configuring the compressed audio input for Speech SDK. Did you use that?

**Comment by chschrae** [comment] 2023-08-18 23:16
Closing assuming the issue is resolved since there hasn't been any customer activity recently. Feel free to re-open if necessary.

**Comment by loomlike** [comment] 2024-02-25 06:35
@chschrae I'm having the same issue. 
I used `ANY` for mp4.  The output object `azure.cognitiveservices.speech.SpeechRecognitionResult` contains the following data:
```
result.reason: <ResultReason.Canceled: 1>
result.cancellation_details.error_details: 'Timeout: no recognition result received SessionId: 82f5014690224c189d4faa3e365f28ed'
result.cancellation_details.code: <CancellationErrorCode.ServiceTimeout: 6>
```

When I extracted mp3 audio from the mp4 file using `moviepy` python package and use it w
/ compression format MP3, it worked.

**Comment by chschrae** [comment] 2024-02-26 17:34
@jhakulin do you have any advice for @loomlike?

**Comment by pankopon** [comment] 2024-03-09 01:36
@loomlike See attached for an example script using `AudioStreamContainerFormat.ANY`.
[mp4test.zip](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/14544527/mp4test.zip)
Tested with MP4 video from https://vimeo.com/665800536 but also works with MP3 audio files etc.
Used WinPython 3.11 with azure-cognitiveservices-speech 1.36.0 on Windows 10, GStreamer set up as in
https://learn.microsoft.com/azure/ai-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=windows&pivots=programming-language-python#gstreamer-configuration

**Comment by pankopon** [comment] 2024-03-11 18:33
Closed as answered, please open a new issue if more support is needed.

**Closed by pankopon** 2024-03-11 18:33 UTC
Labels: in-review, pending close
