### ISSUE TITLE
Failed tlsio_options_set - iOS

### ISSUE THREAD

**Issue by Lykos94** [Azure-Samples/cognitive-services-speech-sdk#1148] opened 2021-06-19 19:27 UTC
**Describe the bug**

Trying to compile a Unity app that contains Cognitive Services Speech SDK version 1.17 on iOS results in the following error when trying to invoke the service within the app. On Android and the Standalone Player it works perfectly, the issue only occurs on iOS.

```
Error: Time:Sat Jun 19 21:18:03 2021 File:/Users/runner/work/1/s/external/azure-c-shared-utility/pal/ios-osx/tlsio_appleios.c Func:tlsio_appleios_setoption Line:730 Failed tlsio_options_set

Error: Time:Sat Jun 19 21:18:03 2021 File:/Users/runner/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:uws_client_set_option Line:2157 xio_setoption failed.
```

**To Reproduce**
1. Start project Build from Unity
2. Build application from XCode 
3. Run on iPhone 
4. Error occurs as soon as the Speech SDK is called (not on start, only when used)

**Expected behavior**
The SDK should not crash

**Version of the Cognitive Services Speech SDK**
Microsoft.CognitiveServices.Speech.1.17.0.unitypackage

**Platform, Operating System, and Programming Language**
 - OS: iOS 14 - target build 11.0
 - Programming language: C#

**Additional context**

```
Error: Time:Sat Jun 19 21:18:03 2021 File:/Users/runner/work/1/s/external/azure-c-shared-utility/pal/ios-osx/tlsio_appleios.c Func:tlsio_appleios_setoption Line:730 Failed tlsio_options_set

Error: Time:Sat Jun 19 21:18:03 2021 File:/Users/runner/work/1/s/external/azure-c-shared-utility/src/uws_client.c Func:uws_client_set_option Line:2157 xio_setoption failed.
```

**Comment by jhakulin** [comment] 2021-06-21 17:47
@Lykos94 Thanks for the report. I am investigating the issue, I could not see any problems with https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone quickstart with Speech SDK release 1.17.0 and iOS 13.3. I will update my device to iOS14 and see if that makes a difference.

**Comment by jhakulin** [comment] 2021-06-22 01:55
@Lykos94 I updated to latest iOS 14 version and Xcode as well and tested https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/from-microphone sample using 1.17.0 release which worked ok on my iPhone. 
Can you reproduce the problem with that sample?

**Comment by Lykos94** [comment] 2021-06-22 02:11
@jhakulin Thank you for your follow up. I’ll make some more tests as soon as possibile and I’ll come back to you with more information.

**Comment by Lykos94** [comment] 2021-06-23 21:43
@jhakulin Hello again, I indeed managed to reproduce the same error on the quickstart repository. This is what I did:
+ Clone the repository (i used [https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/unity/text-to-speech) which should be the same, and I mainly need TTS)
+ Opened the project in Unity (version 2021.1.12f1) with the specified target iOS
+ Imported the Unity package (Microsoft.CognitiveServices.Speech.1.17.0.unitypackage)
+ Opened the HelloWorld.cs code to add my Azure credentials for TTS to work
+ Opened Build settings and run the build
+ Opened the finished build in XCode
+ Signed the project in Signing and Capabilities by checking Automatically manage signing and selecting my company profile
+ Connected my iPhone
+ Pressed Play on XCode

The error happens when i press the UI Button (the "Speak!" one) and it is exactly the same as reported in the previous comment.I have honestly no idea of what I'm missing.

Here are also some more information:
+ I'm using a MacBook Pro 13 M1 processor
+ XCode version 12.5.1
+ Unity 2021.1.12.f1
+ iPhone XS with iOS 14.6

I also tried to check the repository of the error ([https://github.com/Azure/azure-c-shared-utility/blob/master/pal/ios-osx/tlsio_appleios.c](https://github.com/Azure/azure-c-shared-utility/blob/master/pal/ios-osx/tlsio_appleios.c)) but I'm not getting what's wrong

Thanks in advance for your help

**Comment by jhakulin** [comment] 2021-11-15 17:10
@Lykos94 I made some recent testing on 1.19.0 Speech SDK release, Mac M1, using the Unity 2020.3.22f1 with iPhone 8 and I could not reproduce the problem, so probably the reason is somehow specific to your environment. 
Do you see any problems if you use WLAN connectivity on your iPhone ? 

Also If you still have possibility, could you please try to provide a trace from your Unity app ?
```
    string logFile = Application.persistentDataPath + "/logFile.txt";
    config.SetProperty(PropertyId.Speech_LogFilename, logFile);
```

**Comment by jhakulin** [comment] 2021-11-19 02:33
Closing as not reproduced, we can reopen if there is more information provided later

**Closed by jhakulin** 2021-11-19 02:33 UTC
Labels: in-review
