### ISSUE TITLE
Segmentation fault and CPU spike with websocket 502 error

### ISSUE THREAD

**Issue by santoojoshi** [Azure-Samples/cognitive-services-speech-sdk#1029] opened 2021-04-05 12:35 UTC
**Describe the bug**
If SpeechSDK is not establishing the websocket(502 error) with azure server, CPU usage is double than azure server is working fine

**To Reproduce**
1. in /etc/hosts  configure a reachable ip address w.x.y.z.    
w.x.y.z eastasia.api.cognitive.microsoft.com
w.x.y.z eastasia.tts.speech.microsoft.com
w.x.y.z eastasia.stt.speech.microsoft.com

2. Run a Speech To Text continuous recognition 

**Expected behavior**
Call should be CANCELLED without taking much CPU cycles

**Version of the Cognitive Services Speech SDK**
1.14

**Platform, Operating System, and Programming Language**
 - OS: CentOS Linux release 7.7.1908
 - Hardware - x64, x86, ARM, ...
 - Programming language: C++

**Additional context**
 
We are experiencing multiple segmentation fault in load runs of continuous speech recognition in SpeechSDK.  Load is of 200 concurrent continuous speech recognition. Load is run on a k8s environment with multiple pods having 4core CPU and  3GB memory each.
 
Each successful recognition is for 25 sec and for few recognitions are stopped  at 15th seconds using following methods:

Following Configurations are used 
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-USPPollingInterval", "300");
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-BytesPerFrame", "4800");
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("BufferDataSizeInBytes", "32000");
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-StopRecognitionTimeoutInSeconds", "1");

   recog_channel->azureASRChannelConfig.azureSpeechRecognizer->StartContinuousRecognitionAsync().wait();
 
   recog_channel->azureASRChannelConfig.azureSpeechRecognizer->StopContinuousRecognitionAsync();
 
   recog_channel->azureASRChannelConfig.azureSpeechRecognizer.reset();
   recog_channel->azureASRChannelConfig.azureAudioConfig.reset();
   recog_channel->azureASRChannelConfig.azurePushAudioInputStream.reset();
   recog_channel->azureASRChannelConfig.azureASRSpeechConfig.reset();
 

We believe these crashes are because of spike in CPU usage, when there is a network connectivity problem towards azure server.

So we ran a single call with configuring a dummy reachable IP address. This causes spike in CPU usage of the system.

Attached the azure SDK logs…
azurelogs_failure_502_error : CPU usage is double than success case. May be because of RETRY of connection establishmnet
azurelogs_success
backtrace
[azurelogs_failure_502_error.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6258131/azurelogs_failure_502_error.txt)
[azurelogs_success.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6258133/azurelogs_success.txt)
[backtrace.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6258134/backtrace.txt)
[azurelogs_failure_502_error.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6258140/azurelogs_failure_502_error.txt)
[azurelogs_success.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6258142/azurelogs_success.txt)
[backtrace.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6258143/backtrace.txt)

**Comment by ralph-msft** [comment] 2021-04-05 23:39
Thanks for reporting this issue. You've provided everything we need to look into this and we're tracking the investigation on the Speech SDK team's backlog. To keep the open issues list fresh, we'll close this issue while it's prioritized and developed against and report back here once we have an update. Please subscribe to the issue to get the latest, and please re-open this issue if  there's new/different information.

**Comment by oscholz** [comment] 2021-04-13 16:32
@santoojoshi does this happen in the latest 1.16 release as well?

**Comment by glharper** [comment] 2021-04-13 16:39
@santoojoshi Are you able to reproduce this issue with version 1.16? If so, would you be kind enough to attach logs from the 1.16 repro? Thanks.

**Comment by santoojoshi** [comment] 2021-04-30 09:19
@glharper  Sorry for the late response.
Please find the attachments for azure SDK 16.0 logs 
azurelogs_sdk16.0_502_high_cpu.txt :  If Speech server is no responding CPU usage is higher than success case. May be because of RETRY of connection establishment. Is there any configuration for limiting the RETRY number or duration, if azure speech server is not responding?

azurelogs_sdk16.0_success.txt


[azurelogs_sdk16.0_502_high_cpu.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6404220/azurelogs_sdk16.0_502_high_cpu.txt)
[azurelogs_sdk16.0_success.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6404222/azurelogs_sdk16.0_success.txt)

**Comment by amitkumarshukla** [comment] 2021-05-05 22:24
@santoojoshi You can configure the retry parameter using the following 
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-Error-MaxRetryCount", "1");
right now by default it is set to 4.

You can also set the time interval using the following 
recog_channel->azureASRChannelConfig.azureASRSpeechConfig->SetProperty("SPEECH-Error-RetryDurationMS", "50");
Right now it is set to 250 ms by default.

Please set the above value to limit the retry. 

Do let us know if you are still facing the segmentation fault

**Comment by pankopon** [comment] 2021-05-14 18:34
Closed since mitigations have been suggested and there were no further updates. We have work items on the internal backlog to avoid CPU utilization increase when connection fails, and they are tentatively scheduled for the next sprint at the moment. Please open a new issue if you need more support.

**Closed by pankopon** 2021-05-14 18:34 UTC
Labels: in-review, pending close
