### ISSUE TITLE
SPXERR_MIC_ERROR Calling SpeechRecognizer.StartContinuousRecognitionAsync() on iOS 14.8.1?

### ISSUE THREAD

**Issue by mtaulty** [Azure-Samples/cognitive-services-speech-sdk#1308] opened 2021-11-11 16:10 UTC
**Describe the bug**

I have a Xamarin application running on iOS where I am using SpeechRecognizer.StartContinuousRecognitionAsync() and finding that it is throwing an exception "Exception with an error code: 0x15 (SPXERR_MIC_ERROR)" when running on a device. 

I find that it runs in the iOS simulator ok and speech is recognized there and the same code runs on Android device/emulator ok.

It is noticeable that if the microphone on the iOS device is already active (e.g. being used for a Teams call) then the call to StartContinuousRecognitionAsync() works and I get speech recognised.

I am not all sure that this is a bug rather than my error but I would appreciate help in diagnosing.

I have NSMicrophoneUsageDescription listed in my info.plist and the device prompts for mic access and the status I get back seems to suggest that I do have mic access but maybe that isn't working the way I think it is.

**To Reproduce**
1. I have calls to check and/or request then check microphone permissions.
2. I have a call to create a SpeechConfig using SpeechConfig.FromSubscription(key, region)
3. I have a call to AudioConfig.FromDefaultMicrophoneInput()
4. I create a SpeechRecognizer passing the SpeechConfig, Language and AudioConfig.
5. I call SpeechRecognizer.StartContinuosRecognitionAsync()

I am sure that this is a well-trodden and tested code-path so perhaps there is something that is missing from my setup.

**Expected behavior**
Speech recognition as happens on iOS simulator, Android emulator, Android device.

**Version of the Cognitive Services Speech SDK**
.NET SDK 1.17.0 (also tried 1.19.0)

**Platform, Operating System, and Programming Language**
 - OS: iOS 14.8.1
 - Hardware - ARM
 - Programming language: C#/Xamarin

**Additional context**
Log file attached - I think the problem occurs in microphone_pump_base.cpp:127 on line 607 of this file but I could be reading it incorrectly. 

[iOSDeviceNotWorking.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/7521702/iOSDeviceNotWorking.txt)

**Comment by jhakulin** [comment] 2021-11-11 22:02
@mtaulty  As discussed offline, could you check if you can reproduce the problem with the quickstart sample
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp/xamarin
This is to narrow down if the problem is in the app side or not.

**Comment by jhakulin** [comment] 2021-11-15 18:53
Closing the issue as not reproduced. Please let me know if you have still problems.

**Closed by jhakulin** 2021-11-15 18:53 UTC
