### ISSUE TITLE
Background audio SSML tag not working

### ISSUE THREAD

**Issue by johnmalatras** [Azure-Samples/cognitive-services-speech-sdk#1492] opened 2022-05-10 22:54 UTC
### **Describe the bug**

Synthesizing speech with SSML containing a `mstts:backgroundaudio` returns an empty response (0B `audio/mpeg`) 100% of the time

### **To Reproduce**

**Error case**
Synthesize the following:
```
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xml:lang="en-US">
    <mstts:backgroundaudio src="https://www2.cs.uic.edu/~i101/SoundFiles/taunt.wav" volume="0.7" fadein="3000" fadeout="4000"/>
    <voice name="en-US-JennyNeural">
        About a month and a half ago, I started noticing my friends in the tech startup world getting grumpier. Founders were suddenly saying that they were having trouble raising money, and VCs were grumbling that they couldn’t find good deals.
    </voice>
</speak>
```

Response: 200 w/ 0B `audio/mpeg`

**Control**
Synthesize the following:
```
<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xml:lang="en-US">
    <voice name="en-US-JennyNeural">
        About a month and a half ago, I started noticing my friends in the tech startup world getting grumpier. Founders were suddenly saying that they were having trouble raising money, and VCs were grumbling that they couldn’t find good deals.
    </voice>
</speak>
```

Response: 200 w/ 150KB `audio/mpeg` that is playable

### **Expected behavior**
A playable audio file is returned with both background audio and synthesized speech

### **Version of the Cognitive Services Speech SDK**
REST endpoints

### **Platform, Operating System, and Programming Language**
 - OS: macOS
 - Hardware M1 ARM
 - Programming language: REST

**Comment by yulin-li** [comment] 2022-05-12 16:15
See my reply here (https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/528#issuecomment-1125179300), this issue is tracked and could be repro-ed only for 8kHz output formats.

We are investigating this issue, and meanwhile, you can try to use other formats as a workaround

**Comment by johnmalatras** [comment] 2022-05-12 16:41
@yulin-li I'm seeing this for `audio-48khz-96kbitrate-mono-mp3 ` - I hadn't even tried 8kHz formats

**Comment by yulin-li** [comment] 2022-05-13 02:44
ok.. several formats are not supported. Could you try audio-24khz-48kbitrate-mono-mp3 ?

**Comment by pankopon** [comment] 2022-06-24 01:11
Set as duplicate of #528 that has the latest updates and it's understood this is an issue on the service side.

**Closed by pankopon** 2022-06-24 01:11 UTC
Labels: bug, duplicate, tts, accepted
