### ISSUE TITLE
speech_recognizer.stop_continuous_recognition() blocks the parent thread [python]

### ISSUE THREAD

**Issue by Aaron-Yue** [Azure-Samples/cognitive-services-speech-sdk#331] opened 2019-08-03 12:01 UTC
I implement the speech recognition according to the "speech_recognition_with_push_stream()" method in the samples python code. 
The main thread will create a sub-thread when a new audio comes by listening to a redis queue. The sub-thread inherit the "threading.Thread" and the run() method is like the "speech_recognition_with_push_stream()" samples code.
But when the recognition is done and the speech_recognizer.stop_continuous_recognition() func is called, the whole program will be blocked for about 10s. The main thread listening to the redis queue will be blocked too.
I want to know what does the "speech_recognition_with_push_stream()" function do. and how can I fix this problem? Or it is just the bug in my implementation.

**Comment by chlandsi** [comment] 2019-08-05 07:14
If you want to avoid waiting for the call to `stop_continuous_recognition`, you can use the [async version](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.recognizer?view=azure-python#stop-continuous-recognition-async--), which returns immediately. The implementation of the feature waits for confirmation from the service that recognition is stopped. In the async version of the call you can get notified of this event by the future object it returns.

**Comment by Aaron-Yue** [comment] 2019-08-05 09:37
@chlandsi
Thank you for your answer! Do you have a complete sample code for the async version?
I try stop_continuous_recognition_async() func, but it still block the process.

**Comment by chlandsi** [comment] 2019-08-05 10:55
I can't reproduce this behavior. Can you share the relevant parts of your code?

**Comment by Aaron-Yue** [comment] 2019-08-05 11:04
I just replace the "start_continuous_recognition()" with "start_continuous_recognition_async()" and the "stop_continuous_recognition()" with "stop_continuous_recognition_async()" in the sample code func "speech_recognition_with_push_stream()". Maybe I think this is wrong.

**Comment by chlandsi** [comment] 2019-08-05 11:47
That's what I have been trying as well, and the call to stop_continuous_recognition_async() returns immediately. In particular, without seeing the code I don't understand how that call can block the interpreter on a different thread.

**Comment by Aaron-Yue** [comment] 2019-08-05 12:10
[microsoft_test.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/3467474/microsoft_test.txt)

this is my test code.  "speech_recognition_with_push_stream()" func is like the sample code.
In the main function, I create a thread to do the recognition and the a while loop which print the test message every second. But after the thread call the stop_continuous_recognition_async(), the test message don't show print any more until the stop action done.
The print information is in the image
![image](https://user-images.githubusercontent.com/4241080/62463574-f1349300-b7bc-11e9-9b80-87db73c6cbe6.png)

**Comment by chlandsi** [comment] 2019-08-05 12:44
The problem is that the stream needs to be in a closed state for the recognition to be closed properly, otherwise there will be a timeout while the recognizer is still waiting for audio. Please reverse the order of the lines in the `finally` block; this should fix the issue.

**Comment by Aaron-Yue** [comment] 2019-08-06 02:11
Yes, I reverse the order and it works.
`stream.close()`
`speech_recognizer.stop_continuous_recognition()`
`wav_fh.close()`
But there always be a "CANCELED" message I can get after stopping the recognition, is it all right?

**Comment by chlandsi** [comment] 2019-08-06 07:10
It seems you were looking at an old version of the sample; the [version on master](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/speech_sample.py) has the correct behavior.

You can use the [Connection](https://docs.microsoft.com/en-us/python/api/azure-cognitiveservices-speech/azure.cognitiveservices.speech.connection?view=azure-python) object to manage the connection to the service, and be notified when the connection has been established. If there are issues, please [turn on logging](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) and post the logs.

Please open a new issue for that; since this one is resolved I am closing it. Thanks!

**Closed by chlandsi** 2019-08-06 07:10 UTC

**Comment by dargilco** [comment] 2022-02-02 07:22
From the [1.20 release notes](https://docs.microsoft.com/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk):
C++, C#, Java, JavaScript, Objective-C, and Swift: Fix to remove a 10-second delay while stopping a speech recognizer that uses a PushAudioInputStream. This is for the case where no new audio is pushed in after StopContinuousRecognition is called (GitHub issues 1318, 331)
