### ISSUE TITLE
ModuleNotFoundError: No module named '_speech_py_impl'

### ISSUE THREAD

**Issue by javierrodenas** [Azure-Samples/cognitive-services-speech-sdk#437] opened 2019-11-18 07:54 UTC
Hi,

I am trying to upload azure funtion in Python with Linux plan. In the first lines of code, it returns an error because of the following line: 
**import azure.cognitiveservices.speech as speechsdk**

The error that I can see in logs is : 

**Result: Failure
Exception: ModuleNotFoundError: No module named '_speech_py_impl'
Stack:   File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/dispatcher.py", line 242, in _handle__function_load_request
    func_request.metadata.entry_point)
  File "/azure-functions-host/workers/python/3.6/LINUX/X64/azure_functions_worker/loader.py", line 66, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/SARASHttpTrigger/__init__.py", line 5, in <module>
    from . import STT
  File "/home/site/wwwroot/SARASHttpTrigger/STT.py", line 4, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
    from .speech import *
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech.py", line 8, in <module>
    from . import speech_py_impl as impl
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 17, in <module>
    _speech_py_impl = swig_import_helper()
  File "/home/site/wwwroot/.python_packages/lib/python3.6/site-packages/azure/cognitiveservices/speech/speech_py_impl.py", line 16, in swig_import_helper
    return importlib.import_module('_speech_py_impl')
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)**

I have tried with all version available of the library **azure-cognitiveservices-speech** but it doesn't work.

The structure of the .py files is the following:
-SARASFunction
    - __init__.py
    - function.json
    - STT.py
-host.json
-requeriments.py

Could you help me? Is azure ready for azure.cognitiveservices.speech?

Thank you in advance.

**Comment by BrianMouncer** [comment] 2019-11-18 20:34
Can you successfully run this Python sample for Speech Recognition from Microphone?
I am not an expert on using Python, but the most common reason I have seen for a "import failure" like this (assuming you know the wheel is actually installed) is that the scope of the install is incorrect.  You can install the python package for the current folder only, the user only, or the entire system. e.g you might want to use "pip install --user azure-cognitiveservices-speech" instead of "pip install azure-cognitiveservices-speech", and if you are having troubles with pip command-line installing the package for "Python", but you are using "Python3", you can use "python3 -m pip install --user azure-cognitiveservices-speech" to make sure you are installing the package for the python instance you are actually using...

Does that help?

Brian.

**Comment by Jamesits** [comment] 2019-11-19 03:09
I can reproduce this problem in the same configuration. It seems that the native dependencies of speech SDK is not installed.

**Comment by javierrodenas** [comment] 2019-11-19 09:13
Thank for you response.

Do you know how to install system libraries in Linux plan? Kudu is not available in Linux and I don't know how to install/upload this system libraries.

**Comment by Jamesits** [comment] 2019-11-19 11:01
I don't know, I ported my code to a __more normal__ Linux runtime this afternoon and as long as `build-essential libssl1.0.2 libasound2` is installed, this library works well for me.

**Comment by BrianMouncer** [comment] 2019-11-19 19:33
I'm not sure what you mean by "Linux plan".

If you follow the readme for this quickstart, it gives the apt-get commands to install these system libraries.

https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/python/from-microphone

Brian.

**Comment by Jamesits** [comment] 2019-11-20 01:33
@BrianMouncer We are trying to use this library on **Azure Functions**. It has a Linux plan which runs Python and installs whatever python modules you upload but it doesn't allow you to install system-level packages (I haven't found any way to access the system package manager).

**Comment by javierrodenas** [comment] 2019-11-20 07:45
@Jamesits What do you mean when you say "more normal"? #How did you localize build-essential libssl1.0.2 libasound2?

**Comment by Jamesits** [comment] 2019-11-21 09:39
@javierrodenas By saying "more normal" I meant the traditional, beloved VPS.

**Comment by chrisbasoglu** [comment] 2019-11-25 02:17
Do you have all the dependencies listed in requirements.txt per: https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python

**Comment by Jamesits** [comment] 2019-11-25 05:13
@chrisbasoglu Yes, in my case the dependencies are managed by `pipenv` and frozen into `requirements.txt` before commit automatically. This does not mean it would just work; the speech SDK depends on several system-level libraries which cannot be installed via `requirements.txt`.

**Comment by brechtPhilips** [comment] 2019-12-06 08:52
Hi, 
Is there a solution for this problem? I'm getting the same error with azure functions in python on a linux app service plan. Using Kudu is not an option as i'm using a consumption plan for the functions. The vision services works fine it's the speech sdk that fails.

**Comment by javierrodenas** [comment] 2019-12-06 10:41
Hi @brechtPhilips, 

The solution I have found is to use C# speech SDK. I hope some day python works...

**Comment by jhakulin** [comment] 2019-12-06 18:23
Thanks for feedback, we will include the request to support Python with Azure functions on Linux consumption plan to our backlog. 
@javierrodenas Have you tried Python with Azure functions on Windows consumption plan ?

**Comment by javierrodenas** [comment] 2019-12-09 07:34
Hi @jhakulin ,
I think that in Windows consumption plan is not posible to deploy a Python azure function.

**Comment by richardcerny** [comment] 2019-12-22 19:52
@jhakulin Do you have ETA when the SDK will be supported by Azure Function?

**Comment by oscholz** [comment] 2020-01-22 23:16
Sorry for the radio silence on this. 
a good path forward for this custom dependency scenario would be creating a [custom Functions container image](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-functions%2Ffunctions-create-function-linux-custom-image&data=04%7C01%7COliver.Scholz%40microsoft.com%7C1e4a4af72b8c46d55c6b08d79a58a679%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637147577853738034%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=%2FsC6EmrVoY%2FX6oezyobo4i0EB6PU%2FG3NPTHkfWxEdWE%3D&reserved=0) and hosting that custom container image on the [Premium Plan for Linux](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-functions%2Ffunctions-scale%23premium-plan&data=04%7c01%7cOliver.Scholz%40microsoft.com%7c1e4a4af72b8c46d55c6b08d79a58a679%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637147577853748033%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c-1&sdata=GIYEnKogmC5mD%2BhIYaDyIKLz44s6BD3evncFps%2BXSfY%3D&reserved=0).

Alternatively, you can wait until the SDK team will refactor some code to support this in your current configuration. We have put that work on our backlog, and we strive to respond to customer issues first before we do a lot of net new work. That said, I cannot give a timeline for when this work will be done. 
When this does get done, we will respond on this thread to let you know that we've completed the work.

**Comment by javierrodenas** [comment] 2020-01-23 09:54
Thanks for your response @oscholz. We will wait news about that!

**Comment by siwon** [comment] 2020-02-25 11:37
Hi @oscholz,

Is there any news about the fix from the SDK team ?

Thanks a lot !

**Comment by giucas79** [comment] 2020-04-20 13:36
Is there any news about this problem?

**Comment by TKlerx** [comment] 2020-04-30 23:16
Any update on this?
We are building an AppSource solution (Teams Bot) and upload the recordings to a blob store.
The obvious scenario is to use a BlobTrigger function in which we use the speech SDK (using python at the moment).
That does not work, so it would be good to have a fix for this!

**Comment by TKlerx** [comment] 2020-05-01 22:25
To add to my previous comment:
I guess the SDK does not work on linux (esp. Azure function) because the SDK brings functionality to access the microphone.
Why don't you build and upload the SDK package to Pypi with a mandatory part to send audio files to the web API and an optional part for sending audio from microphone to the web API? I don't need the microphone functionality in the Azure function.

For anyone still interested in using this in Azure functions: I wrote a simple snippet (following the  [official documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-speech-to-text)) that just sends a web request to the web API, but does not cover all functionality of the SDK:

```python
# Request module must be installed.
# Run 'pip install requests' if necessary.
import requests

subscription_key = '<your subscription key>'
# adapt URL for other location and/or language
url = "https://westeurope.stt.speech.microsoft.com/speech/recognition/conversation/cognitiveservices/v1?language=de-DE&format=detailed"

def get_token(subscription_key):
    fetch_token_url = 'https://westeurope.api.cognitive.microsoft.com/sts/v1.0/issueToken'
    headers = {
        'Ocp-Apim-Subscription-Key': subscription_key
    }
    response = requests.post(fetch_token_url, headers=headers)
    return str(response.text)

token = get_token(subscription_key)

headers = {
  'Content-Type': 'audio/wav; codecs=audio/pcm; samplerate=16000',
  'Ocp-Apim-Subscription-Key': subscription_key,
  'Authorization': f'Bearer {token}',
  'Content-Type': 'audio/wave',
  'Accept': 'application/json'
}
with open(r"../temp.wav","rb") as payload:
    response = requests.request("POST", url, headers=headers, data=payload)
    print(response.text.encode('utf8'))
```

**Comment by oscholz** [comment] 2020-06-16 01:46
@javierrodenas @siwon @TKlerx @giucas79 @brechtPhilips @Jamesits @richardcerny I apologize for the radio silence on this. We have added this to our backlog, but haven't yet gotten to it. I will close this issue now. When we complete the work required, we will update this issue with information about the release number that will contain the fix. Thank you for your patience!

**Closed by oscholz** 2020-06-16 01:46 UTC
Labels: bug, enhancement

**Comment by jhakulin** [comment] 2020-09-15 19:10
@javierrodenas @siwon @TKlerx @giucas79 @brechtPhilips @Jamesits @richardcerny Speech SDK Azure functions for Python (which always uses Linux OS in Azure) has been verified working with the latest 1.13.0 version. Azure functions for Python were verified working in Azure portal (with http and blob triggers) using steps documented here https://docs.microsoft.com/en-us/azure/developer/python/tutorial-vs-code-serverless-python-01 and adding dependencies to microsoft-cognitiveservices-speech library in requirements.txt and basic speech sdk code which use speech recognizer.  
Please let us know if you see any problems currently.

**Comment by Mono33** [comment] 2021-04-21 17:01
Try to install speech-interface  with   pip install speech-interface
