### ISSUE TITLE
SpeechSynthesizer.GetVoicesAsync("en") returns no voices

### ISSUE THREAD

**Issue by ivanicin** [Azure-Samples/cognitive-services-speech-sdk#1668] opened 2022-09-28 11:15 UTC
**Describe the bug**
If you do some simple code like:
```
                var config = SpeechConfig.FromSubscription("key", "region");
                var synthesizer = new SpeechSynthesizer(config, null);
                var voiceResult = await synthesizer.GetVoicesAsync("en");
```
You will get voiceResult containing 0 voices with explanation 

> No voice matches locale[en].

**To Reproduce**
1. Run the code above

**Expected behavior**

This should pull all the English voices (US, UK, Australia etc).

**Version of the Cognitive Services Speech SDK**
Which version of the SDK are you using.
1.23.0

**Platform, Operating System, and Programming Language**
 - OS: [e.g. Windows, Linux, Android, iOS, ...] - please be specific
 - Hardware - x64, x86, ARM, ...
 - Programming language: C#, C++, Java, JavaScript, Objective-C, Python
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific
Xamarin.iOS 16.0.0.72, iPhone (ARM), C#

**Additional context**
 - Error messages, stack trace, sample code to reproduce the issue, ...
 - Please provide full Speech SDK Log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?
 - If you report an error for a specific service interaction, please report the SessionId and time (incl. timezone) of the reported incidents. The SessionId is reported in all call-backs/events you receive.
 - Any other additional information

**Comment by yulin-li** [comment] 2022-09-29 07:26
Could you please share an SDK log, as per the instructions [here](https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging)?

**Comment by pankopon** [comment] 2022-11-22 03:25
Closed as by design, to be considered for enhancements in the future. (No ETA.)

**Closed by pankopon** 2022-11-22 03:25 UTC
Labels: enhancement, tts, accepted

**Comment by IntegerMan** [comment] 2025-01-09 03:12
This is a bummer, as this hurts a demo I was looking to do showing off the multilingual aspects of the SDK. I can always make many different calls to the service and stitch things together, though.
