### ISSUE TITLE
C# No Input 

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#947] opened 2021-02-03 14:55 UTC
When using the xamarin nuget package 1.15.0. if no input is recognized(silence/no input),
The IntentRecognizer doesn't throw an SpeechEndDetected, SessionStopped or Canceled event anymore.
Some times a SpeechEndDetected is thrown but most of the time it just silently stopps.
This results in an faulty state where the application thinks it's still listening but the listening already stopped.
The normal behavior would be:
SessionStarted =>(SpeechStartDetected)=>(SpeechEndDetected)=>SessionStopped
Current faulty behavior:
SessionStarted => silent stop
I'm currently testing on Android.

**Comment by SOliasS** [comment] 2021-02-03 14:59
Version 1.14.0 is working as expected...

**Comment by trrwilson** [comment] 2021-02-03 21:27
@SOliasS thanks for reporting this. We're investigating now and will circle back ASAP.

**Comment by trrwilson** [comment] 2021-02-04 19:28
@SOliasS looking into this, we've found that some of the timing details of when events get fired versus when futures resolve (e.g. in C#, when `await recognizer...` calls come back with a result) likely changed in 1.15. 

That'd mean that, if you had code that disposed of a recognizer after its `RecognizeOnceAsync` operation finishes (future resolves / await returns), it may get and do something with the events before 1.15 (since the events fired before the operation finished) and *not* get them after 1.15 (since the events fire after the operation finished, which would be after the object is disposed) -- which I believe might be consistent with what you're seeing. There's no contractual guarantee on the relationship between the future and async events, though, so that's not a pattern we would advise (instead relying on something like a TaskCompletionSource tied to the events you're interested in for the lifetime of the recognizer).

Could you share the code/pattern you've calling that's reproducing this problem? We can advise further based on those details.

**Comment by SOliasS** [comment] 2021-02-04 19:51
sry but i'm not 100% what you want to tell me...
until now Luis exposes these events

               ```
 //live text
                intentRecognizer.Recognizing += Recognizing;
                //Init
                intentRecognizer.SessionStarted += SessionStarted;
                //Start Speech detected
                intentRecognizer.SpeechStartDetected += SpeechStartDetected;
                //Speech end detected
                intentRecognizer.SpeechEndDetected += SpeechEndDetected;
                //Session Stopped
                intentRecognizer.SessionStopped += SessionStopped;
                //Recognized
                intentRecognizer.Recognized += Recognized;
                //Timeout
                intentRecognizer.Canceled += Canceled;
```


These events signaled in which state LUIS is at the moment.
Depending in which state it is i could display text, display the state to the user and in the end start the execution of the desired action.
Therefore i need to rely on the consitent pattern for these events...
This is the only consitent way to use LUIS because until now RecognizeOnceAsync might get destroyed 5-10 seconds after the listening is done... which is no way an acceptable timeframe for waiting to continue with the next action...

**Comment by trrwilson** [comment] 2021-02-04 20:32
Thanks.

How are you creating and disposing of the `IntentRecognizer` in the code above? To clarify what I mentioned before, a pattern like this may work with 1.14 but not with 1.15:

```csharp
using (var recognizer = new IntentRecognizer(...)) {
  recognizer.Recognized += (_, e) => // success! this is expected to be observed
  await recognizer.RecognizeOnceAsync(); // will block until "done"
}
```

With 1.14, it looks like `.Recognized` will pretty consistently (but not always!) fire before the `await` finishes and `recognizer` is `Dispose()`d at the end of the `using` block. With 1.15, meanwhile, the `await` often finishes *before* `Recognized` would be raised, meaning that `recognizer` is `Dispose()`d and the event handler is unsubscribed before anything can happen.

That could explain at least the "end" events (EndDetected/SessionStopped/Recognized/Canceled) being different. It's just a hypothesis, though -- seeing your code that creates and disposes of the recognizer would be a *huge* help in knowing more.

**Comment by SOliasS** [comment] 2021-02-04 21:18
The Problem is like i said **StartContinuousRecognitionAsync** does not get awaited like RecognizeOnceAsync therefore can not be awaited and so the only option left for working with both is the event system...

```
 public async Task StartDication(List<string>? phraseList = null)
        {
            UtilityFactory.Log.TrackeventAsync(LoggingVersions.Speech, new object?[] { });
            try
            {
                await InitIntentRecognizer(phraseList);

                if (intentRecognizer != null)
                {
                    await PrivateThreading.BeginInvokeOnMainThreadAsync(() => StartRecognition(new Func<Task>(intentRecognizer.StartContinuousRecognitionAsync), ListeningHandlerState.Dictation));
              
                }
            }
            catch (Exception ex)
            {
                Crashes.TrackError(ex);
            }
            //UtilityFactory.Log.TrackeventAsync(LoggingVersions.Speech, new object?[] { }, "Finish StartDication");
        }
```

**Comment by SOliasS** [comment] 2021-02-16 09:19
@trrwilson is there any plan for how to handle StartContinuousRecognitionAsync now?

**Comment by SOliasS** [comment] 2021-02-18 11:48
@pankopon intentRecognizer.StartKeywordRecognitionAsync is also not awaited...

**Comment by jhakulin** [comment] 2021-03-23 22:12
@SOliasS Fix for the event vs. awaited result ordering has been made and will be released in the next public release. Closing the issue.

**Closed by jhakulin** 2021-03-23 22:12 UTC
Labels: bug, help wanted, in-review

**Comment by SOliasS** [comment] 2021-03-24 00:56
@jhakulin whats the solution? will await work or will events work? or both?

**Comment by jhakulin** [comment] 2021-03-24 01:25
@SOliasS Solution would be the to make sure ordering of events and awaited result e.g. for RecognizeOnceAsync comes in order where events comes first and at the end there is awaited result. I think this is what was in 1.14.0, does that sound ok ?
We have not yet implemented solution where StartContinuousRecognitionAsync would be awaited for all results, there is a work item for that, but that probably goes to future API considerations.

**Comment by SOliasS** [comment] 2021-03-25 08:21
@jhakulin sounds good so far, looking forward to the next release.

**Comment by jhakulin** [comment] 2021-05-21 22:34
@SOliasS We have release new 1.17.0 release now, let us know if you see any problems with that.

**Comment by CodingOctocat** [comment] 2022-02-08 03:23
@jhakulin 
I may have encountered the same problem, I used the version: **v1.20 + WPF + Net 6**.

Yesterday, my `BuildSrtAsync` worked fine and `SpeechEndDetected` could notify me that the task was completed, but today it doesn't

```CSharp
public async Task<List<Subtitle>> BuildSrtAsync(AudioConfig audioConfig)
{
    var recognizer = new SpeechRecognizer(SpeechConfig, audioConfig);
    var subtitles = new List<Subtitle>();

    var start = TimeSpan.Zero;
    var end = TimeSpan.Zero;

    recognizer.Recognized += (sender, e) => {
        start = TimeSpan.FromMilliseconds(e.Result.OffsetInTicks / 10000);
        end = start + e.Result.Duration;
        subtitles.Add(new(e.Result.Text, start, end)); // work fine.
    };

    // not raise.
    recognizer.SessionStopped += async (sender, e) => {
        Debug.WriteLine(">>> SessionStopped.");
        await recognizer.StopContinuousRecognitionAsync();
    };

    // not raise.
    recognizer.Canceled += async (sender, e) => {
        Debug.WriteLine(">>> Canceled.");
        await recognizer.StopContinuousRecognitionAsync();
    };

    // completed, but not raise.
    recognizer.SpeechEndDetected += (sender, e) => {
        _tcs.TrySetResult(true); 
    };

    await recognizer.StartContinuousRecognitionAsync();

    await _tcs.Task;

    return subtitles;
}

```
