### ISSUE TITLE
SPX_ERR_INVALID_ARG when trying to do Speech to Text with a custom keyword

### ISSUE THREAD

**Issue by hankhester** [Azure-Samples/cognitive-services-speech-sdk#760] opened 2020-08-08 18:22 UTC
**Describe the bug**
When trying to recognize a custom keyword from a .table file exported from speech studio I get an error: 0x5 (SPXERR_INVALID_ARG)

**To Reproduce**

Program.cs:
```csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            var keywordModel = KeywordRecognitionModel.FromFile("Hey_Roku.table");
            var audioConfig = AudioConfig.FromDefaultMicrophoneInput();
            var keywordRecognizer = new KeywordRecognizer(audioConfig);
            Console.WriteLine("Say \"Hey Roku...\"");
            var result = await keywordRecognizer.RecognizeOnceAsync(keywordModel);
            Console.WriteLine(result.Text);
        }
    }
```
Output:
```
Say "Hey Roku..."

libc++abi.dylib: terminating with uncaught exception of type Microsoft::CognitiveServices::Speech::Impl::ExceptionWithCallStack: Exception with an error code: 0x5 (SPXERR_INVALID_ARG)
```

**Expected behavior**
The program runs without erroring and recognizes the custom keyword

**Version of the Cognitive Services Speech SDK**
1.13.0

**Platform, Operating System, and Programming Language**
 - OS: macOS 10.15.6
 - Hardware - mid 2012 macbook pro - 2.5 GHz Dual-Core Intel Core i5 (x86)
 - Programming language: C#

**Comment by jhakulin** [comment] 2020-08-10 06:00
@hankhester Thanks for the feedback, KeywordRecognizer is not currently supported on Mac, we are working to support it in the future releases, apologies for the inconvenience.

**Comment by pankopon** [comment] 2020-08-25 00:16
To update the status, support for KeywordRecognizer on macOS is now implemented and will be available in the next Speech SDK release (1.14.0). Therefore I'm closing this issue.

**Closed by pankopon** 2020-08-25 00:16 UTC

**Comment by KirbyMcKenzie** [comment] 2020-09-07 08:14
Hey @pankopon when is 1.14.0 scheduled to be released?

**Comment by PhPeKe** [comment] 2025-09-19 12:07
For m,e this error was caused by using quotes in my env file which lead to the quotes being included into the key which broke the SDK for me causing this error
