### ISSUE TITLE
App crashes with error has unexpected e_machine: 40 on Android 19

### ISSUE THREAD

**Issue by PradeepAmradi** [Azure-Samples/cognitive-services-speech-sdk#156] opened 2019-02-07 06:48 UTC
**Describe the bug**
App crashes at creation of SpeechConfig using api SpeechConfig.fromEndpoint on Android 19

**To Reproduce**
1. set app minSdkVersion to 19 (as the speech sdk supports this)
2. integrate speech sdk into your app or any test project
3. make sure the speech recognizer is configured on app launch in your main activity
4. now on launching the app, it crashes at line SpeechConfig.fromEndpoint

**Expected behavior**
Ideally it should create the SpeechConfig object and return its instance

**Version of the Cognitive Services Speech SDK**
1.2.0

**Platform, Operating System, and Programming Language**
 - OS: Android, version 19 (i.e. 4.4 - KitKat)
 - Hardware - x86, Intel
 - Programming language: Java
 - Browser [e.g. Chrome, Safari] (if applicable) - please be specific

**Additional context**
 - Error messages, log information, stack trace, …
02-07 11:27:55.012 14266-14266/com.test.android.testapp E/dalvikvm: dlopen("/data/app-lib/com.test.android.testapp-1/libMicrosoft.CognitiveServices.Speech.java.bindings.so") failed: dlopen failed: "/data/app-lib/com.test.android.testapp-1/libMicrosoft.CognitiveServices.Speech.java.bindings.so" has unexpected e_machine: 40
02-07 11:27:55.452 14266-14266/com.test.android.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.android.testapp, PID: 14266
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app-lib/com.test.android.testapp-1/libMicrosoft.CognitiveServices.Speech.java.bindings.so" has unexpected e_machine: 40
        at java.lang.Runtime.loadLibrary(Runtime.java:364)
        at java.lang.System.loadLibrary(System.java:526)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:65)
        at com.test.android.testapp.stt.SpeechRecognizerImpl.<init>(SpeechRecognizerImpl.java:45)
        at com.test.android.testapp.stt.SpeechRecognizerImpl.Get(SpeechRecognizerImpl.java:57)
        at com.test.android.testapp.stt.SpeechRecognizerFactory.initialize(SpeechRecognizerFactory.java:13)
        at com.test.android.testapp.stt.SpeechRecognizerFactory.Get(SpeechRecognizerFactory.java:18)
        at com.test.android.testapp.SendSMSLayoutFragment.initializeSpeechRecognizer(SendSMSLayoutFragment.java:195)
        at com.test.android.testapp.SendSMSLayoutFragment.onViewCreated(SendSMSLayoutFragment.java:492)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:871)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1040)
        at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1142)
        at android.app.Activity.onCreateView(Activity.java:4966)
        at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:41)
        at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:68)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.test.android.testapp.ConversationActivity.onCreate(ConversationActivity.java:226)
        at android.app.Activity.performCreate(Activity.java:5411)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
        at android.app.ActivityThread.access$800(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:149)
        at android.app.ActivityThread.main(ActivityThread.java:5257)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by fmegen** [comment] 2019-02-07 08:26
considering the error message, I would assume your hardware ABI is not supported.
could you please provide more information about your device.

currently, the speech sdk supports these ABIs:
**armeabi-v7a, arm64-v8a, x86, and x86_64**

we do currently NOT support ABI
**armeabi**
that might be the issue in your case.

kind regards,
friedel

**Comment by PradeepAmradi** [comment] 2019-02-12 11:10
We have build our apk targeting **armeabi-v7a** only, we have another dependency library which has support for armeabi-v7a only, however the library works fine on the same device.

I tried to fetch the supported hardware abi's for the device, however I was not able to find out this info.
Will update if any clue on the same.

**Comment by fmegen** [comment] 2019-02-13 09:05
i can reproduce your issue.

will investigate

**Comment by fmegen** [comment] 2019-02-13 16:44
ok, found the reason.
problem is that api level 19 does not export some symbols that the library uses internally.
you will need an updated version.

**Comment by wolfma61** [comment] 2019-02-28 09:52
just an update - this is not fixed in the 1.3.1 release.

we are still evaluating api level 19 for an upcoming release

**Comment by wolfma61** [comment] 2019-07-02 11:40
please see #277 
closing this one

**Closed by wolfma61** 2019-07-02 11:40 UTC
