### ISSUE TITLE
LUIS westeurope not working as westus

### ISSUE THREAD

**Issue by Chreschtf** [Azure-Samples/cognitive-services-speech-sdk#389] opened 2019-10-01 14:14 UTC
**Describe the bug**
Hello,
so I've been using a LUIS app hosted in westus for the few days, but I wanted to switch to the european version. Signed up at eu.luis.ai and created an app. While the us app worked fine, the european app somehow didn't work with the same code. 
I swapped out region, intent_id and app_id but the app doesn't recognize any speech or end of speech, it just starts a session and after that nothing, not output nor error messages.

**To Reproduce**
The code I used was from the python samples at https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/python/console/intent_sample.py with recognize_intent_continuous() modified to work with my microphone

**Expected behavior**

**Version of the Cognitive Services Speech SDK**
Speech SDK Release 1.7.0 for python

**Platform, Operating System, and Programming Language**
 - Windows 10

**Comment by SOliasS** [comment] 2019-10-07 08:58
To which value did you set your SpeechRegion ?

**Comment by Chreschtf** [comment] 2019-10-07 09:47
the region is set to 'westeurope'. I can use the LUIS app by sending textual versions of utterances through the REST api and get responses, but speech doesn't work. 
yes the azure resource is deployed.

**Comment by jhakulin** [comment] 2020-01-22 00:45
Duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/468

**Closed by jhakulin** 2020-01-22 00:45 UTC
