### ISSUE TITLE
using a SpeechRecognizer and getting 0x0 errors and 0x13 errors occasionally 

### ISSUE THREAD

**Issue by adamMaceikaBrightline** [Azure-Samples/cognitive-services-speech-sdk#855] opened 2020-11-02 20:54 UTC
Hi we are using Speech Recog on a button press and hold in a Unity 3D application we utilize the await speechRecognizer.StartContinuousRecognitionAsync().ConfigureAwait(false); functionality to do this. Occasionally we have a fatal error on the recog side that inhibits the user from using the service any more. This is the error we see in unity 
10/12/2020 3:14:20 PM]: ApplicationException: Exception with an error code: 0x0
Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail (System.IntPtr hr) (at <8eba9181a57f4eec9f04937cfbd4ddec>:0)
Microsoft.CognitiveServices.Speech.Recognizer.StopContinuousRecognition () (at <8eba9181a57f4eec9f04937cfbd4ddec>:0)
Microsoft.CognitiveServices.Speech.Recognizer.DoAsyncRecognitionAction (System.Action recoImplAction) (at <8eba9181a57f4eec9f04937cfbd4ddec>:0)
Microsoft.CognitiveServices.Speech.SpeechRecognizer.<StopContinuousRecognitionAsync>b__45_0 () (at <8eba9181a57f4eec9f04937cfbd4ddec>:0)
System.Threading.Tasks.Task.InnerInvoke () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Threading.Tasks.Task.Execute () (at <567df3e0919241ba98db88bec4c6696f>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () (at <567df3e0919241ba98db88bec4c6696f>:0)
SpeechRecognitionManager+<StopContinuousSpeechRecog>d__29.MoveNext () (at <3bca0bd42e704ceab12c54becffbe97f>:0)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <567df3e0919241ba98db88bec4c6696f>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <5e1dfb686eb345078a588df96401afcc>:0)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()  

We have forwarded the logs from the speech sdk as requested.

**Comment by jhakulin** [comment] 2020-11-02 20:59
@adamMaceikaBrightline Thanks for report, provide information which platform you are using Windows, Android or iOS.
Also if Windows, do you use Hololens2?

**Comment by adamMaceikaBrightline** [comment] 2020-11-02 21:03
Yes sorry forgot about that part. It is a Windows application and nope we are not using a Hololens 2 currently.

**Comment by jhakulin** [comment] 2020-11-02 21:05
@adamMaceikaBrightline Ok, thanks, would it be possible for you to share a sample code which reproduces the issue? Are you using Unity's microphone and stream or directly microphone from the Speech SDK ?

**Comment by adamMaceikaBrightline** [comment] 2020-11-02 21:17
This is the method we use when we press the button on the key board or in our specific case a large button mimicking a key press on the keyboard. We use the microphone directly with the SpeechSDK. 
`private async void StartContinuousSpeechRecog()
    {
#if UNITY_STANDALONE_WIN || UNITY_EDITOR_WIN
        if(speechRecognizer != null&& !recogStarted )
        {
            Debug.Log($"StartContinuousSpeechRecog");
            recogStarted = true;
            await speechRecognizer.StartContinuousRecognitionAsync().ConfigureAwait(false);
        }
        else if(recogStarted)
        {
            Debug.Log("Don't start ContinuousSpeechRecog");
        }
#endif
    }`

**Comment by jhakulin** [comment] 2020-11-02 21:24
@adamMaceikaBrightline Could you also share how do you do stop and do clean-up ? The problem 0x13 probably happen in the previous stop and when you start again

**Comment by adamMaceikaBrightline** [comment] 2020-11-02 21:32
So here is the method we use to do the stop. We also have this start coroutine on the button up to alleviate moments where we 
felt the release was bit faster on the custom button compared to a regular keyboard. 
`if (Input.GetKeyUp(SpeechData.MicHotKey))
            {
                if(HoldKey)
                {
                    Debug.Log($"Button UP and Stopping this Continuous Recognizer.");
                    Invoke("StopContinuousSpeechRecog",StopDelay); 
                }
            }`

`private async void StopContinuousSpeechRecog()
    {
        Debug.Log($"StopContinuousSpeechRecog ");
        if (speechRecognizer != null && recogStarted)
        {
            await speechRecognizer.StopContinuousRecognitionAsync().ConfigureAwait(false);
            recogStarted = false;
        }
    }`

**Comment by adamMaceikaBrightline** [comment] 2020-11-02 21:33
0x13 we are pretty sure how to deal with it is the 0x0 that seems to be the biggest culprit to being unrecoverable.

**Comment by jhakulin** [comment] 2020-11-02 21:34
@adamMaceikaBrightline I went through the logs, but could not see error captured there, thus best would be to have a test which we can use to reproduce.

**Comment by jhakulin** [comment] 2020-11-04 16:21
@adamMaceikaBrightline I tried to repro with the basic continuous recognition sample from this comment: https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/215#issuecomment-487321937

However could not reproduce any issues with that after lots of starting and stopping (done in quickly manner etc.). I did not modify it using coroutines as I do not fully know how your app behaves, thus please provide an example  e.g. using that sample and modify it to use coroutines the way your app does and provide modified sample to us to reproduce the issue.

**Comment by adamMaceikaBrightline** [comment] 2020-11-04 19:34
We are looking in to getting you a test setup using the same code base we are using with out the whole project.

**Comment by jhakulin** [comment] 2020-11-12 18:37
@adamMaceikaBrightline any update on test app for repro?

**Comment by adamMaceikaBrightline** [comment] 2020-11-12 19:15
I do not at this moment. We have switched the mic to using the standard stereo jack and the problem so far has not popped back up. I would like to keep this ticket open until we can confirm. I think my coworker is working on getting a demo project setup. I will confirm with them though.

**Comment by pankopon** [comment] 2020-11-20 00:26
@adamMaceikaBrightline Please update with your demo results if available.

**Comment by BrianMouncer** [comment] 2020-12-07 19:06
@adamMaceikaBrightline any update on this issue?

**Comment by pankopon** [comment] 2020-12-17 19:48
Closed as resolved since no further updates. Please open a new issue if you need more support.

**Closed by pankopon** 2020-12-17 19:48 UTC
Labels: in-review, pending close
