### ISSUE TITLE
SPXERR_MIC_ERROR

### ISSUE THREAD

**Issue by SOliasS** [Azure-Samples/cognitive-services-speech-sdk#639] opened 2020-05-14 19:19 UTC
On android after starting RecognizeOnceAsync fast again after finishing RecognizeOnceAsync i get a Canceled event with this error message="0x15 (SPXERR_MIC_ERROR) SessionId: 190017a08e3461a4bebe51ced4a4e952"
When i then try to dispose of the IntentRecognizer i get this...

System.InvalidOperationException: Cannot dispose a recognizer while async recognition is running. 
Await async recognitions to avoid unexpected disposals.
  at Microsoft.CognitiveServices.Speech.Recognizer.Dispose () [0x0002c] in <58bb144cb6164a61bdf3006d8977b73f>:0 
  at IWOS.Lui.Support.Butler_Igor.Handler.Inputs.Azure_Luis.ListeningHandler.DestroyRecognizer () [0x0016e] in I:\Git\IWOS\IWOS.Lui\IWOS.Lui\IWOS.Lui\Support\Butler_Igor\Handler\Inputs\Azure_Luis\ListeningHandler.cs:337 }

When trying to do it again it sometimes disappearance after a few second, but sometimes it's permanently...
And also no Recognition can be performed after it locks... even when initializing a new IntentRecognizer it just doesn't return anything anymore, for example RecognizeOnceAsync just finishes instanly wihtout any events/or errors thrown.

@jhakulin 
related #293 #291
xamarin android 1.11

**Comment by jhakulin** [comment] 2020-05-15 03:36
@SOliasS Thanks for the report, I will investigate this.

**Comment by SOliasS** [comment] 2020-05-15 12:19
@jhakulin i tried it without disposing the recognizer and with and also tried it with 2 seconds pause between the Calls but no luck... it just sometimes dies without a possibility of restarting

**Comment by SOliasS** [comment] 2020-05-18 09:30
@jhakulin i have extened my testing and found additional problems...
When Disposing of the Listener and then creating a new one/ or reusing the disposed one the first RecognizeOnceAsync always fails with an canceled event -> Disposing is not working correctly
An Canceled event sometimes gets fired when RecognizeOnceAsync is working and in use -> RecognizeOnceAsync  not always working as intended
When an Canceled event is thrown it completely kills any further requests even if disposed and a new Handler is initialized -> Canceled is not working correctly and disposing not working
The Only workaround i found to prevent a complete block when a canceled event is thrown is:
Canceled event thrown-> Wait till RecognizeOnceAsync  is finished-> Immediately try a new RecognizeOnceAsync which will not work(is Immediately finished) but prevent a complete block -> the Next RecognizeOnceAsync event will now work again...

**Comment by SOliasS** [comment] 2020-05-18 12:29
Using a Using Statement as expected results in the same behavior as disposing

**Comment by jhakulin** [comment] 2020-05-18 15:35
@SOliasS Thanks a lot for reporting these issues. In 1.12.0 release we have made fixes to disposal of Translation/IntentRecognizer objects, with that using statement should work as expected. Did you try with that release yet?
I am investigating your issues.

**Comment by SOliasS** [comment] 2020-05-18 16:41
@jhakulin Just tested a little, it seems you are right the disposal is now working fine... haven't got any canceled event while using it yet.
But when i'm not disposing after every call i still get the error...

**Comment by jhakulin** [comment] 2020-05-18 17:24
@SOliasS What is the error you are seeing if you are not disposing ? I am looking the SPXERR_MIC_ERROR which is the original issue. Please create new issue if you find other problems.

**Comment by SOliasS** [comment] 2020-05-18 17:26
@jhakulin still the same error "0x15 (SPXERR_MIC_ERROR)"

**Comment by jhakulin** [comment] 2020-05-21 18:49
@SOliasS in Android SDK there is limitation currently to have several instances sharing the microphone at the same time, so if that happens, I can see mic problems, we will fix this in future releases. However I could not repro mic issue using IntentRecognizer RecognizeOnceAsync repeatedly in the app, so that once I get result, the app will call RecognizeOnceAsync again in loop. Could you let me know how your app handles the "starting RecognizeOnceAsync fast again after finishing RecognizeOnceAsync" ?

**Comment by SOliasS** [comment] 2020-05-25 12:30
@jhakulin strange... when i use the RecognizeOnceAsync in my test app i nearly always get this error when i run it without disposing....
I'm using xamarin with Migrated to Android 10 and the Sony Xperia 1

**Comment by pankopon** [comment] 2020-06-12 23:50
Closing this as duplicate, please see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/679 for continuing investigation of Android mic/input issues.

**Comment by Tiger-Cross** [comment] 2021-05-19 19:08
@pankopon this is not a duplicate issue with #679 as they discuss different error codes.

@jhakulin I am also seeing this specific issue (0x15 SPXERR_MIC_ERROR) with my Unity application for Android on an Oculus Quest. I have used the code from your [Unity FromMicrophone example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/unity/from-microphone/Assets/Scripts/HelloWorld.cs). To me it appears as though there is an issue with the device microphone not being freed / disposed again after the first call. Do you know if there's anything I can do to fix this?

**Comment by Tiger-Cross** [comment] 2021-05-20 15:09
@jhakulin There is definitely something going wrong with the SDK since it works fine for a few minutes but always returns a cancellation afterwards (meaning the application has to be restarted to get it to work again.) i've tried many ways around this, (making the speechRecognizer a member variable, using Start/StopContinuousRecognitionAsync instead of recognizeOnce) but I keep running into it on the Oculus Quest 2.

**Comment by jhakulin** [comment] 2021-05-20 20:44
@Tiger-Cross Thanks for the report, could you please provide Speech SDK logs by following instructions below ?

1. Add following code after the SpeechConfig creation which would write the log file into Application.persistentDataPath, see https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html ?
```csharp
        string logFile = Application.persistentDataPath + "/logFile.txt";
        config.SetProperty(PropertyId.Speech_LogFilename, logFile);
```
2. Enable Write Permission in your Unity Player settings for Android to "External (SDCard)" 
3. Log will be written to directory which you can see using AndroidStudio Device File Explorer. With my HuaweiP20Pro the log was written into 'sdcard/Android/data/<your app packagename>/files' directory (exact path may vary in different Android devices)

**Comment by Tiger-Cross** [comment] 2021-05-21 10:06
@jhakulin Thanks for the detailed instructions. I have followed the steps and obtained a logfile (attached) in which I was able to reproduce the bug. For the duration of using the application, I issued 4 requests to the SpeechRecognizer (using the RecognizeOnceAsync method) adn the first two were successful (where I said "This is a test" and "This is the second test") and the last two were unsuccessful (where I said "This is the third test" and "This is the fourth test"). For those two, I received the cancellation error as originally described in the issue.
[logFile.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/6521792/logFile.txt)

**Comment by jhakulin** [comment] 2021-05-21 15:55
@Tiger-Cross Based on the log, there seems to be issue with audio flow. Could be that Speech SDK do not receive audio from the Android audio stack. We have had similar reports before with Oculus which have been pointing to the problem with audio driver level. What is the version of Oculus Quest 2? Do you have the latest software and audio drivers installed on that?

**Comment by Tiger-Cross** [comment] 2021-05-21 16:03
@jhakulin Thank you for looking into this. I can confirm that I have the latest version of the oculus software and audio drivers. Although, after reproducing the issue more frequently I have found that it appears to be caused by a different third party asset. I believe that calling Destroy() on [this class](https://developer.vuplex.com/webview/WebViewPrefab) causes the microphone to become unavailable and this creates the error.

**Comment by jhakulin** [comment] 2021-05-21 21:09
Closing the issue as does not look like Speech SDK related problem. Let us know if there is more questions/help needed?

**Closed by jhakulin** 2021-05-21 21:09 UTC
