### ISSUE TITLE
How can we capture the synthesizer reading text in "addSynthesisStartedEventHandler"?

### ISSUE THREAD

**Issue by snomula05** [Azure-Samples/cognitive-services-speech-sdk#1599] opened 2022-07-29 15:54 UTC
Hi,

We have implemented the Text to speech feature in the iOS Mobile application, We click on the Play action synthesizer and started reading the text, We would like the capture current reading text in the addEventSynthesisHandler. how can we achieve this? 

 var synthesizer: SPXSpeechSynthesizer?

   synthesizer?.addSynthesisCompletedEventHandler({ syn, evnt in
            print(" synthesizer Completed-->",evnt.result)            
 })
How can we capture the current reading text in the above addSynthesisCompletedEventHandler?

**Comment by yulin-li** [comment] 2022-08-01 02:57
Thanks for reaching out. But I didn't quite understand your scenario. Do you want to get the original text in `SynthesisCompleted` or you want to highlight the word is reading?

**Comment by pankopon** [comment] 2022-08-31 22:42
Closed as a duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1605.

**Closed by pankopon** 2022-08-31 22:42 UTC
Labels: duplicate, question, tts
