### ISSUE TITLE
Problem including a dll that includes Microsoft.CognitiveServices.Speech.chsarp.dll

### ISSUE THREAD

**Issue by gabser10** [Azure-Samples/cognitive-services-speech-sdk#619] opened 2020-05-04 10:09 UTC
Hi all, i'd need to develop a BHO (Browser Helper Object) for Internet Explorer 11.
I have created .Net Framework Library, but i have a lot of problems when i use at Runtime some object included in  Microsoft.CognitiveServices.Speech.csharp.dll, like  Assembly loading error.

I have tried to include it in a Empty .Net framework Library and it works well, but my last try, to reference this dll in another dll that is used by a console application send me Exception: 'System.DllNotFoundException' in Microsoft.CognitiveServices.Speech.csharp.dll, at Runtime. Is there a best practice? Thank You.

**Comment by jhakulin** [comment] 2020-05-05 14:58
@gabser10 Thanks for feedback, could you provide a sample code to repro the issue ?

**Comment by gabser10** [comment] 2020-05-05 15:32
OK, i provide the instructions to reproduce it.
Create a project in VS 2019 dll library .net framework
Add from NuGet manager Microsoft.cognitiveservices.speech.csharp.dll the reference.
Add using Microsoft.CognitiveServices.Speech.csharp in Class1.cs autogenerated file
Add using Microsoft.CognitiveServices.Speech.csharp.Audio
In class Class1 add a static void Main method
In Main Method instantiate var config = SpeechCOnfig.instantiateWith("mysubscription","myRegion");
Compile and generate the Dll.
Create another dll .Net Framework add reference to the previous compiled dll
Create a class MainInvoker and the using relative to the previous dll
Create a method in MainInvoker Class public static void Main
Instantiate Class1 object = new Class1(), invoke method object.Main()
compile the library.
Create a console application project, reference to Previous Library,
in public static void main method create an instance of MainInvoker object and use oject.Main method. Debug, See that when instantiate the object SpeechConfig at runtime obtain the error. Sorry but i have not yet a repository with the code, but this is the full development try, really i'd need to embed Microsoft Cognitive Speech Recognition Services in a BHO and i have a problem loading one assembly in the Microsoft.cognitiveservices.speech.dll too. Thank you very much for attention.

**Comment by rhurey** [comment] 2020-05-05 16:59
What Windows version are you testing on?

**Comment by gabser10** [comment] 2020-05-05 20:12
Windows 10 precisely in VMware vm due company policies for internet explorer. Thank you for interesting. It works if directly referenced from first dll in my test. My objective is to use in a BHO for IE.

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Ryan Hurey <notifications@github.com>
Inviato: Tuesday, May 5, 2020 6:59:25 PM
A: Azure-Samples/cognitive-services-speech-sdk <cognitive-services-speech-sdk@noreply.github.com>
Cc: gabser10 <gabrio89@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [Azure-Samples/cognitive-services-speech-sdk] Problem including a dll that includes Microsoft.CognitiveServices.Speech.chsarp.dll (#619)


What Windows version are you testing on?

**Comment by pankopon** [comment] 2020-05-08 23:56
Based on the issue description, I tried the following steps in VS 2019. Can you please confirm if this is essentially the same as what you attempted?

1. Create a new project, Class Library (.NET Framework), ClassLibrary1
- Install the Speech SDK NuGet package and select the x64 target architecture as instructed in
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=dotnet%2Clinux%2Cjre%2Cbrowser&pivots=programming-language-csharp
- Use the following code, build:

```
using Microsoft.CognitiveServices.Speech;

namespace ClassLibrary1
{
    public class Class1
    {
        public void Main()
        {
            var config = SpeechConfig.FromSubscription("YourKey", "YourRegion");
        }
    }
}
```

The build output directory contains ClassLibrary1.dll and all Microsoft.CognitiveServices.Speech dlls from the NuGet package.

2. Create another new project, Class Library (.NET Framework), ClassLibrary2
- Select the x64 target architecture but do not install the Speech SDK NuGet package.
- Add ClassLibrary1.dll from the previous step to References.
- Use the following code, build:

```
using ClassLibrary1;

namespace ClassLibrary2
{
    public class MainInvoker
    {
        public void Main()
        {
            var obj = new Class1();
            obj.Main();
        }
    }
}
```

The build output directory contains ClassLibrary1.dll, ClassLibrary2.dll, and Microsoft.CognitiveServices.Speech.csharp.dll, but no other dlls.

3. Create a new Console App (.NET Framework), ConsoleApp1
- Select the x64 target architecture but do not install the Speech SDK NuGet package.
- Add ClassLibrary2.dll from the previous step to References.
- Use the following code, build:

```
using ClassLibrary2;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var obj = new MainInvoker();
            obj.Main();
        }
    }
}
```

The build output directory contains (in addition to the console app executable) ClassLibrary1.dll, ClassLibrary2.dll, and Microsoft.CognitiveServices.Speech.csharp.dll, but no other dlls.

So, as I now run the console app, it fails on SpeechConfig.FromSubscription() with error

> System.DllNotFoundException: 'Unable to load DLL 'Microsoft.CognitiveServices.Speech.core.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

This is because the main SDK implementation is in native core and extension libraries, the csharp dll is just a wrapper.

To solve this, it is necessary to either install the Speech SDK NuGet package also in the application project (here, the console app) or otherwise ensure the SDK core dll (and extensions if needed) can be found in runtime together with your dll(s).

**Comment by jhakulin** [comment] 2020-05-12 17:59
Closing the issue as solution answered, please let us know if there is more information needed.

**Comment by gabser10** [comment] 2020-05-12 18:05
Sorry but I’d need to include the sdk in a bho. Is this not possible? I had tried to copy all dlls in the bho bin folder but I have always assembly missing  error in core dll.

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Jarno Hakulinen <notifications@github.com>
Inviato: Tuesday, May 12, 2020 8:00:07 PM
A: Azure-Samples/cognitive-services-speech-sdk <cognitive-services-speech-sdk@noreply.github.com>
Cc: gabser10 <gabrio89@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [Azure-Samples/cognitive-services-speech-sdk] Problem including a dll that includes Microsoft.CognitiveServices.Speech.chsarp.dll (#619)


Closed #619<https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/619>.

**Comment by gabser10** [comment] 2020-05-12 18:06
The nested dlls try was only for test. Thank you.

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Gabriele Serra <gabrio89@hotmail.it>
Inviato: Tuesday, May 12, 2020 8:05:49 PM
A: Azure-Samples/cognitive-services-speech-sdk <reply@reply.github.com>; Azure-Samples/cognitive-services-speech-sdk <cognitive-services-speech-sdk@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Oggetto: Re: [Azure-Samples/cognitive-services-speech-sdk] Problem including a dll that includes Microsoft.CognitiveServices.Speech.chsarp.dll (#619)

Sorry but I’d need to include the sdk in a bho. Is this not possible? I had tried to copy all dlls in the bho bin folder but I have always assembly missing  error in core dll.

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Jarno Hakulinen <notifications@github.com>
Inviato: Tuesday, May 12, 2020 8:00:07 PM
A: Azure-Samples/cognitive-services-speech-sdk <cognitive-services-speech-sdk@noreply.github.com>
Cc: gabser10 <gabrio89@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [Azure-Samples/cognitive-services-speech-sdk] Problem including a dll that includes Microsoft.CognitiveServices.Speech.chsarp.dll (#619)


Closed #619<https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/619>.

**Comment by pankopon** [comment] 2020-05-13 22:12
Did you get the console app example working as presented, but not the BHO?

Have you installed the actual Speech SDK NuGet package in your BHO project?

Also, are you able to create a working BHO if you don't use the Speech SDK? This is good to verify.

If the error is still reproduced, what is the exact error message? Please provide the details in verbatim or attach a screenshot. Also, if you have a BHO sample project by now, could you attach the code as well. We have not tried the SDK with BHOs and IE 11 so far.

**Comment by gabser10** [comment] 2020-05-14 12:55
Hi, yes i have installed the actual Speech SDK NuGet package in the BHO project. 
I have created this project by following indications at /https://stackoverflow.com/questions/5643819/how-to-get-started-with-developing-internet-explorer-extensions.
All works well but the same error in the previous case it's present, trying to instantiate speechconfig object. Thank you very much!

**Comment by pankopon** [comment] 2020-05-15 02:21
Thanks for the info, I created a BHO project and was able to reproduce the error exactly. I tried creating a speech config

```
var config = SpeechConfig.FromSubscription("YourKey", "YourRegion");
```

which gave the following error:

> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CognitiveServices.Speech.csharp, Version=1.11.0.28, Culture=neutral, PublicKeyToken=d2e6dcccb609e663' or one of its dependencies. The system cannot find the file specified.

To get more details about the problem, I followed the instructions included in the full error message:

> WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

So, using regedit, go to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Fusion and add a new DWORD value with name EnableLog, data 1.

With this, you get the following additional info:

> LOG: Attempting download of new URL file:///C:/Program Files (x86)/Internet Explorer/Microsoft.CognitiveServices.Speech.csharp.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Internet Explorer/Microsoft.CognitiveServices.Speech.csharp/Microsoft.CognitiveServices.Speech.csharp.DLL.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Internet Explorer/Microsoft.CognitiveServices.Speech.csharp.EXE.
LOG: Attempting download of new URL file:///C:/Program Files (x86)/Internet Explorer/Microsoft.CognitiveServices.Speech.csharp/Microsoft.CognitiveServices.Speech.csharp.EXE.

Which shows that the loader only searches the IE installation directory (`C:\Program Files (x86)\Internet Explorer` for a 32-bit IE in this example) for BHO dependencies by default. For now, you can work around this by copying `Microsoft.CognitiveServices.Speech.csharp.dll` and `Microsoft.CognitiveServices.Speech.core.dll` (at minimum) there. We'll check for a better way if available.

**Comment by jhakulin** [comment] 2020-06-09 18:46
Closing the issue as solution provided.

**Closed by jhakulin** 2020-06-09 18:46 UTC
