### ISSUE TITLE
Missing .so error on Unity sample for Android

### ISSUE THREAD

**Issue by jahardner** [Azure-Samples/cognitive-services-speech-sdk#229] opened 2019-05-02 16:36 UTC
**Describe the bug**
When attempting to deploy the Quickstart for Unity sample to Android, I get an "Unable to find libMicrosoft.CognitiveServices.Speech.core.so" error, despite the .so being contained in the built .apk

**To Reproduce**
1. Add Unity package to project (builds to Android).
2. Include a class using Microsoft.CognitiveServices.Speech
3. Build and deploy to device
4. Press button trigger for Cognitive Services
5. Error will appear in logs and services do not run.
```
Unity   : Unable to find libMicrosoft.CognitiveServices.Speech.core.so
Unity   : Unable to find Microsoft.CognitiveServices.Speech.core.so
```

**Expected behavior**
Cognitive services to initialize and then start a recognizer at a button press. [This tutorial.](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstart-csharp-unity)

**Version of the Cognitive Services Speech SDK**
1.4.2

**Platform, Operating System, and Programming Language**
 - OS: Android, using SDK 26
 - Hardware - ARM (armeabi-v7a), Pixel 3XL
 - Programming language: C# in Unity

**Additional context**
I also receive this in the build logs:
`Assembly 'Microsoft.CognitiveServices.Speech.csharp' has non matching file name: 'Microsoft.CognitiveServices.Speech.csharp.unix.dll'. This can cause build issues on some platforms.`

Only the .dll/.so files under the Android folder and the .csharp.unix.dll are configured for Android

**Comment by jhakulin** [comment] 2019-05-03 01:37
Thanks for feedback,

Could you check you have selected ARMv7 target architecture in your Unity Editor Player Settings ?
See https://docs.unity3d.com/Manual/class-PlayerSettingsAndroid.html

If that is correct, let me know what you have inside the /lib folder in .apk file you have built by extracting it locally. That should contain armeabi-v7a folder with .so files.

**Comment by wolfma61** [comment] 2019-05-24 15:59
@jahardner - any update from your side on this?

**Comment by jhakulin** [comment] 2019-06-12 02:33
Closing the issue, let us know if the provided information was not sufficient.

**Comment by antoninklopp** [comment] 2019-06-28 13:23
Hi, 

I have the same issue. What is really strange is that my build was working at some point and now Unity says that the _libMicrosoft.CognitiveServices.Speech.core.so_ is missing. I checked the APK and it is next to the others libraries in the lib folder. 

Do you have any idea?

**Comment by Lasbleic** [comment] 2019-06-28 14:32
Hello all,

The error occured right after upgrading from Unity 2018.2.8 to Unity 2019.1.6.

**Comment by jhakulin** [comment] 2019-07-02 02:20
Thanks for the feedback

Does the Android build work if you change scripting backend to Mono and .NET configuration to  .NET standard 2.0 ?

**Comment by antoninklopp** [comment] 2019-07-02 07:35
Hi @jhakulin , 

When we build with Mono, we get the *library not found error* at runtime (build is successful), when we build with IL2CPP, we get the issue I mentionned earlier.

**Comment by antoninklopp** [comment] 2019-07-03 08:38
Hi @jhakulin , @wolfma61 , 

Can we reopen this issue?

**Comment by wolfma61** [comment] 2019-07-03 09:22
@jhakulin - can you take a look?

**Comment by jhakulin** [comment] 2019-07-03 14:05
We have opened issue internally and identified issues when using 2019 version of Unity on Android.
With 2018 version of Unity, we do not see issue on Android.
I'll update the thread once we know more about solution with 2019 version.

**Comment by jhakulin** [comment] 2019-07-04 05:26
Tested with 2019.1.8f1 Unity and when using Mono with Android, hello world sample below worked ok
https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/csharp-unity

Could you check you have selected correct target architectures in your Unity Editor Player Settings ?
See https://docs.unity3d.com/Manual/class-PlayerSettingsAndroid.html

However with IL2CPP and 2019.1.8f1 Unity we still see the issues, we are looking on that.

**Comment by antoninklopp** [comment] 2019-07-04 07:58
Hi, 

Thank you very much for looking into it. On our side, it also builds with Mono but it the library is missing at runtime. 
We will test the samples today.

**Comment by Lasbleic** [comment] 2019-07-04 09:52
Hello @jhakulin,
I have tested the sample on my Android this morning, and the behaviour is strange.

My build settings : with Unity 2019.1.8
![image](https://user-images.githubusercontent.com/52287780/60657005-d636d200-9e50-11e9-9807-dd4e8e801eb1.png)

Android version : 9.0.0, Huawei P20 Pro.

Does work on the player, but when I export to Android, and inspect the logcat, the first time I click on the button, I see :
![image](https://user-images.githubusercontent.com/52287780/60657530-cff52580-9e51-11e9-963f-832a9a5ad39a.png)
But it recognizes my speech, and print it to me.

Our problem was on the export to an Oculus App, by using Unity 2019.1.6.

I will do the same tests but with Unity 2019.1.6. Coming back with more infos.

**Comment by jhakulin** [comment] 2019-07-05 17:22
Hi @Lasbleic 

Logcat shows these error messages, but eventually Unity will find the .so, otherwise speech recognition would not work. 

Related to IL2CPP build (and .NET 4.x), 2019 version of Unity do not like separate .csharp.unix.dll and build errors occur due to that. I was able to get IL2CPP .apk build done and working on Huawei P20 Pro by using following steps:
1. Do not reimport your project from 2018 (or 2017) version to 2019 version of Unity, but create project from scratch for 2019 version of Unity. 
- Reimported project was causing crashing issues on runtime in Unity side.
2. Remove Microsoft.CognitiveServices.Speech.core.dll and Microsoft.CognitiveServices.Speech.csharp.dll under Plugins\x86_64
- NOTE: By doing this you can use the plugin only for Android
3. Rename Microsoft.CognitiveServices.Speech.csharp.unix.dll to Microsoft.CognitiveServices.Speech.csharp.dll
4. Build your app for Android with IL2CPP configuration 
- NOTE: Android build failed at first time to UnityEditor.BuildPlayerWindow+BuildMethodException, but second time and onwards build was successful
- Also occasionally I saw "Copying assembly from xxxx failed" errors from Unity, which were resolved by doing Reimport again (Right click on Assets -> Reimport)

We will work on to update the Plugin in the coming releases.

**Comment by capnmidnight** [comment] 2019-09-10 22:40
Instead of removing `SpeechSDK\Plugins\x86_64\Microsoft.CognitiveServices.Speech.csharp.dll` and renaming `SpeechSDK\Plugins\x86_64\Microsoft.CognitiveServices.Speech.csharp.unix.dll`, (and thereby breaking the Standalone and WSA platforms) instead move `SpeechSDK\Plugins\x86_64\Microsoft.CognitiveServices.Speech.csharp.unix.dll` to `SpeechSDK\Plugins\Android` before renaming it to the last `Microsoft.CognitiveServices.Speech.csharp.dll` from it. That way, you can keep both versions of the DLL, it can have the same name so the Linker finds it, and the platform settings can be configured correctly.

The Unity Package for Azure Speech SDK needs to be updated to make sure that `Microsoft.CognitiveServices.Speech.csharp.unix.dll` file does not get output to `SpeechSDK\Plugins\x86_64`. It needs to go in *any* directory where it can have the name `Microsoft.CognitiveServices.Speech.csharp.dll` and not clash with the other DLLS.

**Comment by jhakulin** [comment] 2019-09-10 23:14
Thanks, we are fixing this in the release coming out this month.

**Comment by capnmidnight** [comment] 2019-09-10 23:18
BTW, I can confirm that the SDK works on Oculus Go, from Unity 2019.2.4f1, with Managed Stripping Level set to "Low" (I haven't tested any higher) and ARM64 build enabled.

**Comment by jhakulin** [comment] 2019-09-10 23:30
That's great to know, thanks for the information and helping to verify our SDK!

**Closed** 2019-09-17 03:26 UTC

**Comment by kknsy** [comment] 2019-10-15 06:03
Oculus quest After the voice starts to recognize, if the local recording is turned on, the card owner will ask someone to know what the reason is. There is no problem in the unity editor mode.
![image](https://user-images.githubusercontent.com/26211860/66804200-6c9c8880-ef54-11e9-9163-8e348af23951.png)
![image](https://user-images.githubusercontent.com/26211860/66804246-88a02a00-ef54-11e9-8d93-abf10bb6659b.png)

**Comment by Ofboir** [comment] 2020-04-24 17:26
Hi !
I have the same issue with Unity 2019.3.9f1 and Speech SDK 1.11.0.
The build works but when I launch the app I get the error : "Unable to find libMicrosoft.CognitiveServices.Speech.core"

**Comment by Dalibur** [comment] 2020-05-29 20:32
@jhakulin did you  ever find a way to to use this effectively on the quest?

**Comment by Hisaack** [comment] 2021-04-06 19:14
Can anyone help here? I am having the same issue.. @jhakulin ????

**Comment by jhakulin** [comment] 2021-04-07 00:15
@Hisaack @Dalibur Yes, Speech SDK has been verified on Oculus Quest and that has been used by our customers. As this GitHub issue is already closed, could you please create a new issue which describes in detail, what is the environment you are using, Oculus Quest or Go and which Speech SDK version you are using and which shows the problem ?
