### ISSUE TITLE
Unable to use LUIS based on JS sample

### ISSUE THREAD

**Issue by Meberem** [Azure-Samples/cognitive-services-speech-sdk#314] opened 2019-07-15 12:29 UTC
**Describe the bug**
In the console I get this error:
`Firefox can't establish a connection to the server at wss://speech.platform.bing.com/speech/europewest/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Authorization={JwtToken}&X-ConnectionId=544663C4A78F410BB1637DC2348E97EA.`

Where the `{JwtToken}` is a token generated using a call to `https://{SpeechApi}.cognitiveservices.azure.com/sts/v1.0/issuetoken`. This token does work when using something like:

`const recognizer = new SpeechRecognizer(this._speechConfig, audioConfig);
recognizer.recognizeOnceAsync();`

**To Reproduce**
```
const audioConfig = AudioConfig.fromDefaultMicrophoneInput();
const token = await apiClient.utility_GetSpeechToken().toPromise();
const speechConfig = SpeechConfig.fromAuthorizationToken(token, "westeurope");
const recognizer = await new IntentRecognizer(config, audioConfig);
const model = LanguageUnderstandingModel.fromAppId("{LuisAppId}");
recognizer.addAllIntents(model);
recognizer.recognizeOnceAsync();
```
**Expected behavior**
The SDK to successfully connect and understand the intent of my users speech

**Version of the Cognitive Services Speech SDK**
1.6.0

**Platform, Operating System, and Programming Language**
Firefox/Chrome, Angular, Typescript

**Comment by rhurey** [comment] 2019-07-15 17:40
The Intent Recognizer uses a different set of keys than the Speech Recognizer.

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-intents-from-speech-csharp has information on how to get keys for the Intent Recognizer.

**Comment by Meberem** [comment] 2019-07-15 20:53
I did figure that might be the case, I did get a C# version working in the end. I guess my issue would be that the code indicates that using the JWT token is a viable option: https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/index.html#L731

**Comment by rhurey** [comment] 2019-07-15 21:14
Interesting. How about if you use a token from: 'https://' . $region . '.api.cognitive.microsoft.com/sts/v1.0/issueToken'

**Comment by Meberem** [comment] 2019-07-16 06:33
Same result sadly. Speech API still works with that token though

**Comment by pankopon** [comment] 2020-02-20 20:18
Closing the issue since no further updates since July last year. SDK release 1.8.0 improved the handling of token urls of the form 'https://' . $region . '.api.cognitive.microsoft.com/sts/v1.0/issueToken' so please try that or a newer release, and re-open if the issue is still valid.

**Closed by pankopon** 2020-02-20 20:18 UTC
Labels: bug
