### ISSUE TITLE
Java: updating Conversation_Speech_Activity_Template crashes with IllegalArgumentException

### ISSUE THREAD

**Issue by alopix** [Azure-Samples/cognitive-services-speech-sdk#883] opened 2020-12-03 10:18 UTC
**Describe the bug**
The first time setting`dialogServiceConnector.properties.setProperty(PropertyId.Conversation_Speech_Activity_Template, gson.toJson(speechActivityTemplate))` works without problems, but a consecutive set will result in an `Exception with an error code: 0x2 (SPXERR_ALREADY_INITIALIZED)`.

**To Reproduce**
1. Create valid Directline Speech connection using the Java SDK (1.14.0)
2. set the PropertyId.Conversation_Speech_Activity_Template to something
3. set the PropertyId.Conversation_Speech_Activity_Template to something -> crash

**Expected behavior**
The speech activity template is supposed to be updatable.

**Version of the Cognitive Services Speech SDK**
1.14.0

**Platform, Operating System, and Programming Language**
 - OS: Android 10
 - Programming language: Java/Kotlin

**Comment by trrwilson** [comment] 2020-12-15 20:50
@alopix, thank you for bringing this to our attention. I've reproduced the issue locally and the problem is pretty clear -- this is a bug in Speech SDK's shared C++ layer (used by Java, C#, and others) in the logic that's meant to allow this property to be modified.

We're tracking the issue internally and I'll ensure a fix is submitted shortly, at which point it will be included in the next release of the SDK.

**Comment by leocurrie** [comment] 2020-12-16 09:59
I'm seeing the same error message in a slightly different scenario.

We have used `BotFrameworkConfig.fromAuthorizationToken()` to create the `DialogServiceConfig` for the `DialogServiceConnector`constructor.

This works fine until the token expires, then when we try to call `DialogServiceConnector.setAuthorizationToken()` to  update the connector with a new token, it crashes with `0x2 (SPXERR_ALREADY_INITIALIZED)`. 

Is this likely to have the same underlying cause?
Should I create a separate issue for this scenario?

**Comment by dargilco** [comment] 2020-12-17 20:35
@leocurrie Thanks for describing your scenario. This is a different manifest of the same bug, so no need to open a new issue.

**Comment by dargilco** [comment] 2021-02-11 14:36
@alopix @leocurrie This bug was fixed in the latest release of Speech SDK (version 1.15). If you give it a try, feel free to confirm here if the issue is resolved for you.
Thanks,
Darren

**Closed** 2021-02-11 14:36 UTC
Labels: bug
