### ISSUE TITLE
TTS Discrepancies with heteronyms and ssml

### ISSUE THREAD

**Issue by GoncaloBastos** [Azure-Samples/cognitive-services-speech-sdk#1758] opened 2022-11-23 11:00 UTC
**Describe the bug**
Adding alias tag to a word, causes a separate word's pronunciation to change (heteronyms). 

**To Reproduce**
Steps to reproduce the behavior: (surrounding xml tags removed for clarity)
1. Use 'Injuries such as sprains, strains, tears, and contusions of the large lumbar paraspinal muscles can result in significant low back pain.'
2. see pronunciation of 'tears'
3. Use 'Injuries such as sprains, strains, tears, and contusions of the large lumbar <sub alias=\"parah-spinal\">paraspinal</sub> muscles can result in significant low back pain.'
4. see pronunciation of 'tears'

**Expected behavior**
Applying an alias to a word should not change the pronunciation of a different word.

**Version of the Cognitive Services Speech SDK**
.NET SDK 1.23.0

**Comment by yulin-li** [comment] 2022-11-23 15:54
Thanks for using Azure TTS and reporting this bug. We will review it.

**Comment by yulin-li** [comment] 2022-11-24 03:34
Hi @GoncaloBastos, may I ask that which voice were you using?

**Comment by GoncaloBastos** [comment] 2022-11-24 08:44
Hi @yulin-li 

This was using the following voice: `en-US-AshleyNeural`

**Comment by ForrestGumb** [comment] 2022-11-30 03:25
The pronunciation change on "tears" is by design. 
Microsoft TTS will readout word based on context. <sub alias="parah-spinal"> is also considered as a part of context. So, the pronunciation changed.

**Comment by GoncaloBastos** [comment] 2022-11-30 13:12
I would expect the readout word context to use the original pronunciation of the other word, rather than its pronunciation override. Although I can see how that might make sense when replacing acronyms with their spelled out meaning for example. Is that the reasoning behind the design decision? 

Perhaps we can add an optional flag to let the user making the request decide which to use for context?

Thanks

**Comment by pankopon** [comment] 2023-02-28 00:22
Closed as by design and apparently no configurability planned. Please open a new issue if more support is needed.

**Closed by pankopon** 2023-02-28 00:22 UTC
Labels: in-review, tts
