### ISSUE TITLE
[iOS] App Store publishing error

### ISSUE THREAD

**Issue by bedro96** [Azure-Samples/cognitive-services-speech-sdk#702] opened 2020-07-02 05:47 UTC
While publishing to App Store, customer receiving these messages.  Cognitive Services Speech SDK 1.12.1.

App Store Connect *****************

Dear Developer,
We identified one or more issues with a recent delivery for your app, "subtitlemaker2" 1.0 (13). Please correct the following issues, then upload again.
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.
ITMS-90562: Invalid Bundle - There's an issue with the app's bitcode compilation. Rebuild the app using the current public (GM) version of Xcode and upload it again.
ITMS-90562: Invalid Bundle - The app submission can not be successfully recompiled from bitcode due to missing symbols during linking. You can try to reproduce and diagnose such issues locally by following the instructions from: https://developer.apple.com/library/archive/technotes/tn2432/_index.html
Best regards,
The App Store Team
******************************************

Seems like there was identical issue report has been made under 1.11.0, and would like to understand if this has been addressed in 1.12.1 or is there workaround that can be recommended.

Thank you.
KUNHO KO, MS Cloud Solution Architect based in Seoul.

**Comment by BrianMouncer** [comment] 2020-07-03 21:17
Yes, this is an item in our backlog but we have not finished the work to resolve this issue.
The root cause stems from an optional extension dll the the SDK will use if present (for ether compressed audio support or a conversation translation extension). These are optional, as you should not have to pay the disk space price in your app unless you application is actually using those features, but yet the AppStore is flagging them a missing.

After the 4th of July weekend, I will check with the Dev working on this work item and see if there is an ETA.
Last I checked, we didn't have a good solution to this yet.

**Comment by wony2** [comment] 2020-07-04 12:20
I have faced the same error !!!

If bitcode is disabled, it is transferred to AppStore, but it is not executed when downloaded.

**Comment by pankopon** [comment] 2020-07-06 20:24
Previously reported in #600.

**Comment by bedro96** [comment] 2020-07-07 09:23
Is there any update?

**Comment by jhakulin** [comment] 2020-07-10 06:50
@bedro96 We are working on to fix this in 1.13.0 release which comes later this month.

**Comment by oscholz** [comment] 2020-07-20 20:21
Closing this issue as the fix is in 1.13.0, which we will release in the next few days.

**Closed** 2020-07-20 20:21 UTC
Labels: bug, duplicate
