### ISSUE TITLE
Unable to contact server. StatusCode: 1006, undefined Reason

### ISSUE THREAD

**Issue by therowf** [Azure-Samples/cognitive-services-speech-sdk#292] opened 2019-07-02 07:21 UTC
I just copied and pasted the node js code and replace the filename, key, and region but it throws the following error:

E:\Upwork\stt\stt-new\controllers>node microsoft.js
Now recognizing from: m1561477818826.wav
SpeechRecognitionResult {
  privResultId: '1530E7597EE7496E91747B86931F79F9',
  privReason: 1,
  privText: undefined,
  privDuration: undefined,
  privOffset: undefined,
  privErrorDetails:
   'Unable to contact server. StatusCode: 1006, undefined Reason: ',
  privJson: undefined,
  privProperties:
   PropertyCollection {
     privKeys: [ 'CancellationErrorCode' ],
     privValues: [ 'ConnectionFailure' ] } }
Trace: err - Runtime error: Unable to contact server. StatusCode: 1006, undefined Reason:
    at E:\Upwork\stt\stt-new\controllers\microsoft.js:56:13
    at E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\sdk\SpeechRecognizer.js:157:21
    at E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\sdk\Recognizer.js:129:17
    at Sink.executeErrorCallback (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:351:21)
    at Sink.reject (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:318:23)
    at Deferred.reject (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:281:28)
    at E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:193:46
    at Sink.executeErrorCallback (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:351:21)
    at Sink.reject (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:318:23)
    at Deferred.reject (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:281:28)
E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:354
                    throw new Error("'Unhandled callback error: " + e + ". InnerError: " + error + "'");
                    ^

Error: 'Unhandled callback error: Error: 'Cannot reject a completed promise'. InnerError: 'Unhandled callback error: Error: 'Cannot reject a completed promise'''
    at Sink.executeErrorCallback (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:354:27)
    at Sink.executeSuccessCallback (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:345:23)
    at Sink.resolve (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:306:23)
    at Deferred.resolve (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common\Promise.js:277:28)
    at WebSocket._this.privWebsocketClient.onclose (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\distrib\lib\src\common.browser\WebsocketMessageAdapter.js:107:59)
    at WebSocket.onClose (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.emitClose (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\node_modules\ws\lib\websocket.js:182:12)
    at ClientRequest.req.on (E:\Upwork\stt\stt-new\node_modules\microsoft-cognitiveservices-speech-sdk\node_modules\ws\lib\websocket.js:569:15)
    at ClientRequest.emit (events.js:182:13)

Here is my code

```

var sdk = require("microsoft-cognitiveservices-speech-sdk");
var fs = require("fs");

// replace with your own subscription key,
// service region (e.g., "westus"), and
// the name of the file you want to run
// through the speech recognizer.
var subscriptionKey = "466905518**********4bf9a705d";
var serviceRegion = "westus"; // e.g., "westus"
var filename = "m1561477818826.wav"; // 16000 Hz, Mono

// create the push stream we need for the speech sdk.
var pushStream = sdk.AudioInputStream.createPushStream();

// open the file and push it to the push stream.
fs.createReadStream(filename).on('data', function(arrayBuffer) {
  pushStream.write(arrayBuffer.buffer);
}).on('end', function() {
  pushStream.close();
});

// we are done with the setup
console.log("Now recognizing from: " + filename);

// now create the audio-config pointing to our stream and
// the speech config specifying the language.
var audioConfig = sdk.AudioConfig.fromStreamInput(pushStream);
var speechConfig = sdk.SpeechConfig.fromSubscription(subscriptionKey, serviceRegion);

// setting the recognition language to English.
speechConfig.speechRecognitionLanguage = "en-US";

// create the speech recognizer.
var recognizer = new sdk.SpeechRecognizer(speechConfig, audioConfig);

// start the recognizer and wait for a result.
recognizer.recognizeOnceAsync(
  function (result) {
    console.log(result);

    recognizer.close();
    recognizer = undefined;
  },
  function (err) {
    console.trace("err - " + err);

    recognizer.close();
    recognizer = undefined;
  });
```

**Comment by wolfma61** [comment] 2019-07-02 07:24
@therowf - please edit the message remove your subscription key!

**Comment by therowf** [comment] 2019-07-02 07:29
@wolfma61  It was only to see if the subscription key was correct. There I have got 2 keys. Like key1 and key2. Could you let me know which one should use?

**Comment by MazueraAlvaro** [comment] 2019-07-15 15:19
Is a bug, because in the error detail: 'Unable to contact server. StatusCode: 1006, undefined Reason: ', instead of 'undefined' should be the requested URL.

**Comment by willemotlucas** [comment] 2019-08-19 10:56
I'm experiencing the same issue, but not on every call to speech recognition service. 

It seems that this error message is triggered 120 seconds after trying to start a session with the recognize stram, as it would be a timeout from the server or the client.

@therowf Did you manage to solve this problem, or at least to understand the root cause?

**Comment by beelzabub** [comment] 2019-10-01 21:56
Has anybody come to a resolution on this? I am having the same issue. My subscription key and region are correct but still get the "Unable to contact server" message.

Thanks.

**Comment by rhurey** [comment] 2019-10-02 05:00
Can you turn the logging up and run the sample again?

To turn the logging up, inject this code into the beginning of the JS file node will run:
```
var evtExport = require("./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common/Exports");
var browserExport = require("./node_modules/microsoft-cognitiveservices-speech-sdk/distrib/lib/src/common.browser/Exports");
evtExport.Events.instance.attachListener(new browserExport.ConsoleLoggingListener(evtExport.EventType.Debug));
```
This will send more messages to the console. Please redact your key from the connection message with the URL in it.

**Comment by beelzabub** [comment] 2019-10-02 16:50
Hello rhurey, here you go

 | privMetadata: {} | privRequestId: F9F6E95C155D4956A1D675A35A1CD140 | privSessionId: 71D29D1AF1B8430EB425FA466584113D | privAuthFetchEventid: EEE3372AF7A148DAA17FE10D5BCAE769
undefined | undefined | privName: ConnectionStartEvent | privEventId: 319F2DCA2A4640219F2B17AC1A57B3F2 | privEventTime: 2019-10-02T16:47:50.063Z | privEventType: 1 | privMetadata: {} | privConnectionId: 71D29D1AF1B8430EB425FA466584113D | privUri: wss://speech.platform.bing.com/speech/uswest/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=c6b2e804d6054505940fca229040abf1&X-ConnectionId=71D29D1AF1B8430EB425FA466584113D | privHeaders: <NULL>
(cancel)

**Comment by chlandsi** [comment] 2019-10-02 16:53
Please don't post subscription keys. I would suggest to edit the message to remove the key and regenerate your key from the speech resource in the Azure portal.

**Comment by rhurey** [comment] 2019-10-02 18:21
Thanks, that log was helpful.

Are you buy chance using the IntentRecognizer with a Speech Recognition key?

IntentRecognition needs keys from Language Understanding and not Speech. 

We're working to simplify that.

**Comment by beelzabub** [comment] 2019-10-02 19:14
The IntentRecognizer takes a SpeechConfig and an AudioConfig. The speech config is initiated with the Speech subscription key. Below is the relevant code. Where do I set the IntentRecognizer key with a LUIS key?

//var intentConfig = sdk.SpeechConfig.fromSubscription(settings.luSubscriptionKey, settings.luServiceRegion);
            var intentConfig = sdk.SpeechConfig.fromSubscription(settings.subscriptionKey, settings.serviceRegion);
            var audioConfig = sdk.AudioConfig.fromStreamInput(audioStream);

            // setting the recognition language to English.
            intentConfig.speechRecognitionLanguage = settings.language;

            // create the translation recognizer.
            var recognizer = new sdk.IntentRecognizer(intentConfig, audioConfig);

            // Set up a Language Understanding Model from Language Understanding Intelligent Service (LUIS).
            // See https://www.luis.ai/home for more information on LUIS.
            if (settings.luAppId !== "" && settings.luAppId !== "YourLanguageUnderstandingAppId") {
                var lm = sdk.LanguageUnderstandingModel.fromAppId(settings.luAppId);
                recognizer.addAllIntents(lm);
            }

**Comment by rhurey** [comment] 2019-10-02 19:52
You use the LUIS key instead of the Speech key.

**Comment by beelzabub** [comment] 2019-10-02 19:53
When I do that I get

**Comment by rhurey** [comment] 2019-10-02 20:01
Just to be sure... It's a LUIS EndPoint key and not an authoring key?

The first part of this HowTo goes into the setup and key extraction steps:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-recognize-intents-from-speech-csharp

Glad to help, sorry this is so confusing and complicated.

**Comment by beelzabub** [comment] 2019-10-04 15:00
I was using the Starter key. Creating a LUIS resource and assigning my app to the resource solved the issue. Thank you very much for the assist!

**Comment by pankopon** [comment] 2019-12-06 19:03
Closing the issue as resolved.

**Closed by pankopon** 2019-12-06 19:03 UTC

**Comment by aditya-protonn** [comment] 2021-05-27 07:36
I'm still getting this error 
"Unable to contact server. StatusCode: 1006, undefined Reason:  undefined"

Have put the correct subscription key and region. I'm using the quickstart browser sample app "quickstart/javascript/browser/from-microphone/index.html"

**Comment by dargilco** [comment] 2021-05-27 16:46
@aditya-protonn I see you already opened an issue for this in the JS SDK repo. We will follow up there.
https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/296#issuecomment-849423282

**Comment by Slinjez** [comment] 2021-08-15 02:11
I have the same error, however, I'm suspecting that my company firewall or Antivirus could be blocking the request. I will update once I get it resolved.

![image](https://user-images.githubusercontent.com/8165854/129464742-34e06c1d-8263-4431-b257-011936878ae7.png)

**Comment by mallipriya** [comment] 2022-06-26 16:01
I am facing the same error when trying to run the speech-to-text azure cognitive service sample.

The reason for the result remains undefined though I regenerated the subscription key.

Below is the error that appears in console 
![image](https://user-images.githubusercontent.com/51745381/175822938-a69d9a8a-ee03-4635-83b6-932be3a1ac92.png)

@therowf,@aditya-protonn,@Slinjez is your issue resolved?

**Comment by bahaa-mp** [comment] 2022-10-19 01:50
My issue was resolved by waiting a second between requests 🤔

**Comment by timohausmann** [comment] 2024-01-23 22:37
I encountered this message with expired tokens. I used a next.js `app/api/route.ts` to get the token, which is cached by default so after a while it returned stale tokens. Adding `export const revalidate = 0;` to the route (or `{ cache: 'no-store' }` to the fetch) fixed it.

**Comment by abhimanyusood** [comment] 2024-06-28 18:29
> I have the same error, however, I'm suspecting that my company firewall or Antivirus could be blocking the request. I will update once I get it resolved.
> 
> ![image](https://user-images.githubusercontent.com/8165854/129464742-34e06c1d-8263-4431-b257-011936878ae7.png)

This is what finally worked for me! I was facing this issue in the Azure AI Speech Studio with a brand new account and a brand new resource (F0), and disabling Avast ANTI-VIRUS is what immediately resolved the issue for me. The strange thing is, after I turned Avast back on after a few minutes, the issue stayed resolved! Make of that what you will.

**Comment by Arnack** [comment] 2024-11-05 10:34
> I encountered this message with expired tokens. I used a next.js `app/api/route.ts` to get the token, which is cached by default so after a while it returned stale tokens. Adding `export const revalidate = 0;` to the route (or `{ cache: 'no-store' }` to the fetch) fixed it.

That helped me, thanks @timohausmann
