### ISSUE TITLE
API Issue in creating custom acoustic model using Python

### ISSUE THREAD

**Issue by kishan19** [Azure-Samples/cognitive-services-speech-sdk#556] opened 2020-03-18 10:46 UTC
Good Day

We are trying to create a new acoustic model in the custom speech portal, with the following cases (we have attached python code below), and keep hitting an error saying the base model is not valid for the operation.

Case 1: Creating a Acoustic and Language model, using Microsoft’s base model (20191202), which is provided as base model ID starting with 7ff…

We are adding a customize dataset of audio and transcripts which is provided in the dataset array. This is a straightforward process we are following with regard to how we do in the portal, but we want to use the APIs to build a continuous workflow. We need your help in understanding what we are doing wrong. 

Error returned is : {'code': 'InvalidPayload',
 'message': "The base model isn't valid for this operation."}

CODE SNIPPET: 

model_base_url='https://southeastasia.cris.ai/api/speechtotext/v2.0/models'
data={
  "modelKind": "Acoustic",
  "baseModel": {
    "id": "7f446829-6b5e-4284-b9e1-b4a2c2401471"
  },
  "datasets": [
    {
      "id": "bc8ab9a3-c792-4ebd-9ecd-7ed20c315fdc"
    }
  ],
  "locale": "en-US",
  "name": "HW1",
  "description": "Sample model"
}
body=str.encode(json.dumps(data))

model_request=requests.post(model_base_url,headers=speech_base_headers,data=body)
print(model_request.status_code)
model_request.json()

Please revert back at the earliest, as this is a severe roadblock for us.

**Comment by zhouwangzw** [comment] 2020-03-19 13:41
Sorry for the problem. We have identified the issue and the fix will be rolled out in the next days.

**Comment by kishan19** [comment] 2020-03-19 14:12
Thank you, please provide us an update.

**Comment by andreasjl** [comment] 2020-03-19 14:49
Acoustic adaptation is not supported on all base models yet. The one you selected does not support it yet but only language adaptation. While we are working on enabling acoustic adaptation also on more models, you have two options:

1. Pick another model that has the purpose "AcousticAdapation" set.

2. Use only language adaptation in the meantime.

**Comment by jossava** [comment] 2020-04-07 20:33
Hello,

we are trying to train a custom model also in the custom speech portal and we have the same error:
"**Failed to train model** Failed to train model test2. Error: The base model isn't valid for this operation.."

Does anyone have any updates about this?

**Comment by zhouwangzw** [comment] 2020-04-07 20:46
The error is unfortunately caused by a bug. The fix will be rolled out very soon.

Sorry for the trouble.

**Comment by pankopon** [comment] 2020-06-13 00:55
@zhouwangzw Has the fix been released, can we close this issue?

**Comment by zhouwangzw** [comment] 2020-06-14 03:42
Yes, the issue should have been fixed. Closing the issue. Please re-open it or create a new one if you still see the problem.

**Closed by zhouwangzw** 2020-06-14 03:42 UTC
Labels: bug
