### ISSUE TITLE
No Continuous Speech Recognition Quickstart Sample Code?

### ISSUE THREAD

**Issue by cihanunlu** [Azure-Samples/cognitive-services-speech-sdk#1662] opened 2022-09-17 18:23 UTC
Hello guys,

As you know the repository includes a STT quick sample code (JS Browser) : [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser/translate-speech-to-text)

However, I am specifically looking for continous speech translation quickstart sample code. I could not find it anywhere else. 
Normally, I am supposed to bind "recognizing, recognized, and canceled" events to get results on the textarea html, but it did not give any result though i tried the additional code below.

Things got too complicated for me .
Is there any way to transform the available 'onceshot stt' into 'continuous speech translation' sample?

```
var speechConfig = SpeechSDK.SpeechTranslationConfig.fromSubscription(subscriptionKey.value, serviceRegion.value);

        speechConfig.speechRecognitionLanguage = languageSourceOptions.value;
        let language = languageTargetOptions.value
        speechConfig.addTargetLanguage(language)

        var audioConfig  = SpeechSDK.AudioConfig.fromDefaultMicrophoneInput();;

        recognizer = new SpeechSDK.TranslationRecognizer(speechConfig, audioConfig);
        recognizer.recognized = (s, e) => {
          if (e.result.reason == ResultReason.RecognizedSpeech) {
              console.log(`TRANSLATED: Text=${e.result.text}`);
              phraseDiv.innerHTML += `TRANSLATED: Text=${e.result.text}`
          }
          else if (e.result.reason == ResultReason.NoMatch) {
              console.log("NOMATCH: Speech could not be translated.");
          }
      };
        recognizer.startContinuousRecognitionAsync();
      });
```

**Comment by glharper** [comment] 2022-09-19 12:42
@cihanunlu Thanks for using Speech SDK, and writing this issue up. Please see [this multi-scenario sample](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/samples/js/browser) which encompasses continuous speech recognition and continuous translation scenarios, among others (callbacks set [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/24ee1373f8ce5996d1ed3f1e36a60d4028537054/samples/js/browser/index.html#L704), continuous speech recognition API called [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/24ee1373f8ce5996d1ed3f1e36a60d4028537054/samples/js/browser/index.html#L837), continuous translation code [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/24ee1373f8ce5996d1ed3f1e36a60d4028537054/samples/js/browser/index.html#L865))

Let us know if you're able to get that sample running.

**Comment by cihanunlu** [comment] 2022-09-19 20:09
> 

I have tried to extract to code there and implement it into the sample (once-shot) speech trans. code  but it did not work. I did not actually understand to which the"applyCommonConfigurationTo" is bound with. Second of all, I could not implement the text area html (phrasediv) to the recognized callback to show the result on the page. :(

**Comment by glharper** [comment] 2022-09-19 21:01
@cihanunlu First please, take the raw sample ([here](https://raw.githubusercontent.com/Azure-Samples/cognitive-services-speech-sdk/master/samples/js/browser/index.html)), and save it locally. Open the local file in your browser of choice, input your subscription key and region in the top fields, and then select the scenario you'd like to try. In your browser's dev tools, you can set breakpoints in the sample code to see where applyCommonConfigurationTo is called, and what the context is at that point.

Once you've confirmed the sample code works as intended, you can bit by bit change the code to match your intended use case, making sure the code performs as intended after each change.

Please let me know if that sample isn't working for you out of the box.

**Comment by cihanunlu** [comment] 2022-09-23 19:05
> @cihanunlu First please, take the raw sample ([here](https://raw.githubusercontent.com/Azure-Samples/cognitive-services-speech-sdk/master/samples/js/browser/index.html)), and save it locally. Open the local file in your browser of choice, input your subscription key and region in the top fields, and then select the scenario you'd like to try. In your browser's dev tools, you can set breakpoints in the sample code to see where applyCommonConfigurationTo is called, and what the context is at that point.
> 
> Once you've confirmed the sample code works as intended, you can bit by bit change the code to match your intended use case, making sure the code performs as intended after each change.
> 
> Please let me know if that sample isn't working for you out of the box.

Thanks. After a long dedication, I managed to extract unnecessary scenarios out of the sample code. 
But now there is another problem. I have customized and implemented the 'index.html' into a https server. It works fine but I want to use this in my web app. Therefore, I embedded this html using iframe tag.

The html frame appears normally but the functions (speech recognition) does not work when the html is displayed in iframe. When i open the frame in new tab, all functions work somehow.

**Comment by glharper** [comment] 2022-09-26 17:02
@cihanunlu I'm not super well-versed on expected iframe behavior, but I wonder if the the speech sdk import is binding correctly to the global "window" instance in an iframe. You can find out by putting "console.log(window); console.log(SpeechSDK);" where you'd expect the functions to work, and making sure the SpeechSDK instance and window instance have the expected structure.

More generally, though, I'd recommend finding a way to integrate SpeechSDK functions directly into your specific web app, as that seems simpler now that you can see how continuous recognition works.

I'm closing this issue, as we've strayed for the original question of an extant continuous recognition sample in JS.

**Closed by glharper** 2022-09-26 17:02 UTC
