### ISSUE TITLE
Error while processing longer audio file

### ISSUE THREAD

**Issue by grale88** [Azure-Samples/cognitive-services-speech-sdk#255] opened 2019-05-31 12:37 UTC
**Describe the bug**
I am processing longer wav file ~1h 15min and during processing I get the following error: 

Invalid parameter or unsupported audio format in the request. Response text:{"Duration":0,"Offset":10000000,"RecognitionStatus":"BadRequest"}

This error causes recognizer to stop, onCanceled method is called. Previously recognizer returned around ~140 results.

**To Reproduce**
1. Start continuous recognition with particular file

**Expected behavior**
Transcription finishes successfully

**Version of the Cognitive Services Speech SDK**
SDK 1.5.1

**Platform, Operating System, and Programming Language**
 - OS: Ubuntu 18.04
 - Hardware - x64
 - Programming language: Java

**Additional context**
 If you require I can provide you with the file I used for processing,

**Comment by rhurey** [comment] 2019-06-01 03:34
Well, that's definitely not expected. Sorry for the problems.

I'll take a look into this and see if I can reproduce the problem.

In the meantime, a couple of questions:
1) Have you been successful with other large files, and this one is troublesome?
2) Do you happen to have the sessionId for the recognition that failed?

Unrelated, but worth mentioning, have you considered using the batch API for long audio files like this?

**Comment by grale88** [comment] 2019-06-03 07:35
Hello @rhurey 

1. Yes, we were able to process other longer files, that were ~1h, ~1h 30min duration. With this one we experienced this kind of error.
2. Unfortunately I don't have the sessionId

I was not aware of batch API, I just had a look in the documentation. What are the limits in file size/duration that can be processed through batch API?

If you need the file for the issue reproduction I can upload it somewhere for you to test.

**Comment by chlandsi** [comment] 2019-06-03 08:00
Hi @grale88,

yes, please do upload the file so we can reproduce the problem.

About the batch service: There are no restrictions on file length and size. The API is different from the one the Speech SDK uses - the batch service reads files from a storage URI and produces a set of results after the full file has been processed, while the service the SDK uses receives streaming audio data and produces results on the fly.

**Comment by grale88** [comment] 2019-06-03 08:12
Hi @rhurey

Please find file uploaded on https://we.tl/t-WtdsOTTGkF
Thank you also on the details about batch API.

**Comment by chlandsi** [comment] 2019-06-03 09:26
Hi @grale88, did you use a stream to process the file, or did you decompress it before transcribing? If so, can you share the wav/PCM version of the file that was used? Thanks!

**Comment by grale88** [comment] 2019-06-03 10:52
Hi @chlandsi 
Yes, sorry I will attach once again the the file after conversion. File is converted using ffmpeg process before sending to the SDK, my bad...

New link: https://we.tl/t-v31FFatGyb

**Comment by chlandsi** [comment] 2019-06-03 12:14
There seems to be a problem with the wave file header - the chunk size is given as `ffff ffff`, which results in bad values for some parameters. This is the output of `shntool` for the file:
```
shntool info parlament.2.mp3.wav
-------------------------------------------------------------------------------
File name:                    parlament.2.mp3.wav
Handled by:                   wav format module
Length:                       9607679205057:0
WAVE format:                  0x0001 (Microsoft PCM)
Channels:                     1
Bits/sample:                  16
Samples/sec:                  16000
Average bytes/sec:            32000
Rate (calculated):            32000
Block align:                  2
Header size:                  78 bytes
Data size:                    18446744073709551615 bytes
Chunk size:                   18446744073709551615 bytes
Total size (chunk size + 8):  7 bytes
Actual file size:             146434586
File is compressed:           no
Compression ratio:            20919226.5714
CD-quality properties:
  CD quality:                 no
  Cut on sector boundary:     n/a
  Sector misalignment:        n/a
  Long enough to be burned:   n/a
WAVE properties:
  Non-canonical header:       yes
  Extra RIFF chunks:          no
Possible problems:
  File contains ID3v2 tag:    no
  Data chunk block-aligned:   no
  Inconsistent header:        yes
  File probably truncated:    no
  Junk appended to file:      yes (146434579 bytes)
  Odd data size has pad byte: unknown
```

I don't know what could be the source of this problem; when I use ffmpeg to convert the mp3 file the resulting header looks fine.
```
shntool info parlament.mine.wav
-------------------------------------------------------------------------------
File name:                    parlament.mine.wav
Handled by:                   wav format module
Length:                       76:16.078
WAVE format:                  0x0001 (Microsoft PCM)
Channels:                     1
Bits/sample:                  8
Samples/sec:                  16000
Average bytes/sec:            16000
Rate (calculated):            16000
Block align:                  1
Header size:                  78 bytes
Data size:                    73217254 bytes
Chunk size:                   73217324 bytes
Total size (chunk size + 8):  73217332 bytes
Actual file size:             73217332
File is compressed:           no
Compression ratio:            1.0000
CD-quality properties:
  CD quality:                 no
  Cut on sector boundary:     n/a
  Sector misalignment:        n/a
  Long enough to be burned:   n/a
WAVE properties:
  Non-canonical header:       yes
  Extra RIFF chunks:          no
Possible problems:
  File contains ID3v2 tag:    no
  Data chunk block-aligned:   yes
  Inconsistent header:        no
  File probably truncated:    no
  Junk appended to file:      no
  Odd data size has pad byte: n/a

```
Closing this since it doesn't look like an SDK issue; please reopen if you continue to have problems.

**Closed by chlandsi** 2019-06-03 12:14 UTC
