### ISSUE TITLE
Unsupported language results in empty sound

### ISSUE THREAD

**Issue by valerauko** [Azure-Samples/cognitive-services-speech-sdk#2268] opened 2024-02-20 05:28 UTC
**Describe the bug**

In Java SDK, SpeechSynthesizer SpeakText returns successfully despite failed synthesis.

We have a number of preferred voices. When the user chooses a language yet provides text to read in a different language, I expected the SpeakText call to end with an "unsuccessful" ResultReason, but it still ends with SynthesizingAudioCompleted and a 0 byte audio stream.

**To Reproduce**

1. set `ja-JP-NanamiNeural` as the desired voice
2. give the SpeakText call some Thai language text

**Expected behavior**

SpeakText results in an identifiable unsuccessful result.

**Version of the Cognitive Services Speech SDK**

1.35.0

**Platform, Operating System, and Programming Language**

 - OS: containerized Debian Bullseye (required dependencies are installed)
 - Programming language: Java SDK from Clojure

**Additional context**

After the silently failed synthesis .getAudioData returns 0 bytes, so the failure _can_ be detected, but this behavior feels accidental (I couldn't find any documentation about this and I don't know if it's safe to rely on this behavior)

Speech log: [speech.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/14339779/speech.log)

**Comment by yulin-li** [comment] 2024-03-12 05:15
Hi @valerauko this is by designed. The service would skip all unreadable words. @Kerry-LinZhang please help to track this issue and feedback to the engineers.

**Comment by pankopon** [comment] 2024-03-13 20:44
Closed as by design. @yulin-li @Kerry-LinZhang Would be good to document this clearly in public, if not already done.

**Closed by pankopon** 2024-03-13 20:44 UTC
Labels: enhancement, in-review, text-to-speech, pending close
