### ISSUE TITLE
Properties to define : Max Audio Recognition Time  from Microphone OR Stop Recognition on silence

### ISSUE THREAD

**Issue by viju2008** [Azure-Samples/cognitive-services-speech-sdk#615] opened 2020-05-02 12:43 UTC
Hello,

I am doing speech recognition and am using Android SDK. I plan to move to containers in future.  Stopping on silence is default as per documentation. How do i define the following the max audio time recognition time as below:

1) If the user is speaking and has spoken more than 15 seconds. The sdk should automatically stop the recognizer on Android end. If the user has spoken less than 15 seconds and was silent in between then it should be based on silence detection. The speech sdk should stop the microphone on android either on silence detection (when spoken < 15 seconds) or on completion of user saying 15 second audio.

2) In the container back-end how can i specify that the maximum audio length should be for 15 seconds . I could not find any such provision in the container documentation

Regards,

**Comment by viju2008** [comment] 2020-05-07 05:42
Hello Team,

Any updates.

**Comment by rhurey** [comment] 2020-05-07 15:13
Calling the RecognizeOnceAsync() API will get behavior close to what you want. The maximum phrase length is currently not adjustable through the SDK, but is near 15 seconds.

**Comment by viju2008** [comment] 2020-05-09 06:35
> Calling the RecognizeOnceAsync() API will get behavior close to what you want. The maximum phrase length is currently not adjustable through the SDK, but is near 15 seconds.

Can you tell me the exact legth using the RecognizeOnceAsync()

**Comment by pankopon** [comment] 2020-06-13 02:30
Duplicate of https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/625.

**Closed by pankopon** 2020-06-13 02:30 UTC
