### ISSUE TITLE
【Android】 In some mobile phones, such as Samsung s8, pixel2, it always reports WS_ERROR_UNDERLYING_IO_ERROR

### ISSUE THREAD

**Issue by livesun** [Azure-Samples/cognitive-services-speech-sdk#251] opened 2019-05-31 03:33 UTC
#### Version of the Cognitive Services Speech SDK
com.microsoft.cognitiveservices.speech:client-sdk:1.5.1

#### problem
I use it on my Android program and use AuidoConfig with a custom PullAudioInputStreamCallback.
```
//This is pseudo code
public class PhoneStream extends PullAudioInputStreamCallback

  AudioConfig audio = AudioConfig.fromStreamInput(PhoneStream.getInstance());

   TranslationRecognizer   reco = new TranslationRecognizer(translationSpeechConfig,audio);
```

In some mobile phones, such as Samsung s8, pixel2, it always reports this error：WebSocket operation failed. Internal error: 3. Error details: WS_ERROR_UNDERLYING_IO_ERROR code ConnectionFailure。

But it works fine on other phones.

**Comment by fmegen** [comment] 2019-06-04 15:52
Hi livesun,

sorry to hear that you have problems with our sdk.

In order to investigate the root cause for your problem, I would need additional information.
In particular,
  - did you try to compile and run the quickstart application?
  - do you have more information about the error returned by the sdk? especially the errorDetails property would be interesting as it gives more details than just the error code.
  - do you have logcat information you can share?
  - can you please verify that the clock of your devices is correct and that the devices have up-to-date root certificates installed. If any of these are incomplete or time is not correct you will see that the phone will connect, but fail to complete the handshake with the service backend.

thanks a lot for your help!

kind regards,
 friedel

**Comment by wolfma61** [comment] 2019-07-01 12:48
@livesun - any more feedback you can give us? 
Can you try with the latest version?

thx
Wolfgang

**Comment by wolfma61** [comment] 2019-07-01 13:20
also, please see #253

**Comment by wolfma61** [comment] 2019-09-19 15:19
no feedback - closing

**Closed by wolfma61** 2019-09-19 15:19 UTC
