### ISSUE TITLE
App crashing - JNI detected error

### ISSUE THREAD

**Issue by misanchez123** [Azure-Samples/cognitive-services-speech-sdk#347] opened 2019-08-13 10:36 UTC
**Issue**
Application is crashing, 3 out of 10 times. Error shows few seconds (>5secs) after starting the continuous TranslationRecognizer. 

We created an app that creates two TranslationRecognizer, each of the recognizer has their own input source (Mic). 

We follow the code based from this example. 
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/TranslationSamples.java

**Version of the Cognitive Services Speech SDK**
1.6.0

**Platform, Operating System, and Programming Language**
 - OS: Android (SDK 28)
 - Hardware - arm

2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art: JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x200009
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     from void com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.RecognitionEventListener_director_connect(com.microsoft.cognitiveservices.speech.internal.RecognitionEventListener, long, boolean, boolean)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art: "AsyncTask #3" prio=5 tid=18 Runnable
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   | group="main" sCount=0 dsCount=0 obj=0x12e53f70 self=0x72ccdb3200
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   | sysTid=14026 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0x72cb88c450
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   | state=R schedstat=( 813380867 223706531 1142 ) utm=76 stm=5 core=1 HZ=100
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   | stack=0x72cb78a000-0x72cb78c000 stackSize=1037KB
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   | held mutexes= "mutator lock"(shared held)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #00 pc 000000000047c250  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+220)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #01 pc 000000000047c24c  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+216)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #02 pc 00000000004503a8  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+944)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #03 pc 00000000002ee034  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1560)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #04 pc 00000000002ef710  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+188)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #05 pc 000000000045500c  /system/lib64/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+352)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #06 pc 00000000001014d4  /system/lib64/libart.so (_ZN3art11ScopedCheck13CheckInstanceERNS_18ScopedObjectAccessENS0_12InstanceKindEP8_jobjectb+196)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #07 pc 00000000000ff6e4  /system/lib64/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+1124)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #08 pc 00000000000f47e0  /system/lib64/libart.so (_ZN3art8CheckJNI12IsSameObjectEP7_JNIEnvP8_jobjectS4_+632)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #09 pc 00000000000d9524  /data/app/cz.acrobits.demophone.android-2/lib/arm64/libMicrosoft.CognitiveServices.Speech.java.bindings.so (_ZN37SwigDirector_RecognitionEventListener21swig_connect_directorEP7_JNIEnvP8_jobjectP7_jclassbb+188)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:   native: #10 pc 0000000000041170  /data/app/cz.acrobits.demophone.android-2/oat/arm64/base.odex (Java_com_microsoft_cognitiveservices_speech_internal_carbon_1javaJNI_RecognitionEventListener_1director_1connect__Lcom_microsoft_cognitiveservices_speech_internal_RecognitionEventListener_2JZZ+172)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.RecognitionEventListener_director_connect(Native method)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at com.microsoft.cognitiveservices.speech.internal.RecognitionEventListener.<init>(RecognitionEventListener.java:59)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at com.microsoft.cognitiveservices.speech.Recognizer$RecognitionEventHandlerImpl.<init>(Recognizer.java:170)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at com.microsoft.cognitiveservices.speech.Recognizer.<init>(Recognizer.java:64)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at com.microsoft.cognitiveservices.speech.translation.TranslationRecognizer.<init>(TranslationRecognizer.java:47)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at cz.acrobits.demophone.android.MainActivity.translationWithAudioStreamAsyncRemote(MainActivity.java:1301)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at cz.acrobits.demophone.android.MainActivity.access$1500(MainActivity.java:92)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at cz.acrobits.demophone.android.MainActivity$6.doInBackground(MainActivity.java:1566)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at cz.acrobits.demophone.android.MainActivity$6.doInBackground(MainActivity.java:1560)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at android.os.AsyncTask$2.call(AsyncTask.java:304)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-08-13 18:07:21.099 13986-14026/cz.acrobits.demophone.android E/art:     at java.lang.Thread.run(Thread.java:761)
2019-08-13 18:07:21.111 13986-14026/cz.acrobits.demophone.android A/art: art/runtime/java_vm_ext.cc:496] JNI DETECTED ERROR IN APPLICATION: use of deleted local reference 0x200009
2019-08-13 18:07:21.111 13986-14026/cz.acrobits.demophone.android A/art: art/runtime/java_vm_ext.cc:496]     from void com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.RecognitionEventListener_director_connect(com.microsoft.cognitiveservices.speech.internal.RecognitionEventListener, long, boolean, boolean)

**Comment by jhakulin** [comment] 2020-05-08 20:40
Closing this issue as not reproducible, I created an app which use 2 TranslationRecognizers, one which listen microphone and one which listens stream (from wavefile). Could not reproduce the crash, please reopen if the issue is still valid and reproducible

**Closed by jhakulin** 2020-05-08 20:40 UTC
Labels: bug
