### ISSUE TITLE
 iOS 16 - SPXSpeechSynthesizer error

### ISSUE THREAD

**Issue by danigutierrezayuso** [Azure-Samples/cognitive-services-speech-sdk#1613] opened 2022-08-09 11:05 UTC
When using the speech synthesizer 'speakSsml' function on iOS 16 an error is returned:

[AudioConverter] CompositeAudioConverter.cpp:1082  kAudio_ParamError: packet description 1 of 2: range 5662468096-5662468098, 576 data bytes

We are using the latest 1.23 version of the framework.

This was working fine on iOS 15 and now it's returning 0 bytes of audio.

**Comment by ralph-msft** [comment] 2022-08-09 19:33
In order to be able to debug this issue, could you please share the following:
* The SDK logs. You can find instructions on how to enable logging here: https://docs.microsoft.com/azure/cognitive-services/speech-service/how-to-use-logging#ios
* The minimum code that reproduces your issue. In particular this should include the configuration you are using with the speech synthesizer (speech output formats, sample input to reproduce the issue, etc..). Please make sure you do --**_not_**-- include any subscription keys or auth tokens in your code

**Comment by danigutierrezayuso** [comment] 2022-08-10 09:12
Hi Ralph,

Here is the log
[swift.log](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9298602/swift.log)

And this is the configuration that we are using:

```
let filePath = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).map(\.path)[0]
let fileName = "/wavefile.wav"
let fileAtPath = filePath + fileName
if !FileManager.default.fileExists(atPath: fileAtPath) {
        FileManager.default.createFile(atPath: fileAtPath, contents: nil, attributes: nil)
}
try! audioConfig = SPXAudioConfiguration(wavFileOutput: fileAtPath)
try! speechConfig = SPXSpeechConfiguration(authorizationToken: azureToken, region: "westeurope")
let synthetizer = try! SPXSpeechSynthesizer(speechConfiguration: speechConfig, audioConfiguration: audioConfig)
let result = try! synthetizer.speakSsml(ssml)
```

Thank you for helping us!

**Comment by ralph-msft** [comment] 2022-08-11 20:47
Thanks for the additional information, we are investigating this issue and will post an update here once we have more information

**Comment by yulin-li** [comment] 2022-08-12 12:18
Looks the issue is from audio decoding. The SDK would automatically use the compressed audio format (mp3) when requesting service and decode it using Apple's API to pcm formats. As it broken on iOS 16, there might be some API change in new iOS version.

We will investigate this issue further

**Comment by yulin-li** [comment] 2022-08-13 02:53
BTW, could you try to set `SpeechServiceConnection_SynthEnableCompressedAudioTransmission ` to `false` to disable the compress transmission feature? see [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/releasenotes?tabs=speech-sdk#new-features-7)

**Comment by yulin-li** [comment] 2022-08-13 05:17
Hi @danigutierrezayuso, I tried to repro this issue but failed. I installed xcode 14 beta with iOS 16 simulator on my macbook and run the [quickstart](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/swift/ios/text-to-speech) and everything works well in the simulator.

Could you try the quickstart to see if you can repro?

**Comment by danigutierrezayuso** [comment] 2022-08-16 13:31
Hi @yulin-li, this is only failing on actual devices. It always works fine on the simulator.

I've tried to set `speechServiceConnectionSynthesisEnableCompressedAudioTransmission` to false and now it's working perfectly after that change. Thank you!

**Comment by yulin-li** [comment] 2022-08-26 06:45
We have fixed this internally and the fix will be released with 1.24.

I'd like to keep this issue open until 1.24 released.

**Comment by pankopon** [comment] 2022-09-01 23:50
To be closed when the Speech SDK 1.24.0 release is available (latest estimate by the end of September this year).

**Comment by tomthecarrot** [comment] 2022-09-22 06:09
We are also encountering this issue on iOS 16 devices - it results in a consistently-reproducible crash. iOS 15 devices work fine. Additionally, using an 8KHz output format (`SpeechSynthesisOutputFormat.Raw8Khz16BitMonoPcm`) does work.

**Comment by yulin-li** [comment] 2022-09-28 04:46
> We are also encountering this issue on iOS 16 devices - it results in a consistently-reproducible crash. iOS 15 devices work fine. Additionally, using an 8KHz output format (`SpeechSynthesisOutputFormat.Raw8Khz16BitMonoPcm`) does work.
> 
> Is there an updated ETA on this? Until it is fixed, we cannot ship our update due to crashing on iOS 16.

The ETA is mid-Oct.

**Comment by yulin-li** [comment] 2022-10-20 05:52
Closing this issue as 1.24 is released.

**Closed by yulin-li** 2022-10-20 05:52 UTC
Labels: bug, tts, pending close, accepted

**Comment by guris12** [comment] 2023-01-31 11:19
> Hi @yulin-li, this is only failing on actual devices. It always works fine on the simulator.
> 
> I've tried to set `speechServiceConnectionSynthesisEnableCompressedAudioTransmission` to false and now it's working perfectly after that change. Thank you!

how can we set this variable to false ?
