### ISSUE TITLE
Speech SDK on Azure WebApp (Windows x64)

### ISSUE THREAD

**Issue by jnickels** [Azure-Samples/cognitive-services-speech-sdk#396] opened 2019-10-10 14:54 UTC
Hi all,

I try using the speech sdk in a java spring boot project on a azure web app (windows x64).
On my local dev env. everything works fine (Mac OS 10.14.6).
Whenever I try using the deployed version I always receive:
`org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()V
.....`
`Caused by: java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()V`

The azure WebApp General Settings look like this:
![image](https://user-images.githubusercontent.com/147950/66580293-7736d680-eb7e-11e9-893e-727259b131c9.png)

We also tried it with Java 1.8. No difference at all. Also on my local dev env. it works with both java versions. 
Our code follows the given examples in this repo and of course we are using the latest sdk version 1.7.0
Any ideas?

**Comment by amitkumarshukla** [comment] 2019-10-11 21:01
@jnickels 
Thanks a lot for reporting the issue. I will look into it and come back to you.

**Comment by jnickels** [comment] 2019-10-19 10:53
Any updates on this issue?

**Comment by amitkumarshukla** [comment] 2019-10-23 16:47
@jnickels I am looking into it and will get back to you very soon.

**Comment by jnickels** [comment] 2019-10-28 19:16
@amitkumarshukla any news?

**Comment by mahilleb-msft** [comment] 2019-10-30 18:18
Just wondering whether the C++ redistributable is installed in your target environment?

https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/ship-application#windows

Not sure what's the best way to get it into web app (copying the DLLs it installs should work, if these are in path).

**Comment by jnickels** [comment] 2019-11-07 12:25
which DLLs? All of them?! Am I the only one having problems with Speech SDK on azure web app resource?

**Comment by jnickels** [comment] 2019-11-12 08:14
Hi all,
 
did several checks now:
                It works on Azure Ubuntu VM if you start it via console
                It works on Azure Win 10 VM if you run it via Eclipse
                It works on Mac OSX local Dev machine if you run it via IntelliJ or console
                It works on Win 10 local Dev machine if you run it via IntelliJ/Eclipse
                It is NOT working on Azure WebApp (Linux&Win) started via console (triggered by web.config)
                It is NOT working on Azure Win 10 VM if you start it via console
                It is NOT working on Win 10 local Dev machine if you start it via console.
 
That’s the exception I receive when a streaming request hits the Service:
 
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()V
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1054)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:876)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
                …..
Caused by: java.lang.UnsatisfiedLinkError: com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init()V
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.swig_module_init(Native Method)
        at com.microsoft.cognitiveservices.speech.internal.carbon_javaJNI.<clinit>(carbon_javaJNI.java:893)
        at com.microsoft.cognitiveservices.speech.SpeechConfig.<clinit>(SpeechConfig.java:70)
        at com.bmw.connected.mvs.backend.stt.business.SpeechServicesService.receiveTextFromAudio(SpeechServicesService.java:44)
        at com.bmw.connected.mvs.backend.stt.business.SpeechServicesService$$FastClassBySpringCGLIB$$c4bf2594.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
 
 
For me it looks like there is an problem how the sdk tries to resolve the native library on windows.

**Comment by amitkumarshukla** [comment] 2019-11-12 22:21
If you can please send me your sample code. Also send me the command line you used to run it on "It is NOT working on Win 10 local Dev machine if you start it via console."

**Comment by jnickels** [comment] 2019-11-13 11:03
If I run it from console I use the following command:
`java -Dserver.port=8090 -Dspring.profiles.active=mock-profile -jar myJarFile.jar `

Unfortunatelly I can't give you my sample code. But please take a look on your NativeLibraryLoader.java. We decompiled it and it looks like there are some errors loading the DLLs on windows machines.

**Comment by jhakulin** [comment] 2019-11-22 23:16
We know the root cause of the issue and are working on fix, closing the issue from here.

**Closed by jhakulin** 2019-11-22 23:16 UTC
