### ISSUE TITLE
 Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED

### ISSUE THREAD

**Issue by xyi919** [Azure-Samples/cognitive-services-speech-sdk#1702] opened 2022-10-19 09:02 UTC
Describe the bug
connectionFailure

CANCELED: ErrorDetails=Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED [0x80000001 | 2]
wss://chinaeast2.stt.speech.azure.cn/speech/recognition/conversation/cognitiveservices/v1?format=detailed&language=zh-CN&wordLevelConfidence=true&wordLevelTimestamps=true
X-ConnectionId: 03807ee539ac4291acb3ebd19c1e620b SessionId: 03807ee539ac4291acb3ebd19c1e620b

SDK version: 1.21

Platform, windows 11 jdk1.8

supplement: both region and key are correct. I can't connect to my own computer, but my colleague's computer is ok .it's weird.

**Comment by rhurey** [comment] 2022-10-19 20:57
Typically to diagnose connection problems the simplest thing is to try and access the supported languages REST API from a machine having trouble.

Can you access https://chinaeast2.stt.speech.azure.cn/api/v1.0/languages/recognition? There's no auth required.
Curl, browser, either should work.

**Comment by xyi919** [comment] 2022-10-20 00:42
this is ok.

**Comment by rhurey** [comment] 2022-10-20 00:48
Is it possible to send a log file? Instructions are at: https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging

**Comment by BenjayLin** [comment] 2022-10-20 07:27
@rhurey  Hi,I also have this problem. The attachment is my log.

Session stopped.
Encountered error.
Error code: 5
Error details: Connection failed (no connection to the remote host). Internal error: 1. Error details: Failed with error: WS_OPEN_ERROR_UNDERLYING_IO_OPEN_FAILED
wss://chinaeast2.stt.speech.azure.cn/speech/recognition/conversation/cognitiveservices/v1?language=zh-CN&postprocessing=TrueText&profanity=masked&stableIntermediateThreshold=5
X-ConnectionId: a2738f40d473490fbf1661b8d486d66e SessionId: a2738f40d473490fbf1661b8d486d66e

Platform, windows 11  .net core 3.1    SDK version:1.24.0

[log.txt](https://github.com/Azure-Samples/cognitive-services-speech-sdk/files/9827277/log.txt)

**Comment by rhurey** [comment] 2022-10-20 15:03
Ok, this may be another manifestation of #1692's root cause.

Can you try either uninstalling the latest Windows Update that was applied recently, or if applicable one of the updates listed in issue #1692?

**Comment by BenjayLin** [comment] 2022-10-21 01:51
It is normal after installing this update, thank you!
[https://learn.microsoft.com/zh-cn/windows/release-health/resolved-issues-windows-11-21h2#2924msgdesc](url)

**Comment by rhurey** [comment] 2022-10-21 23:25
I'll close this then. Thanks.

**Closed by rhurey** 2022-10-21 23:25 UTC

**Comment by chenjunhua8080** [comment] 2023-08-08 06:17
how to do with linux centos 7 ?
