### ISSUE TITLE
IngestClient does not support multi-channel for batch transcription

### ISSUE THREAD

**Issue by lenisha** [Azure-Samples/cognitive-services-speech-sdk#2185] opened 2023-12-19 05:53 UTC
**Describe the bug**
Given a multi-channel  audio file , Ingest Client batch mode does not support sending channels to Speech Service parameters
https://learn.microsoft.com/en-ca/azure/ai-services/speech-service/batch-transcription-create?pivots=rest-api#request-configuration-options

```
channels:[0,1]
```
As a result getting "Invalid Data" error

**Comment by BrianMouncer** [comment] 2023-12-21 01:59
What is the source of your multi-channel audio.
This was designed to work with the microphone array in some of our speech development devices.

Depending on what you are trying to achieve, you might take a look at some of these samples, https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/ae1f23ea4afb7e34c5be2f2e88aa21b274b1c5c9/samples/cpp/windows/console/samples/speech_recognition_samples.cpp#L1164

Or if you really need to use the REST based batch APIs, I can ask one of the web services team to answer this question. 

Let me know if that answers your question, or if you have more details about what you want to do.

Brian.

**Comment by pankopon** [comment] 2024-02-28 01:01
Closed as answered since no further updates.

**Closed by pankopon** 2024-02-28 01:01 UTC
Labels: update needed
